### ISSUE TITLE
Give CoderDojo access to the CoderDojo organization on dockerhub

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1016]
Currently, I am the only one in the CoderDojo organization on Dockerhub:

https://hub.docker.com/u/coderdojo/

Who would like to join? Who should be admin?

**Comment by butlerx** [comment]
id like to be added, i think @Wardormeur and @DanielBrierton should be set as admins on the dockerhub

**Comment by niccokunzmann** [comment]
Okay, I added [butlerx](https://hub.docker.com/u/butlerx/). Can you check if the permissions are satisfy you?

**Comment by Wardormeur** [comment]
@niccokunzmann I'll send you an email through gitter, this is our generic one so we can keep control over time :)
We probably want to add @josmas to this also :)

**Comment by niccokunzmann** [comment]
@Wardormeur I tried to add this generic e-mail but it was not registered as a user on dockerhub. Could you register that e-mail so I can add you again?
@josmas I added you to https://hub.docker.com/u/coderdojo/dashboard/

**Comment by Wardormeur** [comment]
Sorry Nicco, totally forgot to come back to you on gitter.. Account has been created, thanks :+1:

**Comment by niccokunzmann** [comment]
@Wardormeur you are invited. You can check and close this issue.

**Comment by Wardormeur** [comment]
Thanks a mill !
