### ISSUE TITLE
Badge awarding emails not sent to parents of O13 Ninjas who don't have their own email

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1017]
Also, when adding an O13 to a parent, email is optional, but password is mandatory...

**Comment by Wardormeur** [comment]
Done on https://github.com/CoderDojo/cp-badges-service/commit/2207a68499f19c9f41f0b8e9f16f87b8193cbfb5#diff-0c697802e4b9da9ed2ad5ab9fb9c89beR74
