### ISSUE TITLE
inactive dojos shown on map and in search

### ISSUE THREAD

**Issue by butlerx** [CoderDojo/community-platform#1019]
dojos marked as inactive are still shown on the map and marked and in search for dojos

**Comment by Wardormeur** [comment]
@DanielBrierton @butlerx does this https://github.com/CoderDojo/cp-zen-platform/commit/01fda1a85d892e824c8b250cbe30f65a6b0fbab7 covered the issue?

**Comment by DanielBrierton** [comment]
@Wardormeur That commit specifically covers the list of Dojos, but the map was covered at some other point, so yeah, this should be all good now

**Comment by butlerx** [comment]
yep closed
