### ISSUE TITLE
List is not loading on slow connection

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1025]
Currently, I have a slow internet connection. The list of the dojos is a tab as is the map of the dojos. When loading the list, the map is still loaded in the background. There is no need for that.

Request: Please do not load the map while the list is loading.

Possible implementation: Make the list an extra site.

**Comment by Wardormeur** [comment]
We have plan for this page, as from the UI rework point, we want to have a dashboard when logged-in or a proper search w/ criterias when logged-out. Tho, it's far from done.
We'll surely get there, but splitting the page for a performance improvement isn't really in our plans right now..

**Comment by Wardormeur** [comment]
The list doesn't exist anymore, hence closing off
