### ISSUE TITLE
messages.po entries are removed and added again

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1026]
In the recent weeks I noticed, that entries in the messages.po files were removed and added again.
This leads to the following problems:
1. Translations are removed and show up as 100% matches which need to be translated again and approved.
2. Comments, issues and manual context information for these translations is removed.

Examples:

```
"You can view the" "Zen roadmap" " and see what we are working on, as well as the latest features for Zen."
```

How can this be solved?

**Comment by Wardormeur** [comment]
1. Translations should be removed if not used anymore, we caught of couple of them but feel free to point them out if you find some more. Alas we tried to update them but crowdin process to do so is.. impossible in the actual format (we would need to transpform the po into csv). One good start would be to split the po file to 1) contextualize, 2) minimize the scope of search/upload/download of file to only get what's necessary (i.e. the backend doesn't need all the strings from the front, still it's the same message source)
2. We're working on getting context through comments work, but compability wise, we need to ensure the gettext format is respected by all our dependancies. This is no only dependent from crowdin, but also from po2json that we use to translate the string on the front end and i18n used on middleware and backend

**Comment by niccokunzmann** [comment]
More Context: These were translated several times:
[![capture](https://cloud.githubusercontent.com/assets/564768/20482008/65fa43e8-afea-11e6-8431-98b1126b997e.PNG) 
![capture](https://cloud.githubusercontent.com/assets/564768/20482077/cd841eee-afea-11e6-9e18-140704cdede2.PNG)](https://crowdin.com/translate/zen-community-platform/1/en-de#5648)

**Comment by Wardormeur** [comment]
When did you see this happening?

**Comment by Wardormeur** [comment]
@rosalanghammer can we organize the translation cleanup/upload review for early 2017 ? This is a serious blocker for community translators ..

**Comment by rosalanghammer** [comment]
Yes cc'ing @PhilipHarney as he's still taking a lead on this cross platform. Adding to priority list on our side though for review.

**Comment by Wardormeur** [comment]
Hey @niccokunzmann, @DanielBrierton changed the way we save and deploy po files. We had a conflict where multiple repos were pushing and overwriting the translations on consequent deployments if they were not mutually updated. While we tried to be cautious for it not to happen, it definitely did a couple of times.
The architecture has been changed to externalize the repos by itself, now available at  https://github.com/CoderDojo/cp-translations
You can find more about it on the README of community-platform https://github.com/CoderDojo/community-platform/blob/master/CONTRIBUTING.md#translations
Sorry that it took so long :(
