### ISSUE TITLE
Remove claim badge step

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1036]
Rewording of new email; 

Hi [NINJA NAME],

Congratulations! You have just been awarded an official [BADGE NAME] for your skills! 
Your awesome new badge is now displayed on your CoderDojo profile here [LINK]. 

Check out all the other cool badges you can collect here. [LINK]

Keep coding cool!

The CoderDojo Foundation Team

**Comment by Wardormeur** [comment]
What abt if the guy is not a ninja? We keep the same format?

**Comment by rosalanghammer** [comment]
Yes Hi [Name of awardee] 👍
