### ISSUE TITLE
When adding an O13 to a parent, email is optional, but password is mandatory

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1038]

**Comment by Wardormeur** [comment]
@DanielBrierton ping, status?

**Comment by Wardormeur** [comment]
@DanielBrierton bump :)

**Comment by Wardormeur** [comment]
Doesn't reproduce on /my-children and FTB will override the "quick-adding" children flow from the profile page.
Added to FTB flow to remove this once it's finished

**Comment by Wardormeur** [comment]
FTB flow is published since .. Months. Closing as the original issue cannot be executed anymore (option removed)
