### ISSUE TITLE
Adding admin users

### ISSUE THREAD

**Issue by m2mathew** [CoderDojo/community-platform#1039]
Is there a way to add another mentor of my Dojo to be an admin-level user? We have two admin users, but need to add a third who is taking over many of our logistics.

Thanks! 💃

**Comment by rosalanghammer** [comment]
Hi @m2mathew On the manage users page you can add a 'Dojo admin' and 'Ticketing Admin' - anyone who is taking over logistics can be made these once they 'Join' the Dojo. 

See the two tick boxes checked here which makes people these admin roles and allows them to create and manage events as well as managing users! 

Closing this issue but please let us know if you still have any trouble with this.

![screen shot 2016-09-29 at 12 04 52](https://cloud.githubusercontent.com/assets/12827424/18951421/0896921e-863d-11e6-8890-02701209e427.png)

**Comment by m2mathew** [comment]
@rosalanghammer Is this the page of which you speak? I got here by clicking "My Dojos" from the upper right dropdown menu and then the "Manage" link under the word "Users".
![image](https://cloud.githubusercontent.com/assets/11624407/19019077/7f85d800-883e-11e6-9471-a3adfd72e99b.png)

I cannot get to any UI that resembles what you are showing in your picture. When I click on "View" link for a user I get this type of page:
![image](https://cloud.githubusercontent.com/assets/11624407/19019090/ef87fae8-883e-11e6-8327-e469a371755c.png)

Unless I click on my own and get a more robust set of options.
![image](https://cloud.githubusercontent.com/assets/11624407/19019095/0c139078-883f-11e6-9993-27b9c3f7fcb2.png)

I feel like I am missing a step or that the UI has changed recently.

**Comment by DanielBrierton** [comment]
Hi Mike,

It looks like you're not an admin of this dojo, but in fact just a ticketing admin. Only dojo admins have rights to assign roles and grand admin privileges to other users. I'd recommend asking the champion of your dojo for admin rights if you feel you should have them. They should be able to grant you these rights, and you would then be able to grant them to others.

Daniel

**Comment by m2mathew** [comment]
Thanks for the help, @DanielBrierton. We started a Dojo and one of our gung-ho interns naturally became the leader of the project. He recently returned to his last year of Masters degree before rejoining us full-time. Before leaving, he attempted to switch over the Dojo to myself and another mentor, but didn't see the way to do it. I will get back in touch with him to see if this issue sheds some light on getting us setup. 👍

**Comment by DanielBrierton** [comment]
No problem. We looked into the issue further since, and the reason you're seeing the behaviour you're seeing is that Dojo Admins are only given the right to manage events, edit the dojo listing, and award badges. You only have the right to modify roles of others when you are both a Dojo Admin **and** a Champion of the Dojo. If you wish to get these rights, you'll need to have a current Champion assign the Champion role to you.

@rosalanghammer Can you confirm that the above is the way it should be?

**Comment by rosalanghammer** [comment]
Yes @DanielBrierton or @m2mathew sounds like your Champion has moved on. If you just get him to email us and cc you in we can change that over no problem.

**Comment by m2mathew** [comment]
Hey @rosalanghammer and @DanielBrierton,

We continue to meet every two weeks and have a strong following here in the north side of Dallas. We have the resources to use your project and make it better through contributions (our office started and maintains the material-ui open source project...we have experience with the community!).

But when we check in to using the zen website for creating events and such, our main Dojo leader Jeff Ogata is listed as a Champion, but he cannot do anything other than view things. He is unable to make events and such. Our former Dojo leader Nitin Shetty is back working with us now again, too. Is it a backend issue that our UI tells us that Jeff is a champion but cannot access the "create events" or most of the champion-facing UI?

Thanks for any help!

**Comment by Wardormeur** [comment]
Hey @m2mathew :)
I just checked and you're right. For some reasons, Jeff is still the owner of the dojo, listed as a Champion, but every right has been removed from his account. Did anybody revoked those rights?
The ui changed a bit in between the original screenshot and nowadays, if that helps:
![selection_113](https://user-images.githubusercontent.com/1755357/27989460-2f204d94-6431-11e7-9ca0-401b2a1337eb.png)

**Comment by m2mathew** [comment]
@Wardormeur No one revoked those rights. I think that the last time we were dealing with this, we could make him a champion, but all of the abilities were not given to him. We couldn't figure out how to give him all that from this end. Can we grant him all access to his full powers?

That would be best since we do switch in and out of running to dojo depending on who is in town at our office.

**Comment by Wardormeur** [comment]
I checked in between my last message and Jeff was having full right, including permissions. 
Is this still an issue? If that's the case, i recommend we continue by email/slack as I doubt it's a bug per se.
