### ISSUE TITLE
Images for programming languages

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1043]

**Comment by hnotess** [comment]
What size/format images do you need?

**Comment by Wardormeur** [comment]
We'd better go for square based images, unlike those one we have (https://coderdojo.com/resources/) in order to display them in the profile afterwards

**Comment by hnotess** [comment]
It looks like for the [badges](http://kata.coderdojo.com/wiki/JavaScript_Path) you have available you've got a size of 150px x 150px. If that's a good size, I can work on getting png with transparent background full color images with a square canvas size of 150px x 150px prepped and ready for you over the weekend. 

Alternatively, SVG would be a great choice for badges to display on profiles at different sizes unless you need to support browsers earlier than IE9. And I can see with your project you might want to be open to as many browsers as possible.

**Comment by Wardormeur** [comment]
I dont' believe we will display them full size, at least not on the profile (may be on the event page afterwards once we link sessions to prog lang)
SVG are fine too (i don't believe we will support ie9 since we use flexbox in different places), it's just a matter of having them with transparent bkgrd and uniform in term of format :)

**Comment by hnotess** [comment]
OK. you can assign this issue to me. I can either attach the completed files to the issue or submit a pull request if you let me know the filepath where you want them saved.

**Comment by Wardormeur** [comment]
A PR would be better :)
You can find images in https://github.com/CoderDojo/cp-zen-platform/tree/master/web/public/img (preferably a new sub-folder ;) )
and to link the images, have a look at https://github.com/CoderDojo/cp-zen-platform/blob/master/web/config/programmingLanguages.js
Right now, it's a JSON, preferably will become a real part of our backend in the near future :)

**Comment by benjamingarcia** [comment]
@hnotess PR is ready? or I can take this issue? ;-)

**Comment by hnotess** [comment]
@benjamingarcia go ahead and get started as I haven't been able to get it completed.

**Comment by benjamingarcia** [comment]
@hnotess allright! thanks!

**Comment by Wardormeur** [comment]
Done through https://github.com/CoderDojo/cp-zen-platform/pull/1124
