### ISSUE TITLE
Ability to become Tao verified after dojo creation

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1045]

**Comment by Wardormeur** [comment]
See https://github.com/CoderDojo/community-platform/issues/951 for restriction to take care of

**Comment by sandrobonazzola** [comment]
Tao Verified is missing also on dojo creation, not only after dojo is created.
Newly created dojo, still missing tao verified mark: https://zen.coderdojo.com/dojo/b5eabc06-d7ea-42f4-ab98-e4f489765396

**Comment by Wardormeur** [comment]
Tao will be reworked post new Start a Dojo process.
We probably will hide the information considering it'll not be achievable in the meantime

**Comment by Wardormeur** [comment]
Tao has not made a comeback, closing
