### ISSUE TITLE
Recurring events can be created without any valid dates

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1052]
e.g. create a recurring event from 1st Oct to 3rd Oct that takes place on Fridays. No Fridays exist between these dates, but the event gets created anyway, causing issues afterwards with loading the event.

**Comment by Wardormeur** [comment]
fixed by https://github.com/CoderDojo/cp-zen-platform/commit/55fdcd2f09dd90790b71d8019676047fb5473be8
to close @DanielBrierton  or is there any other scenario ?

**Comment by DanielBrierton** [comment]
Yeah, I think we can close this for sure.
