### ISSUE TITLE
UI for adding children when booking event

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1063]
### Dependency: #1042

Allow a user to add children OTG in case you're bringing in somebody or simply go through the simplified registration/book a ticket process.

NB - Keep flow for ‘New applicant’ as is for Ticketing Admin.

**Comment by DanielBrierton** [comment]
May not be needed when we have add child as part of the registration flow.

Thoughts @rosalanghammer?

**Comment by rosalanghammer** [comment]
May still be needed for users who have already registered but haven't added kids. Needs re-examination when we look at registration and booking flows so leave open for now.

**Comment by Wardormeur** [comment]
Adding children is now supported through the new booking flow
