### ISSUE TITLE
Redirect to event after registering from event page

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1064]
### Dependency: #1063

When registering from an event page, you currently get redirected to the edit profile page. This is incorrect, as we have all the info we need. It should redirect back to the event booking.

**Comment by DanielBrierton** [comment]
After saving your profile post-registration, you are redirected to the event page. This middle step is no longer necessary as there is no further profile info required. Should probably be done as part of overall registration flow rework in #1176

**Comment by Wardormeur** [comment]
Closing, covered with Pivotal
