### ISSUE TITLE
Invite dojo members to an event

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1066]
## EPIC: #1062

Functionality was removed but should be added back in.

To be discussed with @rosalanghammer:
- Auto-approval of tickets from invites
- Augmenting "Notify all members" as a separate thing
  - Notify specific members, or specific user types

**Comment by rosalanghammer** [comment]
Not sure about auto-approval of tickets. Makes logical sense but if you've already chosen ticket approval I don't think it should bypass this as in reality makes a dojo a bit harder to run if this is not spelt out clearly. Especially when a Dojo is in high demand.

**Comment by DanielBrierton** [comment]
This functionality has already been added back in. #1178 created to cover notify members aspect.
