### ISSUE TITLE
My Dojos page redesign

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1072]
## EPIC: #962

My Dojos page should become a dashboard for users to go in and see contextual actions according to their role in the dojo.

**Comment by DanielBrierton** [comment]
Current mockup design, not yet final.

[my-dojos.pdf](https://github.com/CoderDojo/community-platform/files/516421/my-dojos.pdf)

**Comment by Wardormeur** [comment]
Covered by @BSKERRITT
