### ISSUE TITLE
Start a Dojo Redesign

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1074]
Full input needed in terms of requirements before planning. (@rosalanghammer)

**Comment by Wardormeur** [comment]
Should fix https://github.com/CoderDojo/community-platform/issues/1135

**Comment by Wardormeur** [comment]
Should fix https://github.com/CoderDojo/community-platform/issues/1104

**Comment by Wardormeur** [comment]
should handle https://github.com/CoderDojo/community-platform/issues/1045

**Comment by Wardormeur** [comment]
Should cover https://github.com/CoderDojo/community-platform/issues/1074
