### ISSUE TITLE
Youth profiles cannot be viewed by admins of a dojo which they are a member of

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1082]
Champions and Dojo Admins should be able to view profiles of the children within their dojo. This will allow them to see things like badges already awarded, programming languages and parent/o13 contact details.

**Comment by Wardormeur** [comment]
related to #1040

**Comment by Wardormeur** [comment]
@DanielBrierton to close ?

**Comment by DanielBrierton** [comment]
Yes
