### ISSUE TITLE
Event date not consistent

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1083]
![capture](https://cloud.githubusercontent.com/assets/564768/19537755/70209f28-9651-11e6-9847-8420f7406b9e.PNG)

![](https://raw.githubusercontent.com/niccokunzmann/uploads/master/temp/Capture.PNG)

![](https://raw.githubusercontent.com/niccokunzmann/uploads/master/temp/Capture2.PNG)

![](https://raw.githubusercontent.com/niccokunzmann/uploads/master/temp/Capture3.PNG)

The dates are not consistent.

**Comment by Wardormeur** [comment]
It's a timezone issue, we already fixed a couple of them lately.
We'll have a look shortly as it's quite critical :)

**Comment by DanielBrierton** [comment]
Hey Nicco!

Just to confirm, what is the correct time?

Also, is the event on the 22nd Oct supposed to be at 14:00, or should it be the same as all the others, at 15:00?

**Comment by niccokunzmann** [comment]
The correct time for all events would be 14:00 - 17:00.

**Comment by niccokunzmann** [comment]
Here is something that did not arrive via Mail:

My mental model:  
A Dojo has a place. The dojo time is always local to that place.

I conclude from that:  
It is unnecessary to transfer the time to a time zone model.
Converting back and forth only creates error.
It also introduces unforseen errors: When I copy an event over the summer time barrier, the time changes.
If the time is always converted from the local time to the time zone time back to the local time, it is more complex than just storing the local time.  
Here we see the error of a conversion being forgotten.

What I suggest:

-    Do not convert dojo times, thus reduce complexity.
-    Create a method that computes local time to time zone time if you really need this functionality.
-    Saving the local time reflects the users mental model in your database.

This is just a suggestion, so you may have a different view on the topic.

**Comment by Wardormeur** [comment]
We agree on "what you input is what you get".
The main problem is that we can't ignore Tzone because of DST in this case : when you create a recurring event, the TZ may change because of DST changes.
So that we prefer to handle the TZ overall than just an subset of it, even more when changing the actual behavior of event (what you see is what you get, whatever the TZ) will break all the actual events  :p
Daniel is pushing a fix today normally, we had a codebase which was splitted (different handling of dates) which was creating this issue. Nearly there :)

**Comment by Wardormeur** [comment]
@DanielBrierton @niccokunzmann does the latest changes seems allrighty ?

**Comment by niccokunzmann** [comment]
@Wardormeur All dates are consistent for me, now. I vote for closing the issue.

**Comment by Wardormeur** [comment]
Thanks @niccokunzmann !
