### ISSUE TITLE
"Book" button never completes loading

### ISSUE THREAD

**Issue by ercasta** [CoderDojo/community-platform#1094]
Some parents trying to book a ticket for my Dojo are unable to book the ticket as the page never stops loading. 

Unfortunately I don't have enough information to identify exactly the page on which this is happening (there are multiple "book" buttons in different pages, I don't know exactly which one is not working)

**Comment by ercasta** [comment]
It seems to happen when the room is full and the book request should go to the waiting list

**Comment by ercasta** [comment]
From further tests, the button is this one:

<button class="btn btn-primary" type="button" ng-click="applyForEvent(sessionApplication)" tabindex="0"><span ng-if="!event.ticketApproval" class="ng-scope">Prenota ora</span></button>

The behaviour is not tied to waiting lists. Tested from Chrome and Firefox

**Comment by Wardormeur** [comment]
Thanks, we'll have a look at it

**Comment by Wardormeur** [comment]
Actually @ercasta , could you link us which event this refers to? So we can set up a more straightforward scenario :)

**Comment by ercasta** [comment]
https://zen.coderdojo.com/dojo/dee9dfb4-1373-49bd-a184-626734cdae38/event/3c5a4a34-8780-452b-89fd-99d41d4a4834

**Comment by Wardormeur** [comment]
thanks :+1:

**Comment by DanielBrierton** [comment]
Thanks for pointing out thiss issue @ercasta, it helped us identify two further issues, #1097 and #1098. These three issues are all resolved and pushed to master now.
