### ISSUE TITLE
"Save" button on event does not work!

### ISSUE THREAD

**Issue by ercasta** [CoderDojo/community-platform#1105]
I'm trying to update an existing event. The "pubblicare" and "salva bozza" buttons do not work.

I also tried to create a new event, with the same result.

This is a very serious problem. As a result, I had to immediately revert to eventbrite for managing tickets from my next event.

**Comment by Wardormeur** [comment]
Surprising, we haven't done any major code change in a good week. Was this this week-end?
If so, we had a security audit ongoing that diturbed our services, it should work since monday. refers to this thread if it's the issue https://forums.coderdojo.com/topic/264/some-glitches-in-zen/15
If it's not, could you tell us what's your dojo name/web browser so that we look into it (a screenshot or a gif would be even better :))?

**Comment by ercasta** [comment]
It's the Lissone dojo: https://zen.coderdojo.com/dojo/it/lissone-province-of-monza-and-brianza/lissone , chrome (also tried on mobile, nothing happens)

Do you have any kind of automated test in place? Parents are getting really annoyed by these issue!

**Comment by ercasta** [comment]
Btw I tried less than 1 hour ago

**Comment by Wardormeur** [comment]
We're in the process of rewriting those, we'll have the basing bootstrap of e2e done by this week and will continue further to the end of the year so that we reduce all those issues.
We'll have a look very shortly (either tonight or tomorrow morning), thanks for the report :)

**Comment by Wardormeur** [comment]
I went through our logs and couldn't find anything in particular :(
Could you give me a couple of more details?
Which date is the one set? Did you ensure it wasn't a passed date/event?
Did you try by copying the event or was it a brand new one?
Did you ensured that there was no required fields missing (name, description, session name and session ticket) by opening/expanding every "card" (yeah, we should probably open those one if it's missing a required element cc @DanielBrierton ) ?

**Comment by ercasta** [comment]
First I tried updating an existing event. The event was scheduled for december 3rd, but had 0 available tickets because booking was not yet "open". So yesterday I tried to change the amount of available tickets and save the event, but the save button did not work. So I canceled the event and tried to create a new one, copying a previous event, and I faced the same behaviour. I don't know if there were any fields missing: for sure, no evident popup / error message appeared

**Comment by ercasta** [comment]
I don't know if this is relevant, but our dojo has two champions

**Comment by Wardormeur** [comment]
It should be fixed, it was a dependency which haven't been locked + a build process issue.
Can you confirm?

**Comment by ercasta** [comment]
Now the save button works, but the "cancel event" button does not! (Yesterday it was working)

**Comment by Wardormeur** [comment]
Which "Cancel" event are we talking about ?
The one from "Edit event" or the one from the "Event list" ?

**Comment by ercasta** [comment]
Edit event

**Comment by Wardormeur** [comment]
I think that's the issue ;) https://github.com/CoderDojo/community-platform/issues/1108

**Comment by ercasta** [comment]
Opened  #1110

**Comment by Wardormeur** [comment]
Saving works, and cancel is another issue, closing ! :)
