### ISSUE TITLE
Cannot add children

### ISSUE THREAD

**Issue by lordkada** [CoderDojo/community-platform#1109]
I'm trying to add my 2 kids (< 13 yo), but when I click the "save" button nothing happens.

(btw I'm a mentor from CoderDojo Milano - Italy)

**Comment by Wardormeur** [comment]
@DanielBrierton This should be fixed, am i right ?

**Comment by DanielBrierton** [comment]
I believe so @Wardormeur.

@lordkada Sorry, this managed to fly under our radar. Did you manage to get your kids added to your account since? Really sorry for the delay in getting back to you.

**Comment by lordkada** [comment]
yes, it worked. Thanks!
