### ISSUE TITLE
I have read and accept the Terms and Conditions here - no link

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1118]
When I visit the [German registration](https://zen.coderdojo.com/register/user) site, I see no link to the terms and conditions.
I believe it could be due to the key used [here](https://github.com/CoderDojo/cp-zen-platform/pull/1051/files/c9a44c777e4920d9f7db713f1de38b7909edfd67) which is not the same as in the messages.po file.
@rhemon - what do you think?

**Comment by rhemon** [comment]
I am not sure why its doing that, since locally for the msgid I changed msgstr to things and added the same anchor tag, and things worked fine

**Comment by niccokunzmann** [comment]
So, I do not understand why we still have this text:

    
![capture](https://cloud.githubusercontent.com/assets/564768/20869459/dcbf5c74-ba72-11e6-940b-a8c04b0e6362.JPG)


Here: https://zen.coderdojo.com/register/user
And without Link, if the changes go live automatically.

**Comment by butlerx** [comment]
this appears to be an issue with the translation on crowdin https://crowdin.com/translate/zen-community-platform/1/en-de#q=next

**Comment by niccokunzmann** [comment]
Can we re-open the issue until the translation shows up correctly?

**Comment by Wardormeur** [comment]
Even in english, the link doesn't show up.
It may be an issue w/ i18n not supporting HTML

**Comment by Wardormeur** [comment]
It seems to work for Deutsch though, can you confirm @niccokunzmann  ?

**Comment by niccokunzmann** [comment]
It supports HTML: https://zen.coderdojo.com/terms-and-conditions search for creative commons.

**Comment by niccokunzmann** [comment]
Confirmed. It works in German, now. It was not as I was looking at it.

**Comment by Wardormeur** [comment]
Probably the same issue than i had, browser cache :)

**Comment by niccokunzmann** [comment]
In crowdin it is translated: https://crowdin.com/translate/zen-community-platform/1/en-de#5723
I do not know: Is a "crowdin build" required for the translations to go live?

**Comment by niccokunzmann** [comment]
Let us see if the translation is live and in German and then, I will close the issue.

**Comment by butlerx** [comment]
crowdin is only built on deployment from circle so it is built and the text updated each time a pr is merged to master

**Comment by DanielBrierton** [comment]
To add to @butlerx's response, there is also the added complication of crowdin builds being rate limited, I believe to once every 30 mins. So, if two builds happen 20 mins apart and a translation is updated in between them, there's the potential for it to not get into the second build. You can be sure however that it will get into a future build, and we build fairly regularly.

**Comment by niccokunzmann** [comment]
Thank you all, this issue is resolved! @rhemon 
https://zen.coderdojo.com/register/user is German, now too.

**Comment by Wardormeur** [comment]
Don't forget to tick it on #934 :D
