### ISSUE TITLE
Dojo event not showing up on main page

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1121]
The event for the 17th of December is not showing up on the events section of the main page.

![capture](https://cloud.githubusercontent.com/assets/564768/20938612/033d2960-bbec-11e6-96b8-b209e793e486.JPG)
![capture](https://cloud.githubusercontent.com/assets/564768/20938713/68f370c0-bbec-11e6-8f4b-4408a0f5f9b8.JPG)
See, it is missing:
![capture](https://cloud.githubusercontent.com/assets/564768/20938764/8e2e193a-bbec-11e6-9a3b-7826e0ac847c.JPG)

**Comment by Wardormeur** [comment]
Hey Nicco,
We found what the issue was, we'll take care of it today :)
Cheers & thanks for the report !
G.F.

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by DanielBrierton** [comment]
Hey Nicco!

We got this fixed and deployed, your event is now showing up on your Dojo listing. Sorry for the inconvenience and thanks for the bug report.

**Comment by niccokunzmann** [comment]
Hi, no problem! Thanks for the platform :)
