### ISSUE TITLE
Tweak mobile styles for profile/Dojo profiles to include picture

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1123]
Right now, you can't see the profile image or Dojo image when viewing a profile page or Dojo listing. This also means you can't set one, as it has the same CSS rules applied on the edit page, hiding the image.

My proposal is to centre the image on the page and move the name underneath it.

**Comment by all-self-taught** [comment]
I modified the CSS and Templates on my local copy to allow the profile image to appear in the center on mobile devices (screen width < 767px). It'll be in my pull-request tomorrow. No tests were involved, as it was a UI enhancement. Simplest way to test is to narrow the browser screen until the pic appears in the center.

**Comment by Wardormeur** [comment]
Covered by @BSKERRITT
