### ISSUE TITLE
Error while opening manage event page on Zen "Error loading parents: [object Object]" 

### ISSUE THREAD

**Issue by paulolc** [CoderDojo/community-platform#1131]
When opening the manage event page on Zen the following error appears:
 "Error loading parents: [object Object]" 
![image](https://cloud.githubusercontent.com/assets/673004/21693110/8cbbd694-d377-11e6-8a3f-79db24bd4c1f.png)

Steps to reproduce:
1. Login as Mentor
2. On the top right user menu select "My Dojos"
3. On the line of a dojo you have admin permissions and in the Events column click "Manage"
4. Click on any session name
5. <ERROR!>

**Comment by Wardormeur** [comment]
Thanks for the report, we'll have a look at it tomorrow morning :)

**Comment by Wardormeur** [comment]
We had a similar issue 2 days ago, it only seems to happens after the µs is running for a good 2 days. We deployed more logs to understand what's going on.

**Comment by paulolc** [comment]
It's working now. Thanks!

**Comment by Wardormeur** [comment]
It should be fixed by now. A bug had been found in our cp-permissions plugin
