### ISSUE TITLE
Replace mailtrap by maildev

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1143]
In order to avoid rate limits of mailtrap, we should replace mailtrap by any nodejs based mail (ie maildev)
It should be included by cp-local so that the production stack is not impacted

**Comment by Wardormeur** [comment]
@butlerx complexity-wise, could cp-local spin up a maildev server ?

**Comment by butlerx** [comment]
that's relatively simple adding a mail server container wouldn't take much. 
Would we want it to actually send an email or just to kill all mail?

**Comment by Wardormeur** [comment]
replace mailtrap :) So the config for localhost config should change to use maildev instead

**Comment by butlerx** [comment]
sorry i misunderstood. adding maildev should be super quick as it already has a [container](https://hub.docker.com/r/djfarrelly/maildev/).
so in the docker-compose we can just add this and modify all the mailtrap references in the configs to maildev container

**Comment by Wardormeur** [comment]
@heyitsmaimai handled that without much issues :) https://github.com/CoderDojo/cp-local-development/commit/caa8eb64e8ea46e1e67174daac386df6cd2d047b
