### ISSUE TITLE
Dojo Page > Long Titles

### ISSUE THREAD

**Issue by ChristianVermeulen** [CoderDojo/community-platform#1150]
A minor UI issue; when the dojo title is fairly long it doesn't fit in the header anymore. Maybe the title width can be increased? There is plenty of space! :)

![screenshot 2017-02-21 10 28 29](https://cloud.githubusercontent.com/assets/1062751/23158732/87a38eae-f820-11e6-9059-698fb19ecd3b.png)

**Comment by DanielBrierton** [comment]
Note to self: Add longer dojo names to test data. 'dojo1' and 'dojo2' don't quite cut it. 😛 

@BSKERRITT is on it now, should have a fix deployed shortly!

**Comment by DanielBrierton** [comment]
This is fixed by @BSKERRITT's PR #1096 which was merged earlier today.

Thanks for the bug report @ChristianVermeulen!

**Comment by ChristianVermeulen** [comment]
![](https://m.popkey.co/9eaff1/yl1EQ.gif)
