### ISSUE TITLE
Split out day and time on Dojo listing

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1152]
Needs to be defined time/day so that this is easily searchable in the future - this field is currently freetext.

For current freetext field when implemented - we would still want it to be viewable so making it viewable where it can then be over-rode by entering this text. Also need to consider how this free text could be searched if new map settings are implemented. 

Related to #897 - specifically to make map or list easily searchable by day and time that either a parent or mentor may be free.

**Comment by DanielBrierton** [comment]
We should make it so that when editing a Dojo, you need to fill in the new format, while the old format will continue to be shown for those who have yet to update. In time, we can consider phasing out the old format entirely.

**Comment by Wardormeur** [comment]
Closing off, covered through SAD
