### ISSUE TITLE
Update to latest Node.js LTS

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1156]
As of writing, this is v6.9.5.

Main blocker for this right now is lack of e2e tests. We can't upgrade in confidence that everything still works.

**Comment by Wardormeur** [comment]
This is a WIP. Version being worked on may differ 
Done so far : 
- [x] cp-orgs (8.x)
- [x] cp-zen-frontend (6.9)

**Comment by butlerx** [comment]
frontend is done on 8.x

**Comment by Wardormeur** [comment]
Done since early january
