### ISSUE TITLE
Ensure all JS files are linted and checked during build

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1163]
My preference would be for all code, front-end and back-end, to be compliant with semistandard. I'm open to debate on this though. /cc @Wardormeur

Currently a mix of semistandard and jshint is used, with some files not being covered by the linter at all, making code styles inconsistent across the repos.

**Comment by Wardormeur** [comment]
This is a WIP. Choice is a custom config based on airbnb
Covered : 
- [ X ] cp-zen-frontend

**Comment by butlerx** [comment]
this is done for cp-orgs 
and [#1189](https://github.com/CoderDojo/cp-zen-platform/pull/1189) will cover this for cp-platfrom

**Comment by butlerx** [comment]
- [ ] cp-badges-service
- [ ] cp-dojos-service
- [ ] cp-eventbrite-service
- [ ] cp-events-service
- [x] cp-organisations-service
- [ ] cp-users-service
- [x] cp-zen-frontend
- [ ] cp-zen-platform

**Comment by Wardormeur** [comment]
closing off, has be done during the node 8 upgrade
