### ISSUE TITLE
Reduce dependence on Angular resolves

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1164]
Resolves make routes take longer to load, as each page waits for all resolves to ... resolve... In the meantime, the user doesn't see any activity happening, confusing them.

I also suspect that these are what's causing the issues with minifying our front-end code (#703) although I have no evidence to support this. 😅 (My theory is based off the fact that the resolves use dependency injection, but don't use the array syntax.)

**Comment by Wardormeur** [comment]
Closing issue, we migrate into another framework
