### ISSUE TITLE
Send a reminder when notify members

### ISSUE THREAD

**Issue by jeroennijhof** [CoderDojo/community-platform#1167]
When you notify members for an event make sure to send a reminder to the ones which already booked.

**Comment by jeroennijhof** [comment]
https://github.com/CoderDojo/community-platform/issues/568

Describes it way better but shouldn't this be a priority? I mean for events it's one of it's primary needs.

**Comment by rosalanghammer** [comment]
Hey @jeroennijhof - yes we already have this issue so I'm going to close this, if you could +1 in there that would be great. We have a small team (of only 2 developers) and this is not on our current roadmap for development, which is full up until June, but it's very highly prioritised for contributors on our waffle board (https://waffle.io/CoderDojo/community-platform) and we're hoping that some external contributors will be able to pick off these issues. If you know of anyone or if you can contribute it would be much appreciated by not only us but also the wider community :)
