### ISSUE TITLE
Add Open Graph meta tags for facebook sharing

### ISSUE THREAD

**Issue by ChristianVermeulen** [CoderDojo/community-platform#1168]
When sharing an event / dojo on Facebook there is nothing in the preview.
Not even a proper title or description 😢.

![screenshot 2017-03-09 09 10 57](https://cloud.githubusercontent.com/assets/1062751/23741345/585b52d2-04a8-11e7-89c6-01e34d5fcc8e.png)

Could we at least at:
- og:title => `CoderDojo {name} | Zen`
- og:description => `{EventName} at {coderdojoName} on {date}`
- og:image => e.g. map preview with location marker or default image with register call to action

This would increase social engagement tremendously!

**Comment by Wardormeur** [comment]
Yep, it's here :) https://github.com/CoderDojo/community-platform/issues/1059

**Comment by Wardormeur** [comment]
this https://github.com/CoderDojo/cp-zen-platform/pull/1101 should take care of opengraph
