### ISSUE TITLE
Dojo list does not scroll

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1169]
The dojo list loads for a while and then it does not scroll to India:
https://zen.coderdojo.com/?list=true#India

I would like, once the list is successfully loaded, that it scrolls down to India.

**Comment by Wardormeur** [comment]
It seems that the anchor is applied upon click, but not taken into consideration while loading the page.
Definitely a bug, thanks @niccokunzmann :+1:
