### ISSUE TITLE
List issues on up-for-grabs.net

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1170]
We have a list of beginner issues. I would like to list them on http://up-for-grabs.net, so open-source new comers can find them.

Hints:
- [List of Projects](https://github.com/up-for-grabs/up-for-grabs.net/tree/gh-pages/_data/projects)
- [List of beginner issues](https://github.com/CoderDojo/community-platform/issues?utf8=✓&q=label%3Abeginner)

**Comment by niccokunzmann** [comment]
I found that there is a listing already: https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/coderdojo.yml

**Comment by niccokunzmann** [comment]
So, I am closing this although I do not understand the difference between `up-for-graps` and `beginner`.

**Comment by Wardormeur** [comment]
Ah, just to answer and explain. Correct me if I'm wrong @DanielBrierton 
"beginner" are for somebody who wants to try to get familier with the stack, while up-for-grab is more of a "nice-to-have" that we can't cover time-wise atm
