### ISSUE TITLE
Expand Manage Users CSV export

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1173]
Request from community to expand to include'
- Age of child (not necessary to include parent email
- Parent name

**Comment by Wardormeur** [comment]
As per https://github.com/CoderDojo/community-platform/issues/1095, parent email is already exported.
Is there an issue with existing export?

**Comment by rosalanghammer** [comment]
Sorry edited to reflect the actual request **Doh**

**Comment by all-self-taught** [comment]
I added a pull request for this request, branch addExportAge.

**Comment by Wardormeur** [comment]
Review and merged, thanks !
