### ISSUE TITLE
New Registration Flow

### ISSUE THREAD

**Issue by DanielBrierton** [CoderDojo/community-platform#1176]
https://codepen.io/danielbrierton/full/VPMWWN/ to be used as basis. Still needs further UI refinement (e.g. adding multiple children, actually create the last two pages, etc.)

@rosalanghammer has also been looking into this and may have some stuff to add

**Comment by rosalanghammer** [comment]
Worth having a note about DoB that it's not displayed on your profile as this comes up time and time again with parents. 

Need design; when U13 DoB is entered we need a screen/message telling parents they should enter their details. 

Also town/country fields did we say we were going to scrap this as not necessary? At least town can definitely go, country is nice to have.

**Comment by Wardormeur** [comment]
DoB being not visible needs to be checked by profile data tests

**Comment by Wardormeur** [comment]
Closing as the expected flow is now through the Dojo page/Book rather than the "Register" page
