### ISSUE TITLE
Incorrect tooltip text on Dojo icons

### ISSUE THREAD

**Issue by CiaraMcHugh** [CoderDojo/community-platform#1187]
- Tao icon says "Tao unverified" 
- Non-private icon says "Private Dojo"

![screen shot 2017-05-02 at 12 05 57](https://cloud.githubusercontent.com/assets/15370231/25615573/e5a0e75e-2f2f-11e7-9585-658050b37f11.png)

**Comment by Wardormeur** [comment]
Tao unverified is right : it's grey, not green.
