### ISSUE TITLE
How can i delete a child profile?

### ISSUE THREAD

**Issue by zhgabor** [CoderDojo/community-platform#1193]

**Comment by DanielBrierton** [comment]
Hi @zhgabor,

Unfortunately, we don't currently have the functionality to remove accounts from the community platform. If you drop us an email at info@coderdojo.com we'll be happy to take care of it for you though. Sorry for the inconvenience.

**Comment by Wardormeur** [comment]
I opened an issue so we can discuss the global workflow on how to solve this, see #1195
