### ISSUE TITLE
Zip code search anomaly on zen vs coderdojo.com homepage

### ISSUE THREAD

**Issue by CiaraMcHugh** [CoderDojo/community-platform#1199]
Searching for (American) zip code only rather than an address, with no matching Dojo found

On zen: you get the whole world map. i.e. no result
On homepage: map zooms in to the nearest Dojo 

If you instead search for an address (both zen and homepage) you get zoomed to the nearest Dojo as you would expect.
If there is a Dojo at the zipcode you search for, on both zen and the homepage it finds it and zooms in as you would expect.

e.g. 
searching for just "33615" 
I tried with "sheldon road" as an example address within the zipcode

nearest Dojo is Tampa Bay area (status In Planning) which has zip code 33626
https://zen.coderdojo.com/dojo/us/florida/11211-countryway-blvd-tampa-fl-33626/tampa-bay-area-upper-tampa-bay-regional-public-library
Searching for "33626" on zen finds the Dojo.

**Comment by Wardormeur** [comment]
@DanielBrierton Will this be covered by the rework of Search A Dojo ?

**Comment by DanielBrierton** [comment]
Once complete, yes, we should be able to use the same component on WP and Zen and have a consistent, better working search overall.

**Comment by Wardormeur** [comment]
The map has been removed, closing
