### ISSUE TITLE
No cancellation confirmation email when cancelling ticket through link in email.

### ISSUE THREAD

**Issue by grabartley** [CoderDojo/community-platform#1200]
When I cancel my ticket for an event through the cancel link in the confirmation email I received, I don't get an email confirming that the cancellation was successful.

**Comment by Wardormeur** [comment]
@rosalanghammer Should this be a scenario ?

**Comment by rosalanghammer** [comment]
Yes you should get a cancellation email when you cancel through email.

**Comment by Wardormeur** [comment]
Duplicate of https://github.com/CoderDojo/community-platform/issues/944
