### ISSUE TITLE
Event date not consistent

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1201]
The event date is not consistent. I guess, this has to do with German summer and winter time.

Example event: https://zen.coderdojo.com/dashboard/dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a/event-form/32ef9311-a95d-4619-989c-0ed62d366563

![grafik](https://user-images.githubusercontent.com/564768/27082820-89615928-5046-11e7-8622-1edaa9ef4375.png)
from https://zen.coderdojo.com/dashboard/dojos/events/user-events

Dojo URL: https://zen.coderdojo.com/dojo/de/brandenburg/potsdam/potsdam-hpi

See also #1083

**Comment by Wardormeur** [comment]
Interesting.
Thanks, we'll have a look, it may be a scenario that we forgot.

**Comment by Wardormeur** [comment]
Sorry @niccokunzmann the bot closed the issue :)
Can you confirm it's solved?
