### ISSUE TITLE
Updated users are not updated in dojo's users list

### ISSUE THREAD

**Issue by sandrobonazzola** [CoderDojo/community-platform#1202]
I had a parent user[1] which created child accounts[2][3] using her name instead of using her children names.
She joined the dojo[4] and then she updated her children accounts with correct names.
Looking at account pages[2][3] they seems ok now but in the dojo's member list[5] the parent name is still reported instead of the children names.
dojo's members list should refresh with updated data.
[1] https://zen.coderdojo.com/profile/5c24dc33-aeea-4149-9b0d-79ad9b17db4b
[2] https://zen.coderdojo.com/profile/6e4e2552-8f0b-4e23-9691-b1b0d4390a89
[3] https://zen.coderdojo.com/profile/20629ae7-1048-41e1-9c24-d90de9fd81cd
[4] https://zen.coderdojo.com/dojo/b5eabc06-d7ea-42f4-ab98-e4f489765396
[5] https://zen.coderdojo.com/dashboard/my-dojos/b5eabc06-d7ea-42f4-ab98-e4f489765396/users

**Comment by Wardormeur** [comment]
Hi Sandro,
You are right, it seems there is an issue when updating a profile name (cd_profiles), it's not reflected on the administrative user structure (sys_user).
We'll look into it asap
Thanks :+1:

**Comment by Wardormeur** [comment]
Once this will be released, please simply save again the profiles to update the underlying info

**Comment by sandrobonazzola** [comment]
@Wardormeur I would suggest to run a script as admin and do a mass save on all existing profiles.
It would be quicker than asking all registered users to re-save their own profile :-)

**Comment by Wardormeur** [comment]
I'll check db-wise if the inconsistency is the story of 10 or 1000 users.
Resyncing the profile of 30k users won't go easy on our architecture...

**Comment by Wardormeur** [comment]
I'm working on a backport script, shouldn't take long

**Comment by Wardormeur** [comment]
The backfill has been replayed, this shouldn't be an issue anymore.
Thanks @sandrobonazzola :)

**Comment by sandrobonazzola** [comment]
Thanks, looks ok to me now.
