### ISSUE TITLE
Notify All Members on Event page sends a generic email

### ISSUE THREAD

**Issue by owencutajar** [CoderDojo/community-platform#1205]
The UI on 'Notify All Members' asks an admin to pick an event to notify users about. However, the email that is sent is a generic invitation to 'Next Event'. This would be more useful if it refered to the selected event and directed users to the specific event page.

**Comment by all-self-taught** [comment]
See pull request #341 and #9, it's done in cp-dojos-service and cp-translations.

**Comment by Wardormeur** [comment]
We can't use the hashtag cross-repos ;)
https://github.com/CoderDojo/cp-translations/pull/9
and https://github.com/CoderDojo/cp-dojos-service/pull/341 for future review

**Comment by Wardormeur** [comment]
Just a small change to be done on cp-dojos, elsewhat it works, thanks @all-self-taught :)

**Comment by all-self-taught** [comment]
Small change is complete. Exposes only event name in code.

**Comment by Wardormeur** [comment]
I modified a bit your translations as the phrasing differed between some email.
Elsewhat, it's merged, thanks for your help @all-self-taught  and @owencutajar for reporting this improvement :+1:
