### ISSUE TITLE
Padding issue on "My Events" screen

### ISSUE THREAD

**Issue by m2mathew** [CoderDojo/community-platform#1206]
The empty state for **"My Events"** has an incorrect spacing on the left side.

Maybe an easy fix for a first-time contribution?

![image](https://user-images.githubusercontent.com/11624407/27987110-7cec3050-63ce-11e7-9c7e-21e80c39db41.png)

**OS:** MacOS 10.12.5 (16F73)
**Browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by all-self-taught** [comment]
What should it look like instead? Should the sentence be aligned with the yellow box above?

**Comment by m2mathew** [comment]
Hey, James, it should for sure line up with the edge of the yellow box, maybe even be in the line with the child text of that box. I am unsure about the larger design patterns for this site. However, it does look odd with `padding-left: 0` right there. 😀

**Comment by Wardormeur** [comment]
Accordingly to bootstrap's usage in this scenario, i believe the answer would be to have the banner full width and the text slightly padded.
To do so, i'd add .row to .cd-dashboard and replace .row from its children for .col-xs-12
![selection_118](https://user-images.githubusercontent.com/1755357/28178130-345839b2-67f5-11e7-90ef-7a68acc633f9.png)

**Comment by all-self-taught** [comment]
Ok, will work on it and submit a PR.

**Comment by all-self-taught** [comment]
Hi @Wardormeur,

I created a Bootstrap 3 panel, it makes the text flush with the text in the alert above, but there is a slight border around it, barely visible. Was wondering if you want to use that, or if you want a separate alert created for the "No events for your Dojo's" text. The separate alert could be red, and it will still make the text flush with the alert above.

<img width="652" alt="screen shot 2017-07-14 at 10 28 25 am" src="https://user-images.githubusercontent.com/16264518/28216338-4aa35686-687f-11e7-8a2d-564db0b7231e.png">

**Comment by all-self-taught** [comment]
Here's what it'll look like with a red alert:

<img width="1290" alt="screen shot 2017-07-14 at 11 00 11 am" src="https://user-images.githubusercontent.com/16264518/28217605-b63d1d9c-6883-11e7-9228-c968b41c5525.png">

**Comment by Wardormeur** [comment]
Do you have a branch we can have a look at ? :)

**Comment by all-self-taught** [comment]
Hi @Wardormeur see PR #1154 in CP-Zen-Platform

Thanks!
James

**Comment by Wardormeur** [comment]
Closing off as this page has been rewritten
