### ISSUE TITLE
Word-wrap issue with "Time" section in the Dojo home page area

### ISSUE THREAD

**Issue by m2mathew** [CoderDojo/community-platform#1207]
On our Dojo home page, there is an issue with word-wrap. We should not be using `break-all`, maybe use `break-word` instead?

Probably a great candidate for a first-time contributor to the project!

**[Frisco Coder Dojo](https://zen.coderdojo.com/dojo/us/frisco-tx/tx-frisco-call-em-all)**

![image](https://user-images.githubusercontent.com/11624407/27987179-f7c7efb2-63ce-11e7-80e2-315b3a71d003.png)

**OS:** MacOS 10.12.5 (16F73)
**Browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by rstein66** [comment]
Hi! Can I work on this? I'm new to the project & am setting up my local dev now

**Comment by Wardormeur** [comment]
Please, do so :)

**Comment by Wardormeur** [comment]
Both closed by @rstein66 and @DanielBrierton 's work on the new front-end :)
