### ISSUE TITLE
Supporter images not loading

### ISSUE THREAD

**Issue by m2mathew** [CoderDojo/community-platform#1208]
I cannot tell if this issue is specific to our Dojo home page, but our "Supporters" img tag is not loading its `src`.

**[Frisco Coder Dojo](https://zen.coderdojo.com/dojo/us/frisco-tx/tx-frisco-call-em-all)**

![image](https://user-images.githubusercontent.com/11624407/27987194-2a82f1c2-63cf-11e7-82c6-743a273628a2.png)

**OS:** MacOS 10.12.5 (16F73)
**Browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by butlerx** [comment]
this supporter image seems to link to https://www.call-em-all.com/ which isnt a image the supporter link needs to be changed to a link to a image

**Comment by Wardormeur** [comment]
Hi m2mathew,
Unless there is an issue with how to define the url of the supporter image, I believe @butlerx is right

**Comment by m2mathew** [comment]
Hmmmm, that's odd. I added those images long ago (maybe a year ago or so), and have never updated them. I will double-check. Thanks, gents!

**Comment by m2mathew** [comment]
Yeah, my fault. I had it pointing at a picture incorrectly. It is now pointed directly to our CDN, so all fixed up!
