### ISSUE TITLE
Mary does not want to see past events on the Dojo details/listing page

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#1210]
As Mary,
I do not want to view past events
so that I do not get confused about when the next event is taking place.

User acceptance
Given that an event has ended in the users timezone
When I navigate to the Dojo details page,
I should not be able to view the past event

Notes
Current is that events remain live 12 hours after they have ended.

**Comment by Wardormeur** [comment]
Closing off, the user's timezone is now used to query the event-service
