### ISSUE TITLE
Order events on dojo page by date

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1212]
![grafik](https://user-images.githubusercontent.com/564768/28997228-bded2346-7a0f-11e7-90bf-4a5b6907216e.png)
Page: https://coderdojopotsdam.github.io

The events should be ordered by date. Having the next event at the end is confusing.

**Comment by Wardormeur** [comment]
Same cause that https://github.com/CoderDojo/community-platform/issues/1139
A quick fix could be to re-order post-generation of the card, but the real fix is to provide the proper dates from the back-end instead of having the front generating them.

**Comment by iandouglas** [comment]
Add my vote to fix this please.

**Comment by Wardormeur** [comment]
This should be fixed as we reworked the events-service (https://github.com/CoderDojo/events-service)
