### ISSUE TITLE
Duplication of Address on Dojo Page

### ISSUE THREAD

**Issue by Giustina** [CoderDojo/community-platform#1213]
Addresses are duplicated in the 'Location' Section of the Dojo page. Have randomly checked 5 Dojos and the duplication its appearing on the majority. 

Example --> 
https://zen.coderdojo.com/dojos/us/long-beach-ny/long-beach-public-library 
https://zen.coderdojo.com/dojos/ie/dublin/dublin/dublin-docklands-chq

**Comment by Wardormeur** [comment]
Moved to PTracker as this is a WIP project
