### ISSUE TITLE
Can not book

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1216]
From a participant I heard that there are problems booking events. I can reproduce them:
![grafik](https://user-images.githubusercontent.com/564768/30533741-3e2a8b4e-9c5b-11e7-86c7-8ac0081d2f1d.png)
URL: https://zen.coderdojo.com/dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a/event/92157342-ecac-47e2-ae20-312eb744f188
Browser:
- Firefox ESR 52.3.0
- Opera 47.0
- Chrome Version 60.0.3112.113 (Offizieller Build) (64-Bit)
- Intenret Explorer 
![grafik](https://user-images.githubusercontent.com/564768/30533855-c15abf98-9c5b-11e7-95b4-2181351e13c5.png)

Same if I log in:
![grafik](https://user-images.githubusercontent.com/564768/30533872-ddb4411e-9c5b-11e7-9e41-822fcb455bb5.png)
URL: https://zen.coderdojo.com/event/92157342-ecac-47e2-ae20-312eb744f188

**Comment by Wardormeur** [comment]
Hey @niccokunzmann 
What you're seeing is an UX issue alas. The book button is for all the tickets displayed (Coder, Laptop, Mentor..)
When you click "Buchen", it'll display each ticket for this session and a dropdown to select the user from

**Comment by niccokunzmann** [comment]
I am logged in, where should I click? (Firefox)

![grafik](https://user-images.githubusercontent.com/564768/30534017-9f60eb5a-9c5c-11e7-958e-ee1ce516e0da.png)
URL: https://zen.coderdojo.com/event/92157342-ecac-47e2-ae20-312eb744f188

**Comment by Wardormeur** [comment]
Apologies, your first screenshot made me think it was an UX issue.
This should be fixed by https://github.com/CoderDojo/cp-zen-platform/pull/1184, we saw it this WE only and only affect the /event/:id; using the /dojo/:dojoId/event/:eventId would still work

**Comment by niccokunzmann** [comment]
@Wardormeur confirmed :)

**Comment by Wardormeur** [comment]
Hey @niccokunzmann ,
Sorry, forgot to tell you but the fix has been deployed yesterday :)
Thanks for the report :+1:

**Comment by niccokunzmann** [comment]
All fine. Thanks for your work on the platform!
