### ISSUE TITLE
Dojo Applications showing Dojo is not Private, when it has been marked as Private

### ISSUE THREAD

**Issue by nuala-louise** [CoderDojo/community-platform#1217]
In the backend of the verification process, when I check an application someone has put in, the application says a Dojo is not private, when the Dojo is in fact marked as a Private Dojo, and shows as private when you look at the Dojo page itself.

**Comment by AyoAlfonso** [comment]
Should be that some part of the backend isn't filtering the application event. But it received the event quite alright. 
Can I work on this ?

**Comment by Wardormeur** [comment]
Hey @AyoAlfonso,
You can surely pick it up. You need to start by creating an application (/dashboard/start-dojo) and set it as private ("Venue" step).
![screenshot from 2017-11-27 10-05-33](https://user-images.githubusercontent.com/1755357/33261420-9e76a344-d35a-11e7-8737-cb71b574e188.png)
The template is in the old front-end (https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/directives/dojo/lead/template.dust#L156)
My understanding, considering the API seems to return both "1" as a value, is that the filter is falsy.
Feel free to ask any question :)
