### ISSUE TITLE
Doesn't save changed profile image.

### ISSUE THREAD

**Issue by nuala-louise** [CoderDojo/community-platform#1218]
When I try to change [my Zen profile](https://zen.coderdojo.com/dashboard/profile/) image and click save it doesn't save.

It simultaneously shows as an error message with file type when file type is correct, and also saying it uploaded correctly; despite not saving.

**Comment by conoramurphy** [comment]
![screen shot 2017-11-14 at 9 58 11 am](https://user-images.githubusercontent.com/3603234/32773856-70193fe4-c922-11e7-80c0-b590aa20590a.png)

**Comment by Wardormeur** [comment]
This should be solved :)
