### ISSUE TITLE
Cannot download user list

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1221]
https://zen.coderdojo.com/api/2.0/dojos/export-users/0be123e7-c9be-4002-a3cf-f0c8550f749a-user-export.csv does not download the users as csv.
It takes a long time and times out with "File not found".

**Comment by Wardormeur** [comment]
Apologies for the delay @niccokunzmann , I'll try to have a look asap (cc @conoramurphy )

**Comment by Wardormeur** [comment]
Can reproduce in production.
Confirmed that it's insanely slow in general, according to Newrelic (40s+), and just most of the time end up in the browser giving up (timeout).

**Comment by niccokunzmann** [comment]
Hi, no haste, I just reported this and please work on it as you see fit.
I do not know what you apologize for.

**Comment by Wardormeur** [comment]
@niccokunzmann we've pushed a fix about a performance issue, can you tell me if that does solve your issue?

**Comment by niccokunzmann** [comment]
@Wardormeur Thanks! This was a fast resolution and a fast download just a minute ago. I can close this as this issue is resolved.
