### ISSUE TITLE
Daylight Savings changed Start Time of Event

### ISSUE THREAD

**Issue by csuski** [CoderDojo/community-platform#1222]
**Problem**

There seems to be an issue with daylight savings changing the start time of events.

I had a one-off event scheduled from 10am - 12pm for 3/17/2018

After daylight savings the start time (and only the start time) changed, so the event showed up as 11am - 12pm 3/17/2018.

I had to manually edit the event and change it back to 10am.

The event was created while in MST and as of March 11th I am in MDT. The switch from MST to MDT is when this occurred.

**Expected Behavior:**

The expected behavior is that the start time and end time stay the same once the event is created and neither the start nor the end time are modified when a change in day light savings occurs.

**Comment by Wardormeur** [comment]
Hey @csuski, thanks for the report :)
Could you give us the page where you saw the date to be wrong, as well as the event booking page (its id is what we're interested in :)) ? It could be a display issue as we're migrating our front-end stack, and changing the date may display it wrongly somewhere else.
Cheers

**Comment by csuski** [comment]
This is the event it happened to: https://zen.coderdojo.com/dojo/2541fe23-72b4-48ab-b60f-f3153cef5e33/event/595af78f-8de3-4058-9d7b-07db39d3b1d6

I first noticed it on the "event-form" page when I went to create a new event and copied it from the event listed above and I saw the wrong start time.

I then went to the event page (listed above) and confirmed the start time was incorrect.

I then went back to the event-form page, this time for the ID above "https://zen.coderdojo.com/dashboard/dojo/2541fe23-72b4-48ab-b60f-f3153cef5e33/event-form/595af78f-8de3-4058-9d7b-07db39d3b1d6" and the start time was incorrect there too so I modified it to the correct time and saved it.

**Comment by csuski** [comment]
Some more details

The workflow I use to create a events is to go to Manage  Events, then Create Event, then I copy the last event, change the date and publish. I have been doing this for a long time, so I am not sure how the copy works but perhaps I am propagating an old bug?

Also, I am pretty sure this happened to me in the fall when the time changed from MDT to MST. I noticed some times were an hour off on my events, and thought it was odd because daylight saving just happened, but I was more concerned about fixing the times than figuring out what the details of what happened.

------

I went looking to see if this was wide spread or if I could find the bug in action. It looks like for recurring events it isn't an issue (at least I couldn't find any that looked wrong). I found this CodeDojo that looks like it has the same issue I had. They list their event as 10 - Noon, but it is currently showing up as 11 - Noon.

https://zen.coderdojo.com/dojos/us/chillicothe-mo/mo-chillicothe-livingston-county-library

https://zen.coderdojo.com/dojo/b4b22432-c66e-4dfb-b028-f47595c379e7/event/5569e28b-2905-4a0d-9bb7-d7f341521a85

**Comment by csuski** [comment]
I found a recurring event that may have the problem.

The description says 9 - Noon, but the listed time says 10 - Noon. It looks like this is first event in a recurring event that was created prior to the time change.

https://zen.coderdojo.com/dojo/1150ecbb-9a72-44e4-91d2-be2d5bd728a5/event/8f2e3e00-855c-4e83-baf2-df56fcea600f

https://zen.coderdojo.com/dojos/us/zanesville-oh/zanesville-ohio-python-dome

**Comment by Wardormeur** [comment]
Hey @csuski 
Thanks a million for the very detailed research. We're planning it for asap, very likely next week :+1: 
My first guess would be the "copy" functionality (the other Dojo "MO, Chillicothe @ Livingston County Library" has events very similar), but I wouldn't jump to conclusion.

**Comment by Wardormeur** [comment]
Hey @csuski 
We pushed a fix that hopefully should cover our issue. We'll do a global communication about it as we can't automatically detect who's been affected (depends on the country, may have already fixed it, etc.)
Thanks for all your help :+1:
