### ISSUE TITLE
Cleanup of Dojo locations information

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1227]
**Business Goal/Theory**
For reporting and searching purposes, there are several issues with the location information of Dojos.

**List of issues to contend with**
- [ ] No regional information stored (county, state etc.)

**Comment by Wardormeur** [comment]
Closing, done on https://github.com/CoderDojo/cp-dojos-service/commit/0864a2b8cdc7936f34efbb84a8f6bacea0985037
