### ISSUE TITLE
As a prospective volunteer, I should have a clear and guided path all the way to attending an event

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1233]
**Business Goal**
A clear path makes sure we can push volunteering and know people aren't being lost along the way.

**To Do**
- [ ] Have a clear way of signing up as a volunteer on a club
- [ ] Once signed up they should be renavigated to the dashboard where get a notification saying "The Dojo has been told you want to volunteer" and are introduced to the path of progression.
- [ ] Send an email to them once their application to the Dojo has been sent saying the above and adding any information we can give them about safeguarding and guiding them along that path
- [ ] Send an email to them once their application has been accepted

**Possible Completion path**
- Prospective Volunteer (have you applied to a club)
- Community Volunteer (Have you been accepted to a club and booked in)
- Certified volunteer (Booked into a club and completed online safeguarding training)
- Something more? More training etc.?

**Comment by Wardormeur** [comment]
This seems like a duplicate/mix-match of multiple issues/epic, such as https://github.com/CoderDojo/community-platform/issues/1243
Are we continuing on this ?

**Comment by conoramurphy-zz** [comment]
Ya this was meant to be more epic-y. Thanks for tidying up.
