### ISSUE TITLE
Clean up "Where did you hear about CoderDojo" answers

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1236]
**Business Case**
The community team have researched and decided on a clarified set of answers to the "How did you hear about CoderDojo" question in the Start a Dojo form.

**Detail**
https://docs.google.com/document/d/1XxRrkV3DvnftCOI8KilMDVsOcIA-MeBbj4qUHTlt4ts/edit

**To be decided**
What happens to unmapped answers.
Whether we can add the "more detail" answer to all questions.

Previous | New (In order)
-- | --
Search engine | Search engine
Other CoderDojo Volunteers | CoderDojo volunteers
[no previous, new label] | Raspberry Pi Foundation / CoderDojo Foundation outreach
[no previous, new label] | Social media
Future Learn | Future Learn
[no previous, new label] | My employer (CSR scheme at work)
Events | Event / Conference / Training
[no previous, new label] | Library or youth group
Word of mouth | Word of mouth
Other | Other (comment field)
Other Coding Organisations | [no replacement, leave in db]
Development Community | [no replacement, leave in db]
Family/Friends | [no replacement, leave in db]
Media (newspaper/radio) | [no replacement, leave in db]

**Comment by ArayB** [comment]
Just to clarify, the entries that read [no replacement, leave in db] should not appear in the select on the form any more.
Previous answers for those options will stay in the database.

**Comment by conoramurphy-zz** [comment]
Exactly.
