### ISSUE TITLE
Redirection after Register Form should be to the dashboard

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1238]
**Business Goal**
The Zen dashboard is the focus and start of our UX flows. The prospective volunteers will have a much better experience if they land on the dash after they register.

**Current behaviour**
If you go, not logged in, through here https://zen.coderdojo.com/ and go to register. You end up here https://zen.coderdojo.com/register/user (to note most registrations are meant to happen "in flow" when booking/starting a club so this is effectively the old reg form). If they register here they end up on the edit profile page. 

**Desired behaviour**
When you register through https://zen.coderdojo.com/register/user you end up on the zen dashboard. >> https://zen.coderdojo.com/home

**Comment by Wardormeur** [comment]
Note that this shouldn't break flows such as accepting an invite

**Comment by Wardormeur** [comment]
Reviews available : 
https://github.com/CoderDojo/cp-zen-platform/pull/1334
https://github.com/CoderDojo/cp-zen-frontend/pull/238
