### ISSUE TITLE
Make potential volunteers contactable in mailchimp

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1249]
Add a user role/label in mailchimp `potential-volunteers` that corresponds to has application but has not been accepted.

**Comment by Wardormeur** [comment]
Wasn't part of the board, so didn't see it until now.
What's the scenario behind that? 
Limitation-wise, we're aware that there is a lot of old applications not being accepted while the user is part of a club already: should we filter out if the user is already a member of "any" Dojo, or just of the "current" Dojo, to avoid classifying them by mistake ?

**Comment by conoramurphy-zz** [comment]
I'd leave this. Seems more reasonable to add this to a CRM at this stage.
