### ISSUE TITLE
Send better communications when a volunteer applies to join a dojo

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1250]

**Comment by Wardormeur** [comment]
This has been started when the champion has been added to the list of recipient of the email, along the Dojo's email.
A rework of the email and the endpoint to validate or unvalidate a request shall be done to cover this task

**Comment by Wardormeur** [comment]
WIP:
 Translations/email templates:
https://github.com/CoderDojo/cp-translations/pull/100

Backoffice:
https://github.com/CoderDojo/users-service/pull/4

**Comment by Wardormeur** [comment]
Permission:
 - https://github.com/CoderDojo/cp-users-service/pull/306

**Comment by Wardormeur** [comment]
Clubs:
 - https://github.com/CoderDojo/clubs-service/pull/6

**Comment by Wardormeur** [comment]
Frontend: 
https://github.com/CoderDojo/cp-zen-frontend/pull/251

**Comment by Wardormeur** [comment]
Middleware:
https://github.com/CoderDojo/cp-zen-platform/pull/1356

**Comment by Wardormeur** [comment]
Translations, this time for the strings used in the frontend : 
https://github.com/CoderDojo/cp-translations/pull/101/files

**Comment by Wardormeur** [comment]
We need to block the v2 API to request a membership to ensure it doesn't try to send the old template, and crash

**Comment by Wardormeur** [comment]
Previous comment has been added on cp-zen-platform, redirecting old users and making the v3 API a bit flex to ensure retro-compatibility.
TBD: 
 - Merge cp-translations
 - update cp-translations in cp-zen-frontend
 - update cp-translations in cp-email-service
 - Merge the rest of it

**Comment by Wardormeur** [comment]
We're live
