### ISSUE TITLE
Show notification of pending requests to join for a mentor

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#1251]
Reference the case 2 of https://github.com/CoderDojo/community-platform/issues/1243

**Comment by Wardormeur** [comment]
Current status:
![Screenshot from 2019-03-25 14-19-02](https://user-images.githubusercontent.com/1755357/54926814-faf1e400-4f08-11e9-8d27-40d68014abab.png)
Considering this screenshot, I'd consider adding the date (or how long in days since he requested it) when the join request was created, so the user doesn't ask himself "When did I apply already?" or "Should I search another one now or wait a bit longer ?"
That would mean changing the messaging from "Wait a couple of days" as a first step to > ~7 days "contact support/look for another dojo"

**Comment by Wardormeur** [comment]
So that we're clear @conoramurphy : 
 -  the "join request" section should display only if your join request is less than 30 days
 -  the info box should display if the join requests are being displayed (less than 30 days) and the user account is less than 3 months 
Is that right or I messed up the time ranges?

**Comment by conoramurphy-zz** [comment]
@Wardormeur that's correct.
