### ISSUE TITLE
Currently does not work on EE

### ISSUE THREAD

**Issue by conoramurphy-zz** [CoderDojo/community-platform#1253]
Orginial comment here https://forums.coderdojo.com/topic/747/connection-drops-accessing-zen-coderdojo-com-over-ee-4g-in-the-uk

Pasting message here 

```
I haven’t seen anyone else report this issue but I’ve noticed that I can’t access zen.coderdojo.com over a EE 4G connection. I used to think the site was down a lot until I realised that it was only ever down when I was connected over 4G, when using WiFi the site was always fine. I’ve tested on iPad, iPhone & MacBook (multiple different accounts), in all cases the site is inaccessible over EE 4G, all other sites work fine. If I connect to my office VPN then Zen loads perfectly fine.

I suspect the issue is related to the IPv6 Configuration, if you check https://www.ssllabs.com/ssltest/analyze.html?d=zen.coderdojo.com&latest you’ll see that you get a connection error with both IPv6 addresses, but the IPv4 servers are fine. EE issues IPv6 addresses when connecting over 4G, so it would be trying to connect directly to the IPv6 addresses.

The simplest fix might be to disable IPv6 in CloudFlare for the zen subdomain. I assume this issue affects any ISP/telco issuing IPv6 addresses, which could be quite a lot of people.

I’m happy to test again if I can be of any further help sorting the issue.
```

**Comment by Wardormeur** [comment]
Multiple solutions to that:
 - Drop ipv6 support in Route 53 (meh solution) by removing the AAAA record
 - Solve the support in the ELB to ensure ipv6 is being carried over (the ELB are created by kops/handled in kubernetes, so let's avoid manual configuration changes) or translated (apparently, Classic ELB are translating ipv6 to ipv4 https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-internet-facing-load-balancers.html#internet-facing-ip-addresses) 
My recommendation would be to wait for the migration to EKS and implement it at that point. We "could" disable the AAAA record in the meantime to ensure nobody make use of it.
cc @grega

**Comment by grega** [comment]
@Wardormeur Interestingly, whilst the original post erroneously identifies Cloudflare's IPv6 implementation as the problem here, could we not enable Cloudflare's IPv6/v4 proxy for the zen / load balancer subdomains? This would take care of translating IPv6 requests to the IPv4 ELB.

**Comment by Wardormeur** [comment]
Went for your solution, indeed simpler than the others.
The test seems to work, will verify with the user on the forum

**Comment by conoramurphy-zz** [comment]
Checked on someone else's 4g EE. Works now. @Wardormeur happy to move to done?
