### ISSUE TITLE
[HTML/CSS] Make the calendar subscribe link blue

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#1256]
When viewing a [dojo page], one can subscribe to a calendar.
This link "Add to your calendar" should be blue so people know it can be clicked.

[dojo page]: https://zen.coderdojo.com/dojos/de/brandenburg/potsdam/potsdam-hpi

**Comment by CurtisHughes** [comment]
First time looking into this project, but I can look into updating the color of this link 👍

**Comment by Wardormeur** [comment]
If you have any questions, please shout :)

**Comment by CurtisHughes** [comment]
PR opened: https://github.com/CoderDojo/cp-zen-frontend/pull/253

**Comment by Wardormeur** [comment]
Closing, thanks a lot @CurtisHughes  !
