### ISSUE TITLE
Birthday Packs - form link to go on CoderDojo dashboard

### ISSUE THREAD

**Issue by nuala-louise** [CoderDojo/community-platform#1265]
The idea is two months before a Dojos birthday/anniversary this is triggered to show up on the Champions dashboard,  telling them to apply and giving them the form link:

“Your Dojo anniversary is approaching - [apply now for your FREE birthday pack](https://docs.google.com/forms/d/e/1FAIpQLScNDxfs7MP4aOA9f8iZPTuNl6NVO2RHpIch5VGwUDiupaGOxA/viewform) to celebrate”

It should stay on the dashboard until the birthday (day/month), to ensure those who only log in for monthly events don't miss it.

Any questions, just ask. All the best, Nuala

**Comment by Wardormeur** [comment]
I would recommend 2 weeks before and 2 weeks after.
Champions are already quite solicited in term of messaging, avoiding the chances of conflict seems reasonable as long as the time range for showing the message is relevant. 
That would change from "Your Dojo anniversary is approaching - apply now for your FREE birthday pack to celebrate" to "Your Dojo anniversary was near - apply now for your FREE birthday pack to celebrate" after the anniversary date.
What do you think ?

**Comment by nuala-louise** [comment]
@Wardormeur  The idea is to reach out to them from two months in advance so they apply for the pack and receive it in the post in time to hold a birthday Dojo event using the contents of the pack at the time of their birthday. 

Having it two weeks before and after doesn't give us time to receive and review the application, put together and post the pack, them to receive it and host an event on their birthday.

**Comment by Wardormeur** [comment]
Hum. I understand the logic, yet can't totally agree with it: a dojo running once per month/every 3 weeks is unlikely to change its rhythm. So the "birthday date" is actually, at best, a day out of a 2 week range.
On another subject: 
 - what happens if the champion has multiple dojos ? Should we add the Dojo name ?
 - what happens if the champion has multiple dojos anniversary at the same time ? Should we ignore it ? (which contradicts adding the name, btw)

**Comment by nuala-louise** [comment]
The form linked requires the champion to input the Dojo for which they are applying - if they have multiple at the same time, they can add it in the open text part of the form - so we can check them.

So we can either:

- avoid the name specifically because of the contradiction and let the form deal with multiple birthdays

- add in the Dojo name, and if two happen at once, two separate statements appear: eg.
"[Dojo Name1]'s Dojo anniversary is approaching - apply now for your FREE birthday pack to celebrate”
"[Dojo Name2]'s Dojo anniversary is approaching - apply now for your FREE birthday pack to celebrate”



Note: We're using the verification date as the date to work from - not their events near the date - they input the event they are hosting for the birthday on the form.

**Comment by Wardormeur** [comment]
![Screenshot from 2019-05-08 09-40-21](https://user-images.githubusercontent.com/1755357/57361874-5e606a00-7175-11e9-9fbe-32c2b61828e9.png)

**Comment by nuala-louise** [comment]
Looks great Guillaume!  
I think it would be easier to read if it said:
“[Dojo Name], your Dojo anniversary is approaching! Apply now for your FREE birthday pack to celebrate"
Just because the names are so random with the word "Dojo" gets lost in the name, but otherwise this is ace :) 
Thank you for making it work! :D

**Comment by Wardormeur** [comment]
![Screenshot from 2019-05-08 15-01-05](https://user-images.githubusercontent.com/1755357/57381127-418e5b80-71a2-11e9-82de-1699af68c93f.png)
