### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#147]
Can we have a 404 page with the regular header and footer and I will draft the content for the page (suggested links etc).

**Comment by tangentfairy** [comment]
Templates are https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/errors/404.dust and https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/errors/404_no_headers.dust

CSS is here https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/css/dashboard.less

**Comment by flakyfilibuster** [comment]
Hey there, would like to help out with this one - can you let me know what exactly you would like to see when hitting the 404?

Currently it just reads 'PAGE NOT FOUND!'

Cheers

**Comment by tangentfairy** [comment]
Hi @flakyfilibuster - thanks for your interest in helping out! 

I'm open to ideas on this one - we'd love something unique to CoderDojo - maybe something with pixel art ninjas. It'd be great to get some design help on this. I love the animation on the [Github 404 page](https://github.com/404) so it'd be neat to have something like that.

Do you have any ideas?

**Comment by niccokunzmann** [comment]
@tangentfairy If you specify it more, I can add tasks for Google CodeIn - You could also become a mentor in google codein to supervise this. It would look something like this:

> **Description**
>
> **Requirements:**
>
> **Expected Outcome:** 
> 
> **Links/Tutorials: **

And it should last about 3-5 hours and can be given to several students.

**Comment by tangentfairy** [comment]
If you can help the students to set up locally then that sounds good! They
might need help with making contributions.

On Monday, December 21, 2015, Nicco Kunzmann <notifications@github.com>
wrote:

> @tangentfairy <https://github.com/tangentfairy> I like the ides. If you
> specify it more, I can add tasks for Google CodeIn - You could also become
> a mentor in google codein to supervise this. It would look something like
> this:
>
> *Description*
>
> *Requirements:*
>
> *Expected Outcome:*
>
> *Links/Tutorials:*
>
> And it should last about 3-5 hours and can be given to several students.
> They could for example create pull requests to a certain folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/147#issuecomment-166403322>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by flakyfilibuster** [comment]
hey @tangentfairy,
unfortunately I am as bad a designer as I'm an artist - I was under the assumption that there are already some images or a finished design that needs implementation. 

You really don't want me drawing something :P

**Comment by tangentfairy** [comment]
@flakyfilibuster - we are still looking for design help on this one. For the moment, I'd be open to putting [something like this](http://codepen.io/HugoGiraudel/pen/dIDEx) on the 404 page and just putting a message that says:
 "Oops! This is not the page you are looking for. Maybe you'd like to check out some of the following fun sections of our site:
[Find your local Dojo](http://zen.coderdojo.com)
[Community Forums](http://forums.coderdojo.com)
[Kata, our community wiki](http://kata.coderdojo.com)
[CoderDojo community news](https://coderdojo.com/news/)
"

For me, doing the above would close this issue until we can make a fancier 404 page! :smile:

**Comment by niccokunzmann** [comment]
We can also make a CoderDojo contest out of this and put all the 404 designs in a new folder and each time a random design is chosen. One could put scratch projects there, iframes, images, ..., svgs, gifs, ...

**Comment by tangentfairy** [comment]
@niccokunzmann - this would be great in the long run!

**Comment by gisellegk** [comment]
@flakyfilibuster Let me know if I can help with design!

**Comment by flakyfilibuster** [comment]
Hey there,
sorry for the radio silence :(

I was actually looking for royalty free ninja pics, to pixelate, however if you can come up with some ideas or even images/ designs, that would be great.

**Comment by tangentfairy** [comment]
I think the CSS ninja I mentioned could be used! Then it'd be a really cool example of what you can do with CSS for our young ninjas too! :)

**Comment by flakyfilibuster** [comment]
Oh, I didn't know that one was fair game, that we need to honor some licensing rights etc, etc.

Well good then, I'll put that in - thanks.

**Comment by tangentfairy** [comment]
It's open source afaik!

**Comment by gisellegk** [comment]
http://blog.codepen.io/legal/licensing/ Anything public = MIT License

What if we animated the ninja so that it drops down from the "ceiling" on a rope or something?

**Comment by tangentfairy** [comment]
That's a really cool idea @gisellegk! Maybe if we can get the basic ninja up there first then we can "iterate" on it and improve it to animate :) It would be really cool to use CSS animations to showcase what CSS can do!

**Comment by flakyfilibuster** [comment]
Hey there, this is where I am right now:

Ninja stays centered in desktop and mobile view.
Obviously the text needs some padding/margins.

<img width="571" alt="screen shot 2016-01-11 at 8 21 53 am" src="https://cloud.githubusercontent.com/assets/2176610/12228515/dc1e9566-b83c-11e5-9913-0f950cd6c267.png">

<img width="303" alt="screen shot 2016-01-11 at 8 22 39 am" src="https://cloud.githubusercontent.com/assets/2176610/12228519/e0ab338c-b83c-11e5-9a53-7422c0c17cd0.png">


- Should the text be centered?
- How about moving the "Oops! This is not the page you are looking for." text above the ninja and the rest underneath?
- Are there some styleguides as to what type of tags the text should have? h2/h3 for main header? Just paragraphs?

Feedback is appreciated.
Thanks

**Comment by tangentfairy** [comment]
@flakyfilibuster: I like the text centered! I'd prefer the oops text to stay with the rest of the text as I think it is easier to read. 

We don't have a style guide at the moment - this is something we're looking at doing in the first quarter and have a volunteer designer working on it! I think the "Oops" could be in a h2/h3 - I'll leave it up to you to decide which :)

Looks great!

**Comment by flakyfilibuster** [comment]
hey @tangentfairy,
added a pull request https://github.com/CoderDojo/cp-zen-platform/pull/794

Can you have a look and let me know if anything is missing/ wrong?

Much obliged

**Comment by tangentfairy** [comment]
This is live now and looks really cool!

Let me know if you have any questions about other issues @flakyfilibuster - there are a lot at the moment (and most are actually small features). Some are not specced out but I can help with any of them.

If you want to join the Slack development channel ping me a mail on ursula@coderdojo.org !
