### ISSUE TITLE
Windows support for local development..

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#165]
gave the new cp-local-development a shot on windows, you have to install a ton of things (git/python/java/node/postgres/elasticsearch) which takes time, but once you get past all that I now have two issues:

1) cp-dojos-service will not npm install, gives the following odd error, the resolution for which seems to visual express (https://github.com/TooTallNate/node-gyp#installation) - a 9G download!

```
c:\Users\IEUser\coderdojo\cp-local-development\workspace-phase1\cp-dojos-service
\node_modules\seneca-mail\node_modules\email-templates\node_modules\juice2\node_
modules\jsdom\node_modules\contextify>node "c:\nodejs\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available too
ls versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
```

2) the salesforce service will not start, gives the following:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'c:\tmp\newrelic_agent_salesforce.log'

**Comment by wolf99** [comment]
Just trying to get this working on my own windows laptop at the moment so will note anything I come across. Firstly, to npm install node-gyp I needed to update node from the recommended 0.10.38 to 0.10.40 (Just grabbed the msi installer from the nodejs site and installed it over the older version)

**Comment by niccokunzmann** [comment]
As a side note: There is a [virtual machine](https://github.com/niccokunzmann/cp-docker-development) available for development under Windows. You can tell me what you think about it of you like. Of cause that does not replace native windows support. Is setting this up under Windows natively a goal? One would need to convert the .sh files in the repositories or duplicate them.

**Comment by tangentfairy** [comment]
@niccokunzmann yes, it is a long term goal. Some other members of the community have already made progress with it!

**Comment by Wardormeur** [comment]
Apparently works thanks to Docker now :)
cc @DanielBrierton should be able to confirm !

**Comment by DanielBrierton** [comment]
Yup, I've successfully ran Zen on Windows 10 Pro using Docker (via Hyper-V – I assume it will work on non-Pro Windows with Virtualbox-based Docker, but haven't tested that).
