### ISSUE TITLE
Ability to open links in a new tab

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#194]
So this is a strange one, but funnily enough I actually do this a lot in my own flow of surfing so I think we need to fix it:

When logged in, ctrl click (or right click) "Logout" or right click and open in new tab ... In new tab I am still logged in.

Same for Dojo links when you go to "find a dojo"

**Comment by rosalanghammer** [comment]
Definitely a barrier if unable to open multiple Dojos at once to compare and find information. This and #807 make looking for a Dojo a difficult experience.

**Comment by Wardormeur** [comment]
logout doesn't allow to be ctrl-clicked anymore since the new menu :)
