### ISSUE TITLE
Need to update footer

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#206]
Updated footer on the main site to remove emails, need to update it. Will assign myself!

**Comment by kennanseno** [comment]
@tangentfairy what is left to be done on this one? just the text size for the 'where are you?'?

**Comment by kennanseno** [comment]
@tangentfairy also, instead of putting a line of text below the search bar, how about just making the 'where are you?' text to bold.

This is how it'll look like on font size 20 bold:
![location](https://cloud.githubusercontent.com/assets/7852866/10617765/131b087a-7764-11e5-876b-2f6ebca5c13e.JPG)

**Comment by tangentfairy** [comment]
I know we recently did some user testing so the criteria for this issue may have changed. @LauraCDF will let you know!

**Comment by tangentfairy** [comment]
This issue was originally for the footer, please create a new issue if you want UI updates to the homepage. Closing this as footer is completed.
