### ISSUE TITLE
Display message on Badges page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#210]
If you're logged in with "Dojo Admin" permissions, can we have a message that says "If you'd like to award a badge, please visit the manage users section in My Dojos" and "My Dojos" is a link to the My Dojos page.

**Comment by tangentfairy** [comment]
Badges template is https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/badges/index.dust

Badges dashboard controller is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/js/controllers/badges-dashboard-controller.js where we'll need to load the user permissions and check if they have the "dojo-admin" permissions.

**Comment by mef** [comment]
@tangentfairy I may work on this one. Is there another controller already checking the user permissions, that I could use as an example?

**Comment by tangentfairy** [comment]
@mef this would probably be a good example https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/js/controllers/edit-dojo-controller.js#L412

**Comment by tangentfairy** [comment]
Hi @mef, just wondering if you'd still like to take on this issue?

**Comment by mef** [comment]
@tangentfairy I'm afraid I won't have time to soon to continue the work on this one.

I have just pushed what I've done so far, cf. [this commit](bcfa0af). Basically the UI is done, but the controller update is still to be developed.

hope this helps,

**Comment by tangentfairy** [comment]
Thanks @mef

**Comment by tangentfairy** [comment]
Just deployed a fix for this
