### ISSUE TITLE
Reoccurring events

### ISSUE THREAD

**Issue by tangentfairy-zz** [CoderDojo/community-platform#221]
We have the option to have a weekly reocurring event at the moment and I know we said we'd only have it weekly, but we're sure that many Dojos have biweekly events now.

So we need to have a radio button, where if you click "reoccuring" you can pick "biweekly" or "weekly" on a given day.

**Comment by dmwelch** [comment]
@david-cahill how difficult would it be to add "every 1st/2nd/3rd/4th <weekday>" of the month?  Our dojo is every second Saturday and we'd like to make them reoccuring.

**Comment by Wardormeur** [comment]
Closed issues are closed, I opened a new one for you :)
Feel free to comment/provides more info on #1127 !

**Comment by dmwelch** [comment]
@Wardormeur Thx!
