### ISSUE TITLE
Local mailcatcher

### ISSUE THREAD

**Issue by tangentfairy-zz** [CoderDojo/community-platform#304]
Relying on an internet connection for the local dev environment for the mailcatcher is not ideal, so it would be nice to implement a handy setup for http://mailcatcher.me/

Requested by myself

**Comment by DanielBrierton** [comment]
There are other issues with developing offline that we can't really address, like the Google Maps and Captcha APIs. I question the RoI on implementing something for offline dev. @Wardormeur, any thoughts?

**Comment by Wardormeur** [comment]
It goes further than that alas.. We started using s3 for storing images, which can hardly be mocked.
I'd be enclined to have this kind of service once we have a proper docker setup as the actual setup is already "hard" to deploy.

**Comment by Wardormeur** [comment]
Email has been handled by maildev. 
There is still the question of others services, but this issue can be closed in the meantime
