### ISSUE TITLE
Set obvious default values when Parent adding a child

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#331]
country, city/town and address should default to be the same as the parent adding the child - makes the form less tedious to fill out (as it is tedious, e.g. why is 'alias' a required field?)

**Comment by Wardormeur** [comment]
@DanielBrierton covered by you, am i right?

**Comment by DanielBrierton** [comment]
Yeah, this is covered by my new add child form. Will be sure to close when deployed.

**Comment by Wardormeur** [comment]
Closing, it's been covered by my children && the new booking flow
