### ISSUE TITLE
Not showing Champion in profile

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#338]
* I registed as a parent
* created a dojo (went through the champion process)
* my profile still is parent

Profiles should probably list all your types, e.g. champion, mentor, parent, etc /cc @tangentfairy

**Comment by Wardormeur** [comment]
@rosalanghammer should be closed as we don't display this anymore ?

**Comment by rosalanghammer** [comment]
Yes, closing as default user type to begin with.
