### ISSUE TITLE
nginx entity size limit

### ISSUE THREAD

**Issue by ckiss** [CoderDojo/community-platform#346]
when I try to upload a larger file as profile avatar I get this:

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

**Comment by tangentfairy** [comment]
This was sorted post live launch
