### ISSUE TITLE
Resend award badge link.

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#385]
at the moment the award badge link in email can only be sent once. In a case where the email gets deleted or magically disappears, there’s no way to resend the the award badge link or send a new link for the same type of badge.

**Comment by DanielBrierton** [comment]
Badges are now automatically accepted, so this is much less of a problem. I think we can close this. @Wardormeur?

**Comment by Wardormeur** [comment]
Should we notify users with pending badges about accepting those? @rosalanghammer

**Comment by rosalanghammer** [comment]
Yes @Wardormeur @DanielBrierton lets do a mailshot on that. 

'Hi User_firstname,

You still have CoderDojo badges to accept and add to your profile. Just click the link below to claim your badge. 

LINK

Best wishes, 

The CoderDojo Foundation Team'

or something similar :)

**Comment by Wardormeur** [comment]
Closing off
