### ISSUE TITLE
Ability to copy past event

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#410]
Request from community member to copy a past event to make a new event:

"Allow people to start a new event by copying a prior event. Although we try to meet weekly during the school year, we ticket each event separately unless it's a special multi-week workshop. The recurring feature is good for the multi-week workshops but not the regular weekly meetup."

**Comment by tangentfairy** [comment]
Add a checkbox at the top of the create event form to say "Copy past event details" beside the checkbox there will be a dropdown where you can select the date of a past event to copy it into the form.

**Comment by rosalanghammer** [comment]
Already deployed :)
