### ISSUE TITLE
Create Over 13 account using U13 button and vice versa

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#431]
Need a way to validate the date of birth field when creating O13 and U13 accounts. At the moment, a parent can just create in the Over 13 section for his U13 child.

![screen shot 2015-08-14 at 16 36 24](https://cloud.githubusercontent.com/assets/7852866/9277589/211c2ce2-42a3-11e5-8595-77611d7c2475.png)

**Comment by Wardormeur** [comment]
@DanielBrierton To close?

**Comment by DanielBrierton** [comment]
This isn't done, but will be by me today with my cd-add-child directive

**Comment by Wardormeur** [comment]
@DanielBrierton bump !

**Comment by Wardormeur** [comment]
Add-children now redirect to My children, closing off
