### ISSUE TITLE
Charter is in half Italian, half English?

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#439]
I was logged in as someone else and had changed the language to Italian, now I'm logged in as a new user viewing the charter. 

Some of it is in Italian and some of it is in English... 

![screen shot 2015-08-17 at 16 35 18](https://cloud.githubusercontent.com/assets/1136491/9308821/128802fc-44fe-11e5-8cff-a69a5094f591.png)

**Comment by daveymoran-nearform** [comment]
this is a caching issue, chrome dev tools shows that when this issue occurs, the page call is loaded "(from cache)".
