### ISSUE TITLE
Per Dojo statistics page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#442]
Add a page for each Dojo to show relevant statistics about that specific Dojo.

Anyone with Dojo admin permissions in the Dojo can view including the champion. 

Will have charts with the number of events, segmentation of user types, etc.

CDF admins will be able to view this per Dojo.

Requested by @Giustina

**Comment by tangentfairy** [comment]
Would like comments on what specific statistics we'd like to see here. Will need to draw up a wireframe if this is to be a go!

**Comment by niccokunzmann** [comment]
Some ideas

- Number of sessions had
- median or average days between sessions
- number of attendees (maybe even per type)
- actual number of people attending (This statistics needs to be filled in after dojos. It is useful to know how many people come)
- (programming-)languages of attendees
- badges awarded at dojo
- total badges present at dojo/next event
- histogram of how often people attended CoderDojos 
- histogram of user types

- Maybe it is even interesting to mark specific sessions and create a statistics out of that. One could have a time slider to mark an interval and the statistics is computed from that.
- Maybe it would be interesting to see trends, too.

**Comment by Wardormeur** [comment]
See #1006
