### ISSUE TITLE
Prefill champion registration form for new champions who are existing users

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#448]
For someone who has already signed up as a mentor/parent and has filled out their profile info: It would be good if when they clicked on "start a dojo" it prefilled the fields with information from their profile.

**Comment by mihaidma** [comment]
should be fixed by https://github.com/CoderDojo/cp-zen-platform/pull/755

**Comment by Wardormeur** [comment]
Most of it will be removed in the renewal of the SAD process :)
