### ISSUE TITLE
Cannot update profile on the forums when a user has the same name as you already taken.

### ISSUE THREAD

**Issue by thekemkid** [CoderDojo/community-platform#451]
For some background, the zen platform tries to create users on the forum with that users `username` field to be set to the slugified user `name` field.

Say we have two Brian's. Brian1 and Brian2. 

Brian1 signs up to zentest and then creates a forum account. On the forum, the users `username` field is set to be 'brian'. This means you can mention `@brian` in comments, get to his profile at forums.coderdojo.com/users/brian etc and so on and so forth.

Brian2 then signs up. He then goes to the forums and creates his account. Zen tries to set Brian2's `username` field to be 'brian', which is already taken. So Brian2 gets a username which is unique, like `brian1`. This, however, breaks Brian2's ability to update his profile on the forum.

**Comment by tangentfairy** [comment]
Closing this, as we'll solve it with this solution: https://github.com/CoderDojo/community-platform/issues/452
