### ISSUE TITLE
Recommended Practice Reminder email

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#463]
We want to send out an email automatically to a newly created Dojo to remind them to complete recommended practice - this is if they have not completed any of the steps on the setup your Dojo step. 

Will be sent after 4 week if any of the steps were not completed.

**Comment by tangentfairy** [comment]
Hoping @rosalanghammer can take a peek at this and let me know where she needs help

**Comment by rosalanghammer** [comment]
@tangentfairy RP Email workflow created in the sandbox & ready to be deployed.

Email will be sent 28 days after a Dojo is verified to remind them to complete Tao.

**Comment by tangentfairy** [comment]
@rosalanghammer deployed now!
