### ISSUE TITLE
Child, mentor and parent accounts to be backfilled and updated in Salesforce

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#489]
As per  doc https://docs.google.com/document/d/15sWS97XHHg2B-RP_WGqFN6FInCEASSETbmUusR1sl0w/edit#heading=h.jb4hl1z3s4ph

Child accounts are to be put into Salesforce as well as parent and mentor accounts.
Child accounts will be linked to parent accounts using partner account links.

**Comment by Wardormeur** [comment]
Nope. :)
