### ISSUE TITLE
Parent not in the list of members in 'manage dojo users'

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#502]
Profile: http://zentest.coderdojo.com/dashboard/profile/c13f3b3d-cc24-43b9-bd9f-2b89618d1788

joined the account into Enniscorthy TEST dojo earlier  as a parent and everything worked fine. checked on dojo member's list using another account and the account above is not listed there. in his profile it says he is a member of that dojo and can access the dojo in 'my dojos'. created u13 on that account too and it didn't get added into the dojo too.

**Comment by ckiss** [comment]
@kennanseno @tangentfairy I joined this dojo with all this accounts and I can see all the users there in manage users page. Did I miss something? 
<img width="1239" alt="screen shot 2015-09-21 at 2 20 00 pm" src="https://cloud.githubusercontent.com/assets/1004239/9990692/e089897c-606b-11e5-9f89-8bfef9b66ff2.png">

**Comment by kennanseno** [comment]
did they all show up instantly after joining @ckiss ?

**Comment by ckiss** [comment]
@kennanseno yes they did. Can you still reproduce this?

**Comment by kennanseno** [comment]
@ckiss i'll try to reproduce later and will let you know.

**Comment by kennanseno** [comment]
@ckiss seems to be working fine now. close this for now until we receive another report from the community having this problem?

**Comment by ckiss** [comment]
thanks @kennanseno
