### ISSUE TITLE
Global nav not same style as main site

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#508]
Comparing them side by side and they don't look the same!

![screen shot 2015-08-25 at 10 12 00](https://cloud.githubusercontent.com/assets/1136491/9463042/c9bef2e6-4b11-11e5-9ec9-86f0a7bf4774.png)

**Comment by tangentfairy** [comment]
__Technical spec__
Needs to be at least styled the same (the spacing is not right).
CSS is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/css/dashboard.less 

And we need to update the link to be "COOLESTPROJECTS2016". That is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/common/components/cdgm-buttons-left.dust

**Comment by kennanseno** [comment]
working on this now @tangentfairy .

**Comment by tangentfairy** [comment]
It seems like the menu items on the right are now off a little bit on this branch:

![screen shot 2015-11-27 at 10 06 18](https://cloud.githubusercontent.com/assets/1136491/11438710/9621511e-94ee-11e5-84ed-ff9c87c3767a.png)

**Comment by kennanseno** [comment]
<img width="1510" alt="screen shot 2015-11-27 at 1 17 01 p m" src="https://cloud.githubusercontent.com/assets/7852866/11441988/35adce0a-9509-11e5-9626-ee885b93f7e1.png">

Do you mean the space in the right side of the right menu items?

**Comment by tangentfairy** [comment]
Yep, it seems like they are now off center, not like before :)

**Comment by DanielBrierton** [comment]
This nav has since been replaced with a common header.
