### ISSUE TITLE
dojo application verification popup not centered

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#521]
can we center the popup when waiting for dojo verification as it looks awkward when aligned on the side.

![screen shot 2015-08-26 at 15 16 05](https://cloud.githubusercontent.com/assets/7852866/9495915/bb987ae4-4c05-11e5-8887-8289b6af1869.png)

**Comment by tangentfairy** [comment]
Change this back to a strapline, but make sure that the notices don't clash.

**Comment by Wardormeur** [comment]
Start A Dojo (SAD) has been rewritten last year, closing off.
