### ISSUE TITLE
Encoding broken on Zen listing page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#538]
https://zen.coderdojo.com/dojo/861 Pointed out by German champion

**Comment by tangentfairy** [comment]
I just updated the founder of a Dojo, and the encoding issue came back when I saved it.

The Dojo name was Zambrów and when saved it changed to Zambr&#243;w.

I didn't edit anything else about the listing.

**Comment by tangentfairy** [comment]
The Dojo listing page is okay, it looks like it is just the manage dojos page that is broken.

http://zen.coderdojo.com/dashboard/dojo/pl/zambrow-miejski-osrodek-kultury-ul-wyszynskiego-2a/zambrow

However, in the database I was originally able to do:
`select * from cd_dojos where name='Zambrów'`
And I could see the entry.

After editing the Dojo, I cannot see the Dojo with the above query. I have to run this query instead:
`select * from cd_dojos where name='Zambr&#243;w' `

I wouldn't really expect the HTML entity to be saved into the database. We certainly can't have it both ways (which is seems to be at the moment) because it will make it rather difficult to do regional statistics if I have to search for both the entity and non-entity versions!

**Comment by ckiss** [comment]
fixed. will deploy soon

**Comment by tangentfairy** [comment]
Fixed thank you!

**Comment by tangentfairy** [comment]
I'm sorry but I have found this somewhere else! Go to the Dojo List on this page https://zen.coderdojo.com/dashboard/dojo-list

Under Romania there is a listing with html entities. It looks fine on its own listing page.

**Comment by davey-m** [comment]
fixed.
this was just a data issue not a render issue.

**Comment by tangentfairy** [comment]
Right, I saw a few others like that but once I edited them it worked okay.
