### ISSUE TITLE
resize save button in manage dojo events

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#544]
save button seems to be smaller than the other buttons. can we make it bigger so that it has the same height/width as the cancel button beside it.
<img width="431" alt="screen shot 2015-08-28 at 15 01 24" src="https://cloud.githubusercontent.com/assets/7852866/9548053/15689680-4d96-11e5-9710-e43b3177473e.png">

**Comment by kennanseno** [comment]
fixed already with the new system coming this week according to @tangentfairy .

**Comment by kennanseno** [comment]
@tangentfairy the blue button seems to still have a different size than the green and default buttons.

Find a dojo:
<img width="152" alt="screen shot 2015-10-14 at 8 15 25 p m" src="https://cloud.githubusercontent.com/assets/7852866/10494901/e4908492-72b0-11e5-8f67-e12124d76ae8.png">

Badges:
<img width="120" alt="screen shot 2015-10-14 at 8 15 47 p m" src="https://cloud.githubusercontent.com/assets/7852866/10494919/fa67a0fc-72b0-11e5-8e65-d0b1a9acb720.png">

Create event:
<img width="305" alt="screen shot 2015-10-14 at 8 16 00 p m" src="https://cloud.githubusercontent.com/assets/7852866/10494928/06de3044-72b1-11e5-91b1-6613ac337bae.png">

**Comment by tangentfairy** [comment]
@kennanseno Fixed this, thanks!
