### ISSUE TITLE
Allow input on description field on event same way as Dojo notes field

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#547]
Request from community member to allow HTML notation in the description field for an event.

We already have a nice gui on the notes field when editing a Dojo to do this, so we could reuse the same tool for the events description field.

**Comment by tangentfairy** [comment]
__Technical spec__
The Dojo edit page is using something called ckeditor here: https://github.com/CoderDojo/cp-zen-platform/blob/4674958d8d71c899c4fb199d402b3eb367f02efc/web/public/templates/dojos/dojo-form.dust#L144

We just need to add that to the template here:
https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/events/dojo-event-form.dust#L22

**Comment by ferry-** [comment]
Looked into it https://github.com/CoderDojo/cp-zen-platform/pull/730.
The only issue is that in the event-list view wide images stretch the whole list container. Would a fixed width div with overflow scroll be preferable?

**Comment by tangentfairy** [comment]
I see what you mean by the images. We could add an attribute of `width:100%` to `.event-info-row-content img` to fix this.

[The CSS file is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/css/dashboard.less)

**Comment by ferry-** [comment]
I used max-width instead, so that smaller images won't get stretched.
See the same pull request

**Comment by tangentfairy** [comment]
That has been deployed now, congratulations on your first CoderDojo open source contribution @ferry-! 

Make sure you sign up for http://24pullrequests.com/ - then you can earn badges for contributing to this project :)
