### ISSUE TITLE
make for field in create/edit event form mandatory

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#550]
can we make it mandatory. at the moment it can be left blank.

Form:
![screen shot 2015-08-28 at 16 02 30](https://cloud.githubusercontent.com/assets/7852866/9550986/5c891156-4da6-11e5-9eb4-a03386a8f8b5.png)

Event Tab:
![screen shot 2015-08-28 at 15 59 35](https://cloud.githubusercontent.com/assets/7852866/9550966/43df3040-4da6-11e5-9ff6-14430de4bad8.png)

<img width="1088" alt="screen shot 2015-08-28 at 16 57 17" src="https://cloud.githubusercontent.com/assets/7852866/9550947/35f9597e-4da6-11e5-94e4-2b8a0af7b435.png">

**Comment by tangentfairy** [comment]
Was removed in the new events section so this can be closed.
