### ISSUE TITLE
Dojo even time is incorrect on invite email

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#551]
Cork dojo came across this - the event is actually set for 18:15 but the ticket approval email is an hour behind?

![screen shot 2015-08-29 at 18 15 32](https://cloud.githubusercontent.com/assets/1136491/9563389/1fe8f53e-4e7a-11e5-8006-b966142c8dbc.png)

**Comment by ckiss** [comment]
fixed
