### ISSUE TITLE
Microservice timeouts

### ISSUE THREAD

**Issue by david-cahill** [CoderDojo/community-platform#556]
`
{"0":"2015-08-31T09:26:48.407Z","1":"af8hqwn75l5x/1441013034192/11226/-","2":"error","3":"act","4":"dojos       ","5":"OUT","7":"cmd:dojos_list,role:chairo-cache","8":11114,"9":"{cmd:dojos_list,role:chairo-cache,query:{mysqlDojoId:54}}","10":"ENTRY","11":"(byz2k)","12":"-","13":"seneca: Action cmd:dojos_list,role:chairo-cache failed: [TIMEOUT].","14":"act_execute","15":"{id:ojs2ebi1dw59/tjfs75ipgolh,gate:false,ungate:false,desc:cmd:dojos_list,role:chairo-cache,plugin:{name:dojos,","16":"Error: [TIMEOUT]\n    at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:338:23)\n    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:429:66)\n    at wrapped [as _onTimeout] (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)"}
{"0":"2015-08-31T09:26:48.411Z","1":"af8hqwn75l5x/1441013034192/11226/-","2":"error","3":"act","4":"dojos       ","5":"OUT","7":"cmd:list,role:dojos","8":11118,"9":"{cmd:list,role:dojos,query:{mysqlDojoId:54}}","10":"ENTRY","11":"(dwsyu)","12":"-","13":"seneca: Action cmd:list,role:dojos failed: [TIMEOUT].","14":"act_execute","15":"{id:1bh2gj0g0l8z/i2yknti54yf1,gate:false,ungate:true,desc:cmd:list,role:dojos,plugin:{name:dojos,tag:-},time:{s","16":"Error: [TIMEOUT]\n    at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:338:23)\n    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:429:66)\n    at wrapped [as _onTimeout] (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)"}
{"0":"2015-08-31T09:26:48.415Z","1":"af8hqwn75l5x/1441013034192/11226/-","2":"error","3":"act","4":"remote$       ","5":"OUT","7":"cmd:*,role:cd-dojos","8":11118,"9":"{user:null,zenHostname:zen.coderdojo.com,locality:en_US,cmd:list,role:cd-dojos,query:{mysqlDojoId:54}}","10":"ENTRY","11":"CLIENT","12":"-","13":"seneca: Action cmd:*,role:cd-dojos failed: [TIMEOUT].","14":"act_execute","15":"{id:rgfzklrc4uhd/tb3m9infm4j4,gate:false,ungate:true,desc:cmd:*,role:cd-dojos,plugin:{name:remote$,tag:null},ti","16":"Error: [TIMEOUT]\n    at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:338:23)\n    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:429:66)\n    at wrapped [as _onTimeout] (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)"}
`

**Comment by ckiss** [comment]
@dberesford this can be closed now, right, since there are no more random timeouts?

**Comment by tangentfairy** [comment]
Might be worth checking if https://github.com/CoderDojo/community-platform/issues/670 was due to a timeout error before closing.
