### ISSUE TITLE
Award attendance badges automatically

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#561]
Suggestion from CD Rotterdam to award attendance badges automatically based on number of events user has attended in system.

We also discussed doing this previously.

See Installation of badgekit here https://github.com/CoderDojo/cp-local-development/blob/master/installing-badgekit.md

Full specification to follow.

**Comment by tangentfairy** [comment]
For more information on creating test data, [see this doc](https://github.com/CoderDojo/community-platform/blob/master/creating-test-data.md). The main [readme file is here](https://github.com/CoderDojo/community-platform/blob/master/README.md). 

- The [application attendance for a ticket is updated here](https://github.com/CoderDojo/cp-events-service/blob/cc15412e8e8bd3be4e8b91c69ea03a3f6198bb34/lib/update-application-attendance.js#L7).
- [Example of how the dojos service is called from the events service](https://github.com/CoderDojo/cp-events-service/blob/cc15412e8e8bd3be4e8b91c69ea03a3f6198bb34/lib/user-dojos-events.js). In this case we need to call the badges service from the events service.
- The [badge is added to the profile here](https://github.com/CoderDojo/cp-badges-service/blob/master/lib/add-badge-to-profile.js).

Let me know if you have any questions, usually around on the [Gitter](https://gitter.im/CoderDojo/community-platform?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or tag me in the comments!

**Comment by niccokunzmann** [comment]
It should still be possible to award the badges manually, since not everyone used the platform from the beginning.

**Comment by tangentfairy** [comment]
Yes we will not be removing this functionality, this issue is just to add
extra functionality :)

On Friday, January 29, 2016, Nicco Kunzmann <notifications@github.com>
wrote:

> It should still be possible to award the badges manually, since not
> everyone used the platform from the beginning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/561#issuecomment-176639650>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by Wardormeur** [comment]
This has been done some time ago, should be closed :]
