### ISSUE TITLE
Pre-filling of address on event page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#562]
Complaint from CD Rotterdam that the pre-filing of the address with the Dojo listing address doesn't suit them.

Can we replace this with a tickbox at the top, so you can tick "Use Dojo listing address" and it will pre-fill only if you ask. By default it won't be pre-filled.

**Comment by Arrayindex** [comment]
I'll try and take a peek at this during the week.

**Comment by tangentfairy** [comment]
That'd be amazing thanks @Arrayindex!

**Comment by tangentfairy** [comment]
__Technical spec:__

- The [events template](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/events/dojo-event-form.dust)
- The [edit event controller](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/dojo-event-form-controller.js)
- You'll need to load the details of the Dojo listing also. Take a look at the [existing endpoints in the Dojos service](https://github.com/CoderDojo/cp-dojos-service/blob/master/dojos.js)
Then these details can be loaded form the edit event controller.

**Comment by tangentfairy** [comment]
This is live now, many thanks to @flakyfilibuster !
