### ISSUE TITLE
Add application details to events

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#564]
From CD Rotterdam:

"we are heavy users of the custom questions 
functionality in Eventbrite. This gives us the possibility to loan 
out spare laptops, see which subjects kids ask for to be doing and 
gather other info we might need for a dojo. This is something that 
might actually stop us from using Zen. Hopefully this is something 
that might be added in the future."

I think this would mean adding multiple custom questions.

For now, in the short term, if we can add a field beside where you apply with "Notes/requests". Then the applicant can reply to any questions the ticket admin has in the event description.

**Comment by tangentfairy** [comment]
This has also been requested by CoderDojo Dun Laoghaire

**Comment by josmas** [comment]
Hey @tangentfairy, would something like this work for now? Extra styling can be added too.

![application_notes](https://cloud.githubusercontent.com/assets/194925/11666696/b78f7826-9de5-11e5-8b8c-2d9de3603b07.png)

**Comment by tangentfairy** [comment]
@josmas That looks great! We'll need to show this on the administrator end in the manage events section for the ticketing admins also. Space is tight on that page, so maybe there could be a new column that says "Details" and when you click on the details button it should show a little popup with the notes field.

**Comment by josmas** [comment]
@tangentfairy didn't think of the admin page; will have a look. I'd rather keep the interface consistent, not a huge fan of modals, but I'll see what works best.

**Comment by tangentfairy** [comment]
Sure, I'm open to options. A button with an accordion is another idea!

**Comment by josmas** [comment]
@tangentfairy how do I see the admin counterpart of this? I am logged in as manager, but if I join a dojo (as a guardian) and try to get tickets, I see the same thing... What am I missing?

**Comment by tangentfairy** [comment]
As manager, go to manage Dojos and edit any verified dojo. Make yourself
the founder. Then you'll see manage events under my Dojos, all going well!



On Wednesday, December 9, 2015, Jos <notifications@github.com> wrote:

> @tangentfairy <https://github.com/tangentfairy> how do I see the admin
> counterpart of this? I am logged in as manager, but if I join a dojo (as a
> guardian) and try to get tickets, I see the same thing... What am I missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/564#issuecomment-163313962>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by josmas** [comment]
This is how the events list for managers looks like:
![notes_field](https://cloud.githubusercontent.com/assets/194925/11753202/c7c74fa4-a03b-11e5-8328-11b8c1e8d193.png)

Please review! :)

**Comment by tangentfairy** [comment]
This is live now, thanks @josmas ! :)
