### ISSUE TITLE
Ability to embed Dojo events on external websites

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#566]
Request from CD Rotterdam to be able to embed the Dojo events onto other websites - essentially on Manage Events we'd provide a textarea with some embed code that shows an iframe/similar with the list of upcoming events (would probably limit to upcoming 10 and then a link to CD to see more for the full list).

**Comment by Wardormeur** [comment]
Done on https://github.com/CoderDojo/cp-zen-platform/commit/d1f6402dc589b653dce3bb589cac698aba3b1eed :)
