### ISSUE TITLE
Dojos not being converted in Salesforce

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#576]
Rosa verified this this morning http://zen.coderdojo.com/dashboard/dojo/at/otelo-linz-luftraum-bethlehemstrasse-30-4020-linz/linz-stadt

And it did not turn into an account in Salesforce.

It is still a lead here https://eu2.salesforce.com/00Qb000000HtynO

**Comment by daveymoran-nearform** [comment]
updates to champion profiles are now saved in salesforce. will update labels when fix is deployed.

**Comment by tangentfairy** [comment]
Will we need to manually go through and convert any Dojos that were not converted since now? This http://zen.coderdojo.com/dashboard/dojo/uz/tashkent/uzb-coder was verified this morning but is not in Salesforce (not even as a Lead).

**Comment by daveymoran-nearform** [comment]
the last comment is most likely related to issue #641 where the convert script was not being run because the wrong platform id has associated with the lead.

**Comment by tangentfairy** [comment]
I'm not sure if this is related, but the notes field on the Dojo does not update:

https://eu2.salesforce.com/001b00000143ZiVAAU/d?retURL=https%3A%2F%2Fnpe01.eu2.visual.force.com%2Fapex%2FaccountViewOverride%3Fid%3D001b00000143ZiV%26sfdc.override%3D1&nooverride=1

I updated it a couple of times to add/remove characters but it did not update, it does not match the listing: https://zen.coderdojo.com/dashboard/dojo/ie/dublin/dublin/dublin-docklands-chq

The website field does not seem to update either.
