### ISSUE TITLE
Dojo marked as deleted but still viewable in My Dojos

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#579]
This Dojo was marked as deleted, and we can still see it in the Manage Dojos list (correct, CDF admins are allowed to see them).

But when the champion of the Dojo logs in they can still see the Dojo. It is not supposed to be viewable to anyone but CDF admins when marked as deleted.

Happening for St. Joseph's

**Comment by daveymoran-nearform** [comment]
after plenty of testing on my local dev environment, i have updated the cd_usersdojos table with the following sql statement:
update cd_usersdojos 
set deleted=1,deleted_by=d.deleted_by,deleted_at=d.deleted_at 
from cd_dojos as d 
where d.id=cd_usersdojos.dojo_id and d.deleted=1 and cd_usersdojos.deleted=0

590 dojos out of 1809 were updated.

**Comment by tangentfairy** [comment]
Sounds good, thanks @daveymoran-nearform
