### ISSUE TITLE
Country dropdown list covering up date picker during profile setup

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#581]
the country field seems to cover up the date picker when both are clicked. clicking one should hide the other field/s.

<img width="877" alt="screen shot 2015-09-02 at 09 53 31" src="https://cloud.githubusercontent.com/assets/7852866/9626965/fa81bb64-5158-11e5-98ca-22f2833615c3.png">

**Comment by tangentfairy** [comment]
__Technical spec:__

- The (CSS file)[https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/css/dashboard.less]
- Datepicker on champion registration [is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/start-dojo-wizard/step-two-champion-registration.dust#L38). To get to this page, go to "start a dojo". After registering it is the next page (champion registration form). This form is for new users who want to start a dojo
- There's another Datepicker on the (profile page here)[https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/profiles/general-info.dust#L24]. To get to this page, register as a user and click on your name, then go to "edit profile".

**Comment by DanielBrierton** [comment]
This no longer occurs, so I'm closing the issue.
