### ISSUE TITLE
Can still apply for an event even though i'm already approved/confirmed

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#599]
So i've already applied to the event and was approved by the dojo champion, yet when I apply again and I still get the pop up below(the dojo didn't receive an event application email for this so it's all good on that end).
 
![screen shot 2015-09-09 at 10 43 59](https://cloud.githubusercontent.com/assets/7852866/9758734/5a84ebda-56e0-11e5-8ad4-599efbe1c330.png)

**Comment by tangentfairy** [comment]
Was fixed by Davey in another issue.
