### ISSUE TITLE
Privacy statement page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#60]
In addition to the cookie banner, we'll need a page listing all of the cookies we'll be using on the site, as per regulations. 

We can fit this in as part of the privacy statement Rosa is drafting

Will assign myself this one for now.

**Comment by gisellegk** [comment]
Hi! I'm participating in [24 Pull Requests](http://24pullrequests.com/) and I started a day late! This will be my first time contributing to something open source...

How can I help with this issue? I'm not sure what file I should be looking at....

**Comment by tangentfairy** [comment]
Hi @gisellegk - thanks for offering to help out! The [readme](https://github.com/CoderDojo/community-platform) has some information about the project and how to get set up with local development. You'll only need to put in a request to the [frontend repository](https://github.com/CoderDojo/cp-zen-platform) for this task.

The link to the page [could go in the footer here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/common/footer.dust) and [the way the charter page is set up](https://github.com/CoderDojo/cp-zen-platform/search?utf8=%E2%9C%93&q=charter) would be a good example ([the charter itself is here](http://zen.coderdojo.com/dashboard/charter)).

All text needs to be [added to the translations file](https://github.com/CoderDojo/cp-zen-platform/blob/0b18f94af024d51ce9055dbc02ee89b1a520b08f/web/locale/en_US/messages.po#L483), and [in the templates](https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/charter/charter-info.dust#L2) we use an i18n plugin.

The privacy statement itself is in a [public Google Document here](https://docs.google.com/document/d/17Y-YSxEH8oZo0SWDc1eejY11reAkIYyahDjNpvgKX_k/edit) - and I am presently adding the cookies list to it. The most tedious part of this will be using a different i18n key for each section, as we ideally don't want HTML elements getting into the messages.po file.

Let me know if you have any questions - and if you want to join the Slack :) - I'm on the 24 Pull Requests gitter.im also!

**Comment by gisellegk** [comment]
@tangentfairy I'm on it! Thanks!

**Comment by gisellegk** [comment]
So I had an issue installing the node packages because of my school's internet filter :( 

I won't make it for today's 24 pull request but now that I'm home and am all set up I'll try for tomorrow!

**Comment by tangentfairy** [comment]
Cool! Mail me at ursula@coderdojo.org if you have any problems - would be interested to hear what was blocked by the internet filter also.

**Comment by gisellegk** [comment]
It was whatever Phantom.js' package is hosted on... kept timing out and I tried to download it manually and it came up as the filter page. `npm install`-ing worked perfectly on unfiltered home wifi though :)

**Comment by tangentfairy** [comment]
Great! :)

**Comment by gisellegk** [comment]
So when I run
`./start.sh development ./service.js`
 I get this error message:
```
config file not found: development
Usage: ./start.sh <config> <startscript> [startscript_opts]...
```
So when I run
`./start.sh development ./service.js`
 I get this error message:
```
config file not found: development
Usage: ./start.sh <config> <startscript> [startscript_opts]...
```
There also is no `scripts/insert-test-users.js` to run....
Am I missing a step somewhere..?  Also should I be emailing these kind of questions to you, or commenting here?

**Comment by tangentfairy** [comment]
You don't need to run this - make sure you are following the instructions in this repository: https://github.com/CoderDojo/cp-local-development Once you have installed the perquisites you will be able to run the `init` and `run` commands.

The cp-zen-platform repo is just the front end part of the system. I'm going to update the readmes of the other repositories to point to cp-local-development now to avoid any further confusion - I can understand why this happened! :)

**Comment by gisellegk** [comment]
@tangentfairy Took a break from working on this but I'm back.

Still stuck on setting up everything...

It keeps telling me `createuser: could not connect to database postgres: FATAL:  role "giselle" does not exist` Am I in the wrong directory?

**Comment by josmas** [comment]
Hi @gisellegk It looks like you are trying to connect to the DB directly with your user. Have you created a 'platform' user as explained [here](https://github.com/CoderDojo/cp-local-development#install-tools)?

If you can provide a step by step description of what you've done so far for the local install, we might be able to help out.

**Comment by gisellegk** [comment]
@josmas so I already have node, git, and grunt installed. I then installed PostgreSQL (sudo apt-get install postgresql) and pgAdminIII (sudo apt-get install pgadmin3).

Then, I ran `createuser -P -s -e platform` and it prompts me for the password twice, which I type, then it gives me the error I mentioned above. 

I'm in the cp-zen-platform directory for all of this btw. It didn't mention having to clone any particular directory for this until the Code Setup section so I guessed that it didn't matter.

**Comment by josmas** [comment]
Hi @gisellegk thanks for that. Try creating the new user with the ***postgres*** admin user, like:
`createuser -U postgres -P -s -e platform`

before that can work, make sure that you can use the ***postgres*** user. The [trust](http://www.postgresql.org/docs/9.2/static/auth-pg-hba-conf.html) method for the admin user may be good enough if you are running this only locally. If you want to play safer, then you can add a password to it.

You are correct guessing that so far it does not matter which particular directory you do this from (so far it's just a postgresql issue).

**Comment by niccokunzmann** [comment]
Hi @gisellegk if you like to try it out: I created automated installation methods at [cp-docker-development](https://github.com/niccokunzmann/cp-docker-development). There are scripts to install it under Ubuntu, to use docker and just to use a VM. If you like to try it out, please report/change any thing you like. Maybe you want to look at the differences you have to the ubuntu.sh installation. I would be happy if you use it. It was created to fast setup the cp-local-development repository.

**Comment by gisellegk** [comment]
@niccokunzmann I tried your script file... It keeps getting stuck on this: 

Remove the following npm installations:
/usr/local/bin/npm
done?

I tried deleting that file (and now it's gone) but it's still giving me the same message so I'm not sure what to do...

**Comment by niccokunzmann** [comment]
I think you can uninstall this with `sudo apt-get remove` OR you edit the script and remove the installation of npm. Maybe you just type ENTER and it runs further.

**Comment by gisellegk** [comment]
I just edited the script... looks like I am on my way. Thanks so much!

**Comment by niccokunzmann** [comment]
Please let me know what you edited, maybe upload it or give it to me, so I can improve the existing script.

**Comment by gisellegk** [comment]
@niccokunzmann I just deleted the node installation part, so not a super useful edit.... I'm not good with shell scripts, so I don't know how to do it myself, but maybe giving the option to skip over instead of only asking to delete the previous installation would be helpful?

**Comment by niccokunzmann** [comment]
@gisellegk Is it running on your platform?

**Comment by gisellegk** [comment]
@niccokunzmann yes, it does! A couple days ago it randomly stopped working but I think it was an unrelated issue... but now it's working fine.

Also, a couple of general questions: ( @tangentfairy ?)

1. Does this page need to have the user confirmation stuff like the Charter? right now I based it off of the Terms and Conditions page -- text only...

2. Where is a good place to put css to style the cookies table?

**Comment by tangentfairy** [comment]
@gisellegk 
1. Text only is fine for now!
2. [The main css file is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/css/dashboard.less). I think there's a `table-striped` class in bootstrap that makes tables look quite good! It is used in the events section somewhere.

Let me know if you need anything else, and thanks for taking this on!

**Comment by gisellegk** [comment]
I just put in the pull request. Thank you all for being so patient and supportive of me!

**Comment by tangentfairy** [comment]
This is live now, thanks so much @gisellegk! If you'd like to join the CoderDojo Foundation Slack channel for development chat, send me a mail on ursula@coderdojo.org

I've invited you to become a member of this organization now too :)

**Comment by niccokunzmann** [comment]
Where did you get this text from? Are there existing translations?

**Comment by niccokunzmann** [comment]
Are there existing translations of the text one could refer to during translation?

**Comment by tangentfairy** [comment]
@niccokunzmann - The [Google doc with the text is here](https://docs.google.com/document/d/17Y-YSxEH8oZo0SWDc1eejY11reAkIYyahDjNpvgKX_k/edit). It is available for translation in CrowdIn now that this issue has been closed!
