### ISSUE TITLE
Wording on parent/guardian invite 

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#607]
I clicked an invite to become a parent/guardian when not logged in and the popup said I must have the parent/guardian user type (I was only a champion).

Can we have some further explanation here - i.e. "Please contact your Dojo administrator to become a parent."

Also, if you are not logged in, a different message needs to appear - "You must be logged in to accept an invite"

**Comment by tangentfairy** [comment]
__Technical spec__
Start by looking here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/js/controllers/accept-dojo-user-invitation-controller.js

**Comment by rosalanghammer** [comment]
First part is no longer relevant so can be closing as blocking usertype doesn't exist since change to registration. Assigning myself a task to review all error messages and make them user-friendly.
