### ISSUE TITLE
saving a profile update immediately after registering a new users seems slow - insert a spinner to give user feedback of operation in progress

### ISSUE THREAD

**Issue by davey-m** [CoderDojo/community-platform#609]

**Comment by kennanseno** [comment]
this seems to update fast enough that it doesn't require a spinner on my end. @tangentfairy thoughts?

**Comment by tangentfairy** [comment]
Have you tried uploading a large image?

**Comment by kennanseno** [comment]
oh wait. I thought it's the profile fields. yea, it does take a bit of time.

**Comment by tangentfairy** [comment]
This hasn't arisen since, so I'm going to close off this one.
