### ISSUE TITLE
Update wording on emails

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#614]
As per doc:
- Email sent when a user forgets their password.
- Email sent when a user invites another user to the platform.
- Email sent to confirm a ticket request has been received. 
- Email sent to confirm a ticket has been approved by champion
- Email sent to confirm a ticket has been cancelled
- Email sent to parent when they are invited to become a parent of a ninja
- In the case that there is a parent of a child who has already signed up and has a profile - the parent can invite that child to link up with their account
- Email sent to user when they are asked to accept a badge
- Email sent to champion when user leaves Dojo
- Email sent to champion when user requests to join a Dojo

**Comment by tangentfairy** [comment]
__Technical spec__
Doc is here https://docs.google.com/document/d/1OBw9mfUPhlbAsMOnwHL09WkaFnJtqF0f9Xz6VV7S2L0/edit

It needs to be compared with the templates in these two places
https://github.com/CoderDojo/cp-users-service/tree/master/email-templates
https://github.com/CoderDojo/cp-dojos-service/tree/master/email-templates

For further clarification ask me.

**Comment by kennanseno** [comment]
@tangentfairy doc permission needs to be changed. can't open the google doc link.

**Comment by tangentfairy** [comment]
I will give access to whoever wants to assign themselves the issue

**Comment by kennanseno** [comment]
@tangentfairy requested access. will be updating email templates that doesn't require me to create a new ejs variable as i've no clue how to create one.

**Comment by kennanseno** [comment]
<ul>
<li>Email sent when a user forgets their password.<b>[DONE]</b></li>
<li>Email sent when a user invites another user to the platform.</li>
<li>Email sent to confirm a ticket has been approved by champion</li>
<li>Email sent to confirm a ticket has been cancelled</li>
<li>Email sent to parent when they are invited to become a parent of a ninja
In the case that there is a parent of a child who has already signed up and has a profile - the parent can <b>[DONE]</b></li>
<li>invite that child to link up with their account<b>[DONE]</b></li>
<li>Email sent to user when they are asked to accept a badge<b>[DONE]</b></li>
<li>Email sent to champion when user leaves Dojo<b>[DONE]</b></li>
<li>Email sent to champion when user requests to join a Dojo<b>[DONE]</b></li>
</ul>

**Comment by Wardormeur** [comment]
@rosalanghammer To review

**Comment by rosalanghammer** [comment]
@Wardormeur We can close as a re-review has been done as features are built - I will do another full review of all in April with Community team. Are cp-users and cp-dojos the only places where email templates are stored?

**Comment by Wardormeur** [comment]
They are stored together in crowdin, but imported/used (emails wise) by both dojos & users, yes.
