### ISSUE TITLE
List of applicants to event do not match Dojo members

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#617]
You have to be a member of a Dojo to join an event. There are users in the events attendance that are not in the manage users section for the Cork Dojo.

I checked the db and it looks like they are a member of the Dojo, so it might be a pagination issue on the Manage Users page but I couldn't be sure.

user id e18bfdc4-c909-462b-bf3e-c9de5cbd052e

**Comment by daveymoran-nearform** [comment]
fixed.
