### ISSUE TITLE
Show 'total number of dojos' somewhere on home page

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#621]
Adding them all up on the map is getting to be too much of a challenge, would be nice to see at a glance how many dojos there are around the world.

**Comment by howardjing** [comment]
I can take a look at this -- it looks like the map already has a count of dojos grouped by location:

![image](https://cloud.githubusercontent.com/assets/831651/26014079/295916f0-3729-11e7-9c48-56c6cfcf1311.png)

Is the goal to get the global count of dojos regardless of location on the home page as well?

**Comment by Wardormeur** [comment]
Hey @howardjing Yes, the idea would be to have a directive displaying a counter of dojo.
I know we already have a counter used on poll (look for poll-counter) but you may be able to do something fancier :)

**Comment by howardjing** [comment]
I wasn't able to get to this this weekend. I might be able to try again next weekend, but no guarantees. I'd imagine a solution would involve creating a dojo counter in cp-dojos-service, but a front end only solution might involve computing the count from the result of the by-country endpoint:

```
_.values(dojos).reduce((sum, list) => sum + list.length, 0)
```

I've noticed that the by-country endpoint takes several seconds to load, so this solution isn't great.  Not sure if there's a more relevant endpoint.

**Comment by Wardormeur** [comment]
The map "tab" loads api/2.0/dojos which returns the list of dojos that are then displayed on the map.
Either reusing this result.length or making a separate endpoint to just return the count in pure SQL would be a better idea (I think) :)
