### ISSUE TITLE
Verified Dojo missing from new database

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#626]
This Dojo is missing:

`Brecht @ de bib Brecht`

It is not in the new db. It is owned by the same user as this Dojo: http://zen.coderdojo.com/dashboard/dojo/be/kerklei-2-brecht/dojo-brecht

Was there an issue with the migration where one user owned more than one Dojo?

**Comment by daveymoran-nearform** [comment]
@tangentfairy can u please email me a mysql dump of the two dojos in question (and the owner details of the second dojo if they are not already in production db), thanks :)

**Comment by daveymoran-nearform** [comment]
then these details resurface the migration scripts in the community platform repo can be altered and used to perform the import.

**Comment by tangentfairy** [comment]
I mailed on the Imagineware one - the Belgian one was since recreated.
