### ISSUE TITLE
User cannot edit profile if image is too large

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#633]
Rosa got an error every time she tried to save her profile. She got the entity too large error.

I discovered that once I resized and reuploaded her profile picture it worked.

The odd thing is that she did somehow manage to upload the original image, but every time you go to resave the profile it sends the image again, and somehow subsequent edits causes the error.

The original image dimensions were 3200 x 2133.

We probably won't ever need an image that large, so could we limit it to something like 1200 (width or height) and show a friendly error message rather than the plain "there was an error saving profile" error?

If it is larger in dimensions than this can just say "Your profile image is too large. Please resize to a maximum of 1200px x 1200px"

**Comment by ckiss** [comment]
fixes in https://github.com/CoderDojo/cp-zen-platform/pull/657.
