### ISSUE TITLE
Retain aspect ratio of supporters images on Dojo listing

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#634]
The image on this listing is very stretched
http://zen.coderdojo.com/dashboard/dojo/au/211-church-street-parramatta-nsw-2150/north-parramatta-nsw-progalore

Update the CSS to remove the height and have a max-width of 570px instead

**Comment by kennanseno** [comment]
fixed.

**Comment by rosalanghammer** [comment]
Another case of strange sponsor logo sizing - https://zen.coderdojo.com/dashboard/dojo/pl/warszawa/warszawa-allegro

**Comment by tangentfairy** [comment]
It looks like the class `dojoSupporterImage` has gone missing on the image tag

**Comment by kennanseno** [comment]
@tangentfairy this image is not in the dojo sponsor section but was added in the dojo notes section.

**Comment by kennanseno** [comment]
just checked. it isn't a bug, when you add an image in the notes section, it uses the default image size. A dojo admin has to manually change it to his desired size. An email to the dojo to edit the size of the image will suffice on this. @tangentfairy  @rosalanghammer 

<img width="1193" alt="screen shot 2015-12-03 at 6 38 44 p m" src="https://cloud.githubusercontent.com/assets/7852866/11570069/2209ee0e-99ed-11e5-8c34-e08a5c22c4be.png">

**Comment by tangentfairy** [comment]
We can put the same fix in here that we did for the events notes section, which Jonathan did here: https://github.com/CoderDojo/community-platform/issues/547

**Comment by tangentfairy** [comment]
Fixed and deployed now
