### ISSUE TITLE
Add popup on registration page to explain user types

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#648]
Parents keep registering themselves or their kids as champions.

Put an info icon to the right of the "user type" dropdown explaining how to pick which profile you want.

@rosalanghammer to provide text.

**Comment by rosalanghammer** [comment]
Champion - A CoderDojo Champion is an individual who spearheads setting up and maintaining a Dojo. Champions do not necessarily have to have the ability to code but possess the skills required to bring together technical mentors and supporters to run a Dojo frequently!

**Comment by rosalanghammer** [comment]
Mentor/Volunteer - these volunteers power their local Dojos with their technical and organisational skills and inspire the next generation of coders, entrepreneurs and innovators!

**Comment by rosalanghammer** [comment]
Ninja Over 13 - A Ninja is a young person who attends their local Dojo! Only Ninjas over 13 can have their own account, Ninjas under 13 must register under their Parent/Guardians account.

**Comment by rosalanghammer** [comment]
Parent/Guardian - Parents/kids are super important in CoderDojo as they encourage and inspire CoderDojo Ninjas on a daily basis! Parents can sign up on the platform to register their kids (both aged under 13 and over 13) for their Local Dojos events and so their kids can earn badges for their profile!
