### ISSUE TITLE
User completed application process for Dojo without signing charter

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#655]
See this application id 7e74bbbd-ce7d-4b3f-8fdf-19a444aa9778

Somehow the champion of this unverified Dojo https://zen.coderdojo.com/dashboard/dojo/us/gulf-breeze-fl/gulf-breeze-fl-woodlawn-beach-middle-school

Has gone through the application process but is appearing in manage dojos as not having signed the charter. 

This is blocking the administration staff from verifying Dojos.

**Comment by ckiss** [comment]
I couldn't reproduce this issue and seems to be an one-off type of bugs which might have been caused by the timeouts. I'll park it for now and I'll keep an eye on it. Found few small other issue when testing this. I'll link the PR's to this ticket.
