### ISSUE TITLE
'when' field on sys_user table not in sync with old database

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#661]
Most of the 'when' field values on the sys_user table are set to the 26th of August. 

This makes it very difficult for me to see how many users actually signed up in 2015, and see how our user base is growing.

It means at the moment I have to do stats on both the old and new databases. 

Would be useful to get the when field backfilled according to the old database, so we lose the huge number of records with the 26th of August on them (which is meaningless).

**Comment by DanielBrierton** [comment]
@rosalanghammer Do we really care about this anymore..?

**Comment by rosalanghammer** [comment]
No closing!
