### ISSUE TITLE
Malahide Dojo not searchable on homepage

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#664]
You can search this on zen.coderdojo.com but the link on the homepage gives you a 404

**Comment by daveymoran-nearform** [comment]
searching for malahide on homepage produced one result which linked to http://zen.coderdojo.com/dashboard/dojo/ie/st-sylvesters-parish-centre-main-st-malahide/malahide
which is now viewable.

**Comment by tangentfairy** [comment]
Closing until we can reproduce again...
