### ISSUE TITLE
Ability to copy a past event into a new event

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#665]
Add a dropdown on the create event page button that says "copy previous event" - when selected, a dropdown appears with a list of event names and dates.

![screen shot 2016-01-14 at 14 05 42](https://cloud.githubusercontent.com/assets/1136491/12326419/9b6f12e6-bac8-11e5-9d77-c266d987d0b4.png)

- Use the [search events endpoint](https://github.com/CoderDojo/cp-events-service/blob/master/lib/search-events.js)
- Event creation [form is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/events/dojo-event-form.dust). Make sure only to put this feature in creation mode.

**Comment by tangentfairy** [comment]
Related to https://github.com/CoderDojo/community-platform/issues/562

**Comment by Wardormeur** [comment]
Deployed !
