### ISSUE TITLE
cp-local-dev needs to clone all repos before doing npm installs

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#666]
The script bails if the workspace dir already exists, so if it can clone the repo before trying to do an npm install that will cause less hassle.

**Comment by BahuMan** [comment]
+1

**Comment by dberesford** [comment]
@BahuMan just fyi, this is how far we got with windows support previously: #165

**Comment by Wardormeur** [comment]
Closing, we now use docker instead
