### ISSUE TITLE
Salesforce - city field needs to be made bigger

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#668]
```
Details: { id: 'km4mpaw85459/478fxu96frxh',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'TOO' },
  time: { start: 1442673589752, end: 1442673591812 },
  'orig$':
   { name: 'STRING_TOO_LONG',
     errorCode: 'STRING_TOO_LONG',
     fields: [ 'City' ] },
  'message$': 'City: data value too large: Francavilla Fontana, Province of Brindisi (max length=40)',
  message: 'City: data value too large: Francavilla Fontana, Province of Brindisi (max length=40)',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.6.4/txa4vlknc2jq/1442503108701/8673/-' }
```

**Comment by dberesford** [comment]
also billing city field:

```
Details: { id: '1jgp5jtn8jxv/ond7p658kipj',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'ARQ' },
  time: { start: 1442671237571, end: 1442671239609 },
  'orig$':
   { name: 'STRING_TOO_LONG',
     errorCode: 'STRING_TOO_LONG',
     fields: [ 'BillingCity' ] },
  'message$': 'Billing City: data value too large: Francavilla Fontana, Province of Brindisi (max length=40)',
  message: 'Billing City: data value too large: Francavilla Fontana, Province of Brindisi (max length=40)',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.6.4/ef81qfbqnaoe/1442503093293/11392/-' }

Stack:
    at Object.handle_response (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by tangentfairy** [comment]
It's not possible to make this bigger on the Salesforce side: https://success.salesforce.com/answers?id=90630000000gnrvAAA

The only solution is to make a custom city field. The downside of this is that we wouldn't be using the default Billing City field, which I have a feeling is better to use as it will produce better statistics using the native Salesforce tools.

https://developer.salesforce.com/forums/?id=906F00000008ih6IAA

What we could do is append the long city to the Street address and truncate the city field so that we take the part before the comma (seeing as the second part is the province anyway) before passing it to Salesforce.

Thoughts?

**Comment by tangentfairy** [comment]
CC @daveymoran-nearform who might have further thoughts...

**Comment by daveymoran-nearform** [comment]
after a bit of research ...
**we cannot:**
-edit any of the address fields,
-create a custom field of type location with with custom fields/lengths,
**we can:** 
-create all new fields for city field or each field in the original address data type, [not ideal for both saving and displaying]
-as ursula mentioned above append/truncate, [not ideal as we are relying on users input to dictate how we split the address/city values]
-add another input filed to take in "state" value, [atm im unsure of how this extra field will work with platforms current state and google maps api]
-put in front end validation to limit input characters to 40, [potentially a little bit limiting to the end user]

fyi, salesforce strongly recommend using the address field exactly as defined with no editing or workarounds.

my own thoughts on it are to set the front end validation to limit to 40 chars as the city value in question ia an outlier case and even at that is only 41 characters long. the city in question is actually a city and state combined so adding a state input field may be beneficial but it may cause quiet a few regression issues with previously implemented/tested functionality. for me, i think we should set the front end validation and reevaluate later on down the line if enough users have similar issues with inputting their address.

any thoughts @tangentfairy

**Comment by tangentfairy** [comment]
I agree that we need to try and go with Salesforce' recommendations that we need to use the address field exactly as is.

I don't want to lose any information though - I'd prefer if we can add a state input or some other field for a province. And make sure we keep the city stored in some way!

**Comment by tangentfairy** [comment]
Mitigated this for the moment by putting front end validation in.
