### ISSUE TITLE
Verified Dojo giving 404 page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#672]
Annabel just verified this Dojo http://zen.coderdojo.com/dashboard/dojo/ie/midleton%2Fmidleton but it is giving a 404. If you search for the Dojo name "Midleton" you'll see it in manage dojos.

Dojo id is 7a6cec25-6c41-4541-9736-7ee8f15c47bb

**Comment by ckiss** [comment]
@tangentfairy for some reason this dojo had saved in the DB dz/midleton/midleton instead of ie/midleton/midleton in the slug field. I changed that straight in the DB, to make it work, but I have to investigate further to see what caused this.

**Comment by tangentfairy** [comment]
Great thanks @ckiss
