### ISSUE TITLE
Install Google Tag Manager

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#674]
@petecoderdojo needs Google Tag Manager installed on Zen asap

**Comment by petecoderdojo** [comment]
Code below:


<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-P3CNG3"
height="0" width="0"
style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)
<http://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f)>
;
})(window,document,'script','dataLayer','GTM-P3CNG3');</script>


On 22 September 2015 at 09:47, Ursula Clarke Everett <
notifications@github.com> wrote:

> @petecoderdojo <https://github.com/petecoderdojo> needs Google Tag
> Manager installed on Zen asap
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/674>.
>



-- 
Pete O'Shea

Communications and Events @ the CoderDojo Foundation <http://coderdojo.com/>
PH: +353876965019 | Skype: peter__oshea
Twitter: @*p*eter0shea <https://twitter.com/peter0shea> @CoderDojo
<http://coderdojo.com/>

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>
   - Book a ticket for DojoCon 2015 in Derry, Ireland 
   <http://dojocon.coderdojo.com/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by tangentfairy** [comment]
Installed
