### ISSUE TITLE
Docklands Dojo not searchable on map

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#679]
I searched for "Docklands" and "CHQ" but I can't find it.

![screen shot 2015-09-22 at 11 32 44](https://cloud.githubusercontent.com/assets/1136491/10016289/ba254d04-611d-11e5-875f-730cce023954.png)

When I zoom in to the location also I cannot find it - I just get a cluster of "2" and when I click on "2" nothing happens:

![screen shot 2015-09-22 at 11 34 20](https://cloud.githubusercontent.com/assets/1136491/10016316/f1b814f4-611d-11e5-9b01-478d2f4cc7f9.png)

Dojo listing is here: http://zen.coderdojo.com/dashboard/dojo/ie/the-chq-building-ifsc-dublin-docklands-dublin-1-ireland/dublin-docklands-chq

Are we indexing the "name" field for the map search? If not I think we need to be.

**Comment by ckiss** [comment]
@tangentfairy we are not searching by name when doing searches on the map. We only search for locations. I think I can make the search to look into the name field too. About the pin, I don't have a solution for that yet. It might be because there are two dojos in the exact same location, cause it seems to work in other places where we have a cluster of 2. I'll look into this.

**Comment by tangentfairy** [comment]
There's a test Docklands Dojo, I am going to mark it deleted.

Yes, it would be great to make it search by name field also as that is usually more specific!

**Comment by tangentfairy** [comment]
Oddly enough the test docklands Dojo is already marked deleted, but it still shows up on the map.

**Comment by ckiss** [comment]
@tangentfairy I discovered it's not from DocklandsTest that we get two dojos in same place. "Crumlin, Dublin @ Loreto Crumlin Girls School" seems to be held in the exact same location. I'll see if it's possible to split that cluster into two, but it will be difficult to user to select one or another even if I put two distinct pins, cause the map will put them in the same place.

**Comment by tangentfairy** [comment]
Well Crumlin is nowhere near the Docklands so I'd say if we can edit the coordinates to 53.3290806,-6.2975074 for Crumlin in the db then that will sort the issue. And very unlikely for two Dojos to have the exact same coordinates.

**Comment by ckiss** [comment]
fixed & deployed

**Comment by tangentfairy** [comment]
Cristian is looking into making sure that when you search "Docklands" for example, the map will not zoom to Australia.

**Comment by ckiss** [comment]
fixed this. It just needs to be deployed :)

**Comment by tangentfairy** [comment]
Fixed, thanks @ckiss

**Comment by tangentfairy** [comment]
Reopening, found another instance of this that I'm looking into now (two Dojos on the map that seem to be at the same location!).

**Comment by tangentfairy** [comment]
Fixed now
