### ISSUE TITLE
Social URLs aren't correct in preview

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#680]
The URLs on the profile for LinkedIn and Twitter are okay now, except for when you are in edit mode - the preview to the left of the page is still incorrect. See bottom left preview of URL in this screenshot.

Pointed out by community member.

![screen shot 2015-09-22 at 11 45 50](https://cloud.githubusercontent.com/assets/1136491/10016515/8004f1f4-611f-11e5-8093-e8a26bd8e900.png)

**Comment by daveymoran-nearform** [comment]
i cannot reproduce this issue. there is only one entry in the db that starts with http and that is not the url above. the profile takes the twitter handle from the db and prepends "https://" to it so im not sure how the extra http is being displayed. from the url above the second http is not correct syntax, it is "http//" instead of "http://" and there in no occurrences of "http//" in the codebase.

**Comment by daveymoran-nearform** [comment]
@tangentfairy can u confirm that this incorrect url is still occurring on your account as I cannot i cannot reproduce it. thanks.

**Comment by tangentfairy** [comment]
The URL is only incorrect when you are in "edit" view. The URL is fine in the db. It is just when you are "previewing" the profile in edit mode.

**Comment by daveymoran-nearform** [comment]
i logged in as myself, clicked my profile(link in top nav bar), clicked edit, and hovered over twitter icon and the link is not doubled. am i missing a step or testing in the wrong location?
![screen shot 2015-09-24 at 09 49 35](https://cloud.githubusercontent.com/assets/12595380/10069140/f5c91306-62a1-11e5-9f64-f6aabc27d74b.png)

**Comment by tangentfairy** [comment]
Put a http:// in front of the Twitter URL?

**Comment by daveymoran-nearform** [comment]
there isnt supposed to be one there, the placeholder text describes that. the input field is only looking for a twitter handle - do you want this input behavior to be changed? i recall this was causing confusion with users a while back, think there is an issue or two relating.

**Comment by daveymoran-nearform** [comment]
if you save the twitter filed with a http:// or a https:// it gets removed on save. the issue with the link from the original image is that the twitter field input is http//... not http://... so the regex is bypassed as this is just 6 charachters and deemed a legit input, if the original twitter value had the colon in between the p and the first / it would not look like it is doubling up the http value.

**Comment by tangentfairy** [comment]
It seems like the user probably put http// in so we'll close this until any further reports are submitted! Thanks for investigating @daveymoran-nearform
