### ISSUE TITLE
Make user type selection a dropdown on manage users page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#681]
Champions are unable to add a user type because they don't know they need to _type_ e.g. "parent" to select a new user type.

Can we Make this a dropdown selection which shows the list of user types, rather than forcing the user to know the names of each user type?

**Comment by gbonanome** [comment]
Hi, if you're opening this issue from my [question on the forum](https://forums.coderdojo.com/topic/13/managing-my-dojo-adding-members/6) maybe there's a misunderstanding. There's no problem understanding the needing to type, my issue was that I'm not able to add more than one user role.

**Comment by tangentfairy** [comment]
Hi @gbonanome - I think it still needs to be more intuitive to use so I will keep this open.

On your issue, if you are still experiencing problems can you send a screenshot to info@coderdojo.com please?

**Comment by DanielBrierton** [comment]
This is being addressed by a new change role action in a redesign of the manage users page.

**Comment by Wardormeur** [comment]
@DanielBrierton To close?

**Comment by DanielBrierton** [comment]
Yeah, role selection is much more obvious now, think we can close this.
