### ISSUE TITLE
User type dropdown not working in Italian

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#682]
Report from @gbonanome that the user type dropdown on the manage users page is not working when switched to Italian

![noparentlabel](https://cloud.githubusercontent.com/assets/1136491/10019188/d4634886-6133-11e5-9f78-8ba6d83e88d8.gif)

"I can confirm that switching to the English interface works for me. Instead on the italian interface there's a javascript error (TypeError: Cannot read property 'name' of undefined)"

**Comment by daveymoran-nearform** [comment]
fixed, this was a localization error. have localized the usertypes on page load, now the functionality behaves as expected.
will update labels when deployed.

**Comment by tangentfairy** [comment]
@gbonanome this is fixed now!

**Comment by gbonanome** [comment]
@tangentfairy :+1: thanks! It works :smiley:
