### ISSUE TITLE
Dojo name not showing on Salesforce

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#683]
Here is one example: https://eu2.salesforce.com/00Qb000000I487C?srPos=0&srKp=00Q

The company name is "Craig Hand" but on his listing https://zen.coderdojo.com/dashboard/dojo/gb/craigavon/craigavon It is Craigavon. 

Although, here is an example that _was_ converted: https://zen.coderdojo.com/dashboard/dojo/ro/timisoara-timis-county/oce-timisoara
Account is here https://eu2.salesforce.com/001b000001OlIfHAAV/d?retURL=https%3A%2F%2Fnpe01.eu2.visual.force.com%2Fapex%2FaccountViewOverride%3Fid%3D001b000001OlIfH%26sfdc.override%3D1&nooverride=1 

but the Dojo name is nowhere to be seen on the Salesforce account.

This Dojo https://eu2.salesforce.com/001b00000143ZzlAAE/d?retURL=https%3A%2F%2Fnpe01.eu2.visual.force.com%2Fapex%2FaccountViewOverride%3Fid%3D001b00000143Zzl%26sfdc.override%3D1&nooverride=1

Has the correct name (as on the listing https://zen.coderdojo.com/dojo/at/welser-strasse-26-4060-leonding/linz) - and the champion account is "Karin" as listed in the partners.

**Comment by tangentfairy** [comment]
@rosalanghammer is this resolved to the best of your knowledge? I know we had an issue with it in the past but I think it is working now?

**Comment by rosalanghammer** [comment]
Seems to be fixed now. :)

On 25 November 2015 at 15:58, Ursula Clarke Everett <
notifications@github.com> wrote:

> @rosalanghammer <https://github.com/rosalanghammer> is this resolved to
> the best of your knowledge? I know we had an issue with it in the past but
> I think it is working now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/683#issuecomment-159653095>
> .
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by tangentfairy** [comment]
Excellent!
