### ISSUE TITLE
Put list of forum mods in an env file

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#688]
This list should really be in an env file https://github.com/CoderDojo/cp-zen-platform/blob/master/web/options.base.js#L103

**Comment by BenChapman** [comment]
Completed: https://github.com/CoderDojo/cp-zen-platform/pull/665 & https://github.com/CoderDojo/cp-aws-stack/pull/9

**Comment by tangentfairy** [comment]
Done thanks!
