### ISSUE TITLE
Ninja cannot see parents profile

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#689]
I logged in as this parent http://zen.coderdojo.com/dashboard/profile/31c1e5d2-6c9b-4adc-86ac-66b57d0449db and added the child "Amy" to his profile. She's an O13 ninja. I then logged in as Amy but I couldn't see her dads profile, it says it is private.

Surely it makes sense for a ninja to always see their parents profile even if it is private?

**Comment by ckiss** [comment]
@tangentfairy not sure here. Would you like to make parent profile visible to children even if profile is private? Or do you need to investigate this more?

**Comment by tangentfairy** [comment]
I think I'd like to leave a request for comments label on this one. Let's see what the community thinks. 

I'm in favour of making the parent profile visible to any ninjas attached to it.

**Comment by tangentfairy** [comment]
Parent profile to be visible to ninjas

**Comment by tangentfairy** [comment]
@ckiss this still happens, I can give you the profile info if you need

**Comment by ckiss** [comment]
@tangentfairy sure, let's talk in private. I tested it with a new account and it worked, so there might be something wrong with existing accounts.

**Comment by tangentfairy** [comment]
I caused a timeout error by going to this profile now. 

![screen shot 2015-11-30 at 11 39 21](https://cloud.githubusercontent.com/assets/1136491/11470602/070c48f6-9757-11e5-8b10-d62dd0f87d22.png)

**Comment by tangentfairy** [comment]
Hasn't arisen since, closing for now.
