### ISSUE TITLE
Error on date when creating event

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#691]
User cannot change date - it seems to default to 1970 (beginning of unix time!) and she cannot click "save draft" - she gets an error.

![screen shot 2015-09-24 at 10 54 36](https://cloud.githubusercontent.com/assets/1136491/10070511/e1cf09ce-62aa-11e5-9313-14ee98de0aeb.png)

**Comment by ckiss** [comment]
fixed & deployed
