### ISSUE TITLE
Platform should force HTTPS and include a HSTS header

### ISSUE THREAD

**Issue by BenChapman** [CoderDojo/community-platform#693]
The platform currently doesn't force users onto HTTPS. Users should be forced onto HTTPS on the production environment, and additionally the platform should send a HSTS header in production.

**Comment by ChristianVermeulen** [comment]
Wait, this was already known 5 months ago? Shouldn't this have higher priority? It seems pretty risky to me, especially since we are talking about private data of parents and children....
Im nit to familiar with the platform setup but a simple redirect should fix the problem right?

**Comment by Wardormeur** [comment]
Considering it is working "by default" (you can access it from https), it may not have been escalated, and considering a limited amount of people can actually fix it (server configuration is not open to my knowledge), this probably have been delayed.

**Comment by PhilipHarney** [comment]
Thanks for letting us know. I'm looking into this, but we're sort of in maintenance mode for the next couple of weeks while we're between developers. I've applied a server rule that *should* enable redirection and it seems to be working intermittently. I'm hoping that it just needs to propagate. I'll check back in a few hours.

**Comment by BenChapman** [comment]
I believe this had been done but not closed and there is has since been a regression. Investigating now.

**Comment by BenChapman** [comment]
I have put in place a temporary fix on the AWS stack. Will need to introduce it into the cp-zen-platform server, rather than relying on the environment the app is deployed to.

**Comment by BenChapman** [comment]
Code based fix now in https://github.com/CoderDojo/cp-zen-platform/commit/bc255003b05f34b074fdc7d42e868bb0da219a95. In the process of reviewing requirements for HSTS header.

**Comment by ChristianVermeulen** [comment]
Seems to be a good fix :) At least https is forced now so all traffic is properly encrypted and secure! Wether is the right solution or not I'll leave up to you guys.

**Comment by DanielBrierton** [comment]
The HSTS header has been since added, so along with Ben's commit, this issue is resolved.
