### ISSUE TITLE
Twitter handle on profile page

### ISSUE THREAD

**Issue by Aryess** [CoderDojo/community-platform#695]
Continuation of https://github.com/CoderDojo/cp-zen-platform/issues/678

I understand it can be confusing for some, but I think now it's at least as confusing, if not more. To be honnest, I wouldn't have realised if I didn't check the link on the left hand side after saving. 

How about something like that?
![capture d ecran de 2015-09-25 16 23 36](https://cloud.githubusercontent.com/assets/3518172/10104573/49a6f898-63a2-11e5-984d-32503c663987.png)
I does break the design a bit, but at least it can't be more clear as to what we're expected to type. Maybe you can prefill the field with the "twitter.com" part as some un-editable text. Not really sure on that part.

**Comment by Aryess** [comment]
In any case, for security reason, you probably shouldn't store the link like that, let's say as a username I put "myevilcloneoftwitter.com/myhandle" as my handle, you click on it, it asks you for your twitter credentials...

Another graceful solution (maybe a bit more than breaking the design) would be to let the user type either `twitter.com/myhandle` or `myhandle`, parse it, and in both case store just `myhandle`. Both users are happy, and it's more secure. Bit of work on the backend though, I admit.

**Comment by tangentfairy** [comment]
I like this idea, +1 from me, will leave the request for comments label on here for a bit to see if there are any objections.

**Comment by dberesford** [comment]
+1 from me also, really good idea :-)

**Comment by tangentfairy** [comment]
Removed request for comments, let's do this

**Comment by tangentfairy** [comment]
__Technical Spec__
There's a few places this will have to be updated, on:
- The Dojo listing
- The users profile
- The champion application section

See a list here and refer to me with any questions: https://github.com/CoderDojo/cp-zen-platform/search?utf8=%E2%9C%93&q=twitter&type=Code

**Comment by michaelfbradley** [comment]
I'm take this one

**Comment by DanielBrierton** [comment]
My suggestion for this:

```javascript
function getTwitterUsername(str) {
  return str.match(/(@|((http(s)?\:\/\/)?(www\.|m\.|mobile\.)?twitter\.com\/)?)?([A-Za-z0-9_]+)/)[6];
}
```

This would allow users to type 'https://twitter.com/DanielBrierton', 'mobile.twitter.com/DanielBrierton', '@DanielBrierton', or just 'DanielBrierton' and it would figure it out and create the correct link.

**Comment by Wardormeur** [comment]
Covered through SAD
