### ISSUE TITLE
UI changes for events section

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#702]
- Adjust spacing on sessions as bottom of event form [Done]
- When the minus icon appears beside the session, float it to the left of the text box inline rather than above it on a separate line [Done]
- Info icon at bottom of events create/edit form shows up on hover but the one at the top shows up on click. Make this consistent (hover) [Done]
- Match event view on Dojo listing page to wireframe [Done]

Wireframe:
![screen shot 2015-10-01 at 14 35 08](https://cloud.githubusercontent.com/assets/1136491/10222013/a45b10c0-6849-11e5-893a-55c91aa44abc.png)

"Total event capacity" instead of "event capacity" as in wireframes [Done]:
![screen shot 2015-10-01 at 14 49 00](https://cloud.githubusercontent.com/assets/1136491/10222429/d1dce990-684b-11e5-8d01-f59ea1b35e15.png)

Requirements doc https://docs.google.com/document/d/1H0VMC49dSVn0-MFoeQPBw6RkRY5U2AZeX_E_3d2DRAQ/edit

Formatting on event confirmation email needs to be adjusted 
- add spacing in the name/type/quantity section
- add buttons/colours e.g. status approved to be green etc.

![screen shot 2015-10-01 at 14 57 10](https://cloud.githubusercontent.com/assets/1136491/10222590/cacab55a-684c-11e5-99cc-f39209c67a3e.png)

**Comment by tangentfairy** [comment]
While I'm working on implementing these changes I'd appreciate community feedback on further improvements.

**Comment by tangentfairy** [comment]
Last thing to be done is changing the wording on the emails

**Comment by Wardormeur** [comment]
Closing. We're simplifying and hidiing as much as possible sessions, this won't happen.
