### ISSUE TITLE
Change reply to on emails

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#704]
Was discussing this with @rosalanghammer 

- Can we change the reply to on event invites and event confirmations to be to the Dojo email 
- Can we also change the join member invite emails to reply to the users account [Done]

We are getting emails into ZenDesk that need to be resolved by the Dojo rather than the Foundation.

**Comment by tangentfairy** [comment]
Done on invites, to test the other one

**Comment by tangentfairy** [comment]
Not done on the request to join a Dojo

**Comment by speciousstream9** [comment]
Having the same effect, for parents replying to Dojos and getting us instead.

**Comment by Wardormeur** [comment]
Verified applications is not having the proper reply to
Event invite is having it
