### ISSUE TITLE
Allow file uploads in NodeBB

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#707]
There's an option here https://forums.coderdojo.com/admin/settings/post to enable file uploads. 

But on the server side we'd have to set it up to point to s3 for uploads, so it requires a bit of work first.

**Comment by DanielBrierton** [comment]
We discussed this, and have decided against enabling this. Hosting users' content in this way adds more moderation issues, including copyright takedown requests. File uploads could also be used as an attack vector if a vulnerability were to be found in NodeBB.
