### ISSUE TITLE
Fork repos instead of cloning it when doing ./localdev.js init command in cp-local-dev

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#709]
At the moment, I have to test my fixes to make sure it's working properly in the cloned repos, if it is fixed, I then have to do those changes to the forked repo and do the pr's from there. 

It would be great if the ./localdev.js init command forks the repos so contributors don't have to do twice the work.

**Comment by Wardormeur** [comment]
Either way is to use the git remote on the cloned repo to commit to your fork

**Comment by kennanseno** [comment]
@Wardormeur hmm. that would be fairly useful and easy workaround. you can add it on the localdev repo readme on how to do it btw.

https://github.com/CoderDojo/cp-local-development

**Comment by Wardormeur** [comment]
Interesting reading regarding Github API to ease it further more
http://stackoverflow.com/questions/2423777/is-it-possible-to-create-a-remote-repo-on-github-from-the-cli-without-ssh
Can we rely on the git general username? I doubt so :|

**Comment by Wardormeur** [comment]
README updated, doing the fork on behalf of somebody is too much of a trouble
