### ISSUE TITLE
Ability to filter by date on manage recurring events

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#712]
It's difficult to see at a glance how many attendees I have for a given date on the recurring events.

Add a dropdown at the top of the page to filter by date. When filtered, the check in box will be a singular check box and only the users attending on that date will be shown.

Then this will also make it easier for me to download a CSV of attendees for a given date.

**Comment by Wardormeur** [comment]
"Recurring"/Term events don't work that way. see https://github.com/CoderDojo/community-platform/issues/716 for a reference.
We may work on recurring event instead of term events in the future, in which case ^ this should definitely be supported. Closing off in the meantime.
