### ISSUE TITLE
Disable editing on past events

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#713]
You can't edit a past event - there's no save draft or publish buttons.

It's a bit confusing that you can still change the text on this page and add users to the invites list etc, so can we disable all of the inputs on this page if the event is a past event.

**Comment by tangentfairy** [comment]
__Technical spec__
See this template, use the existing pastEvent var https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/events/dojo-event-form.dust

Make the inputs have the "readonly" attribute.

**Comment by flakyfilibuster** [comment]
I can take care of this @tangentfairy

**Comment by tangentfairy** [comment]
Great, go for it! :)

**Comment by flakyfilibuster** [comment]
Done in PR https://github.com/CoderDojo/cp-zen-platform/pull/812 @tangentfairy

**Comment by tangentfairy** [comment]
This is live now, thanks @flakyfilibuster !
