### ISSUE TITLE
502 when exporting guest list

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#717]
Doesn't work on local either

![screen shot 2015-10-06 at 12 39 23](https://cloud.githubusercontent.com/assets/1136491/10307494/63ad93a4-6c27-11e5-8eac-27244a9086c8.png)

**Comment by davey-m** [comment]
aws logs say:
Message: seneca: Action cmd:exportGuestList,role:events failed: Cannot read property 'headers' of undefined.

**Comment by tangentfairy** [comment]
Works, thank you!
