### ISSUE TITLE
Redesign UI of Dojo listing

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#718]
This page could do with some design love!

It was mentioned by a parent that they thought they could click on the "Register ahead" box to register. I think we could make this yellow instead of blue (blue usually means something is a link!). There is the potential to link "Register ahead" to the events part of the page.

Also thinking that we could move the map, so that it displays at the top of the page, with the Dojo name appearing on top. 

The headings could be a little less vibrant - maybe a single border rather than a double border. We could consider changing the colour theme on the Dojo listing also.

Would love to hear community feedback on how to change the UI of the page - this is non inclusive of new additions to the page. We can discuss moving things around the page, changing colours and fonts in this issue - new features can go into a separate issue.

**Comment by willknott** [comment]
Sorry Tangent, you're think like someone who knows the system... Its not the colour. That requires knowledge which is built p over time and, sorry to say, some parents don't have. (Besides, if they went to the web after CSS changed the rules, blue does not always mean "click here")

The meaning of "Register Ahead" completely changed when registration and setting up a profile became a requirement...
Parents think they have "registered" when they join a dojo. The problem is... the have registered. Booking a seat is required

Change 1.
Change "Register Ahead" to "seat booking required"/ "Seat Booking needed". (Which ever fits)
Change 2. For each event where booking is required, replace the "more info" button with "more info and booking"

**Comment by tangentfairy** [comment]
We have a similar box on the login page that is clickable so that may be causing confusion - http://zen.coderdojo.com/login it may be assumed that any blue box that looks like this is clickable.

On change 2, we have changed the event appearance so that it no longer says "info" - it is an accordion drop down. We could do a couple of things here:
- Add the word "book here" before the arrow
- Automatically have the first event in the list on the Dojo listing page appear expanded 

Would love to hear feedback on these proposed changes from all community members.

**Comment by rosalanghammer** [comment]
We could consider scrapping the 'Register Ahead', 'Open Come Along' etc. as many Dojos forget about this and have left their Status as 'In Planning' which was default on the old Zen? Instead we would ensure each Dojo has booking requirements in the notes before being verified. Would be great to get community feedback on this though as some Dojos may use it.

Also in terms of UI I would prefer to see the 'Contact' section not being buried down on the right as it is the most important section for parents trying to find out information. Pulling it up higher on the right or into the middle section may be more effective.

**Comment by tangentfairy** [comment]
Both very good points @rosalanghammer - it would be good to know if Dojos are using these options before using them.

Looking at the statistics in the database, for all active Dojos (any Dojo listings currently public), here are the numbers:
- In planning: 154
- Open, come along: 259
- Register ahead: 359
- Full up: 46

Would like to see the contact section moved up also!

**Comment by Giustina** [comment]
Agree with @rosalanghammer about scrapping the tags, they could be changed to be more self explanatory e.g 

Tags could be changed to 
- In Planning - Check Back Soon
- Book a Ticket 
- Full up 

Regarding the contact section - I love the idea of not needing to oversee a Dojo email address (from a parent/ninja perspective) & having all contact via the Platform, but thats a future feature request :)

**Comment by willknott** [comment]
You also need a "just show up"

**Comment by tangentfairy** [comment]
Yes I think saying "just show up" instead of "Open, come along" might be a bit clearer too!

**Comment by LauraCDF** [comment]
I suggest changing the terminology to 'Booking Required' here instead of 'Book a Ticket' to make it clear you can't just show up. I agree with having a 'Just show up!' option also. Could extend it to 'Just show up, no booking required!' to be super clear.

**Comment by tangentfairy** [comment]
Sounds good :+1:

**Comment by tangentfairy** [comment]
List of UI changes to made to this page:
- Move events up to top of page
- Boxes at top right of page will move down the page
- We'll be renaming "booking required"
- If a Dojo has no events, display a message saying "You may need to contact this Dojo to find out about upcoming events" (People assume if the Dojo is not using the events system that they have no events coming up)

**Comment by tangentfairy** [comment]
This is live now, so if we can put further tweaks into a new issue that'll be easier to tackle. Hopefully we can make small incremental changes bit by bit! 

We're also looking at a redesign of navigation and Zen in general next year, so that will contribute to further improvements.
