### ISSUE TITLE
Invite all members of a dojo to a dojo event

### ISSUE THREAD

**Issue by willknott** [CoderDojo/community-platform#721]
One of the features of the previous system was the ability to invite ninjas to an event..
Its something quite a few parents relied on (I get emails since the switch to zen asking when we are restarting, or why they didn't get an event).

It is *possible* to invite a single member to an event, but the ability to invite all members of a dojo to an event is not present. (Leaving the dojo should stop mails).

Can this feature be added?

**Comment by tangentfairy** [comment]
You can invite all members of a Dojo to an event as a ticketing admin, did you want the ability to do this a a Dojo member?

**Comment by willknott** [comment]
When was this added? I guess I need to see release notes, didn't know that
it had become available (explains why it's off the backlog)

**Comment by tangentfairy** [comment]
It was added as part of the new events system, requested here https://github.com/CoderDojo/community-platform/issues/663

Here is the pull request for that feature https://github.com/CoderDojo/cp-zen-platform/pull/691 which released two days ago.

**Comment by rosalanghammer** [comment]
Hi @willknott - can you take a look at this issue to remove current event invite feature and replace with an invite all instead? Want to know Champions thoughts on this in terms of usability - https://github.com/CoderDojo/community-platform/issues/764

**Comment by willknott** [comment]
Thank the God of your choosing that the feature is added.

Instead of getting multiple mails a day about when the next session is, the
parents / ninjas are signing themselves up.

One  catch is, if you set up multiple events (and invitations), they sign
up for one, and show for another. (work around... Only one invite at a
time)

**Comment by rosalanghammer** [comment]
Hi @willknott can you add comments to #764 with regards to what the best invite would be :)

**Comment by tangentfairy** [comment]
Closing this - we can look at implementing https://github.com/CoderDojo/community-platform/issues/764 if we want to change the invite functionality, further discussion can go there.
