### ISSUE TITLE
Flag on telephone number on profile out of line when invalid

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#723]
![screen shot 2015-10-07 at 14 43 41](https://cloud.githubusercontent.com/assets/12827424/10339266/5c6ce014-6d02-11e5-891e-87ed797fc868.png)

**Comment by tangentfairy** [comment]
__Technical spec:__
- The champion registration form template (is here)[https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/champion/create.dust#L61]. To get to this page, click on start a dojo and go past the first registration page. The champion registration page is where you can enter a blank phone number to see the error
- There's a second place you can enter a phone number, on the [user profile here](https://github.com/CoderDojo/cp-zen-platform/blob/6c59045fc5d5558e8d9cf9154a53463354385e52/web/public/templates/profiles/general-info.dust#L75).

**Comment by flakyfilibuster** [comment]
I can take care of this, I think

**Comment by tangentfairy** [comment]
Deployed, thanks @flakyfilibuster :)
