### ISSUE TITLE
Incorrect status error on Dojo admins for user endpoint

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#726]
I was calling this endpoint as a test http://zen.coderdojo.com/api/1.0/users/dojo_admins_for_user/:user_id

I was logged out. And I got a 200 error - it would make more sense to get a 403

![screen shot 2015-10-08 at 15 23 24](https://cloud.githubusercontent.com/assets/1136491/10369245/3173d708-6dd1-11e5-912a-4d5bf22ba874.png)

**Comment by Wardormeur** [comment]
A permissions system has been implemented in between. This doesn't happen anymore.
