### ISSUE TITLE
Add table with log of dates Dojos are marked inactive or active

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#727]
We don't currently store what date a Dojo's stage is set to inactive. Similarly we don't know when a Dojo was marked active (if it was previously inactive).

Store these dates in a log table of it's own for statistical purposes.

**Comment by rosalanghammer** [comment]
+1 Sooner we get this, the faster we can produce Dojo retention stats :)

**Comment by tangentfairy** [comment]
Updating this - if we can just do a timestamp of the last time the dojo was marked inactive, and overwrite that timestamp any time it is inactive, that will do for now :)

**Comment by Wardormeur** [comment]
This has been done last sprint. https://github.com/CoderDojo/cp-dojos-service/commit/991de5fcc2433f70fd7284068010a36aaef466ce
