### ISSUE TITLE
Browse button off center on tablet size screen

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#734]
Resize the edit profile screen to be smaller on windows - to tablet size and the browse button overflows
It's fine on a mac!

**Comment by tangentfairy** [comment]
__Technical spec__
https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/user-profile.dust

**Comment by DanielBrierton** [comment]
I'm not sure what this is actually referring to, as we no longer have a browse button. @Wardormeur: Any ideas? Or will we just close it?

**Comment by Wardormeur** [comment]
Probably the md breakpoint makes it looks huge on tablet on landscape, because it was using xs-12

**Comment by Wardormeur** [comment]
Closing off. The user profile page has been reworked multiple time in between.
