### ISSUE TITLE
Info icon off centre on table size view

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#735]
![screen shot 2015-10-13 at 15 30 17](https://cloud.githubusercontent.com/assets/1136491/10457716/58b14dd6-71bf-11e5-9687-afb7af34a7ff.png)

**Comment by tangentfairy** [comment]
__Technical spec__
Templates are here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/start-dojo-wizard/step-one-register.dust and here https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/start-dojo-wizard/step-one-register.dust
CSS is here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/css/dashboard.less

**Comment by michaelfbradley** [comment]
I'm on this

**Comment by tangentfairy** [comment]
Deployed now, thanks @michaelfbradley
