### ISSUE TITLE
Addition of a required capacity field to Dojo listing creation page. 

### ISSUE THREAD

**Issue by LauraCDF** [CoderDojo/community-platform#736]
Will assist with tracking of Dojo number. 

Should prompt Dojo who already have listing to add capacity next time they edit their profile as is required now.

**Comment by tangentfairy** [comment]
This would need to be added here: https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/dojo-form.dust#L139

It could have a placeholder that says "Please let us know the average capacity of youths at your Dojo".

It will be more or less the same as this input field: https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/dojo-form.dust#L15 with it's own required message (the validation error that appears).

The text goes in the messages.po file: https://github.com/CoderDojo/cp-zen-platform/blob/master/web/locale/en_US/messages.po

The cd_dojos table will need to be altered using a db migration script in this folder: https://github.com/CoderDojo/cp-dojos-service/tree/master/scripts/database/pg/migrations
These scripts are run when you start up your local environment.

It will need to be added to Salesforce also. See here https://github.com/CoderDojo/cp-dojos-service/blob/26cf998b81f469daaab86d42912f9d5824cc68fd/dojos.js#L1234 

For Salesforce tests see https://github.com/CoderDojo/cp-salesforce-service/blob/fd828080c3618bc3f62617879287aec546156915/test/salesforce.js#L156 and https://github.com/CoderDojo/cp-salesforce-service/blob/fd828080c3618bc3f62617879287aec546156915/test/fixtures/salesforceDojos.json
