### ISSUE TITLE
Address only to be compulsory for Champions in registration form. 

### ISSUE THREAD

**Issue by LauraCDF** [CoderDojo/community-platform#737]
Is not to be compulsory for Mentors, parents or children on their profiles.

**Comment by tangentfairy** [comment]
__Technical spec__
Remove required here: https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/profiles/general-info.dust#L66

**Comment by tangentfairy** [comment]
This is live now and tested, thanks @iwtcs! :smile:
