### ISSUE TITLE
Add banner to top of profile registration page to say 'Not all of this info is viewable on your profile, this is just for our record'

### ISSUE THREAD

**Issue by LauraCDF** [CoderDojo/community-platform#738]
@rosalanghammer Can you add exact text?

**Comment by tangentfairy** [comment]
Any update on the text for this? @rosalanghammer

**Comment by rosalanghammer** [comment]
Not all information entered on your profile is viewable. You can choose to
hide certain information by ticking the hide buttons at the bottom of the
page.

On 18 November 2015 at 11:58, Ursula Clarke Everett <
notifications@github.com> wrote:

> Any update on the text for this? @rosalanghammer
> <https://github.com/rosalanghammer>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/738#issuecomment-157689973>
> .
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by tangentfairy** [comment]
__Technical spec:__
- The [template is here](https://github.com/CoderDojo/cp-zen-platform/blob/6c59045fc5d5558e8d9cf9154a53463354385e52/web/public/templates/profiles/general-info.dust)
- Use the `alert` and `alert-info` classes on a div to display this

**Comment by tangentfairy** [comment]
I'm going to also add a banner about how to book an event here. This seems to be the point where parents are getting lost.

**Comment by tangentfairy** [comment]
@rosalanghammer I added a message per user type, as the parents don't have the optional fields on their profile at present.

It says "Only your username and profile picture are publicly viewable. Other fields are for administration purposes only." for a parent, and the message that you provided will show for other types.

Here's a screenshot of the event message I also added:
![screen shot 2015-11-30 at 08 16 22](https://cloud.githubusercontent.com/assets/1136491/11467813/af6a157e-9742-11e5-8590-8210878077a2.png)

**Comment by rosalanghammer** [comment]
Looks good 👍

On 30 November 2015 at 09:14, Ursula Clarke Everett <
notifications@github.com> wrote:

> @rosalanghammer <https://github.com/rosalanghammer> I added a message per
> user type, as the parents don't have the optional fields on their profile
> at present.
>
> It says "Only your username and profile picture are publicly viewable.
> Other fields are for administration purposes only." for a parent, and the
> message that you provided will show for other types.
>
> Here's a screenshot of the event message I also added:
> [image: screen shot 2015-11-30 at 08 16 22]
> <https://cloud.githubusercontent.com/assets/1136491/11467813/af6a157e-9742-11e5-8590-8210878077a2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/738#issuecomment-160565766>
> .
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.
