### ISSUE TITLE
Add "Tao verified" checkbox on edit Dojo page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#741]
For CDF admins, display a "Tao verified' checkbox on the manage dojos page.

Enabling this officially "CDF" certification will display a Tao logo on the Dojo page.

Need to figure out what the Tao logo on listing page will look like.

**Comment by tangentfairy** [comment]
See https://github.com/CoderDojo/community-platform/issues/736 for Technical spec on how to add a field to a Dojo listing.

See here https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/templates/dojos/dojo-detail.dust for Dojo listing template.

**Comment by Aryess** [comment]
Still not ready for dev?

**Comment by tangentfairy** [comment]
@Aryess Ready for dev!

**Comment by Aryess** [comment]
Ok I'll try this one

**Comment by tangentfairy** [comment]
This is live!
