### ISSUE TITLE
Deeplinking on start-dojo flow

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#743]
Request from @petecoderdojo to be able to deeplink e.g. the champion registration form goes to /start-dojo/champion-registration rather than just /start-dojo/ 

All four steps are currently on the same URL.

List of links:
1. /start-dojo/champion-registration/
2. /start-dojo/setup-your-dojo/
3. /start-dojo/create-listing/

**Comment by Wardormeur** [comment]
Covered through SAD
