### ISSUE TITLE
Errors when viewing CDF admin profile

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#745]
Rosa was testing the system and she created a mentor profile. She tried to view a CDF admin profile with it and we got two fatal errors:

```
Message: seneca: Action cmd:load_champions_for_user,role:cd-users failed: [TIMEOUT].

Code: act_execute

Details: { id: 'tv5fdu1z1399/g14ptw8j6g09',
  gate: false,
  ungate: true,
  desc: 'cmd:load_champions_for_user,role:cd-users',
  cb: [Function],
  plugin: { name: 'cd-users', tag: '-' },
  fn: [Function: cmd_load_champions_for_user],
  time: { start: 1444751500051, end: 1444751620063 },
  'orig$': { [Error: [TIMEOUT]] timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:load_champions_for_user,role:cd-users',
  instance: 'Seneca/0.6.4/8unuqgmmd0qb/1444751364917/29336/-' }

```

```
Seneca Fatal Error
==================

Message: seneca: Action cmd:load_dojo_admins_for_user,role:cd-users failed: [TIMEOUT].

Code: act_execute

Details: { id: 'gk7ztogzc23x/9hy1x3wd6yj2',
  gate: false,
  ungate: true,
  desc: 'cmd:load_dojo_admins_for_user,role:cd-users',
  cb: [Function],
  plugin: { name: 'cd-users', tag: '-' },
  fn: [Function: cmd_load_dojo_admins_for_user],
  time: { start: 1444751244075, end: 1444751364075 },
  'orig$': { [Error: [TIMEOUT]] timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:load_dojo_admins_for_user,role:cd-users',
  instance: 'Seneca/0.6.4/8e1k5yji327q/1444751234071/29267/-' }

```

**Comment by tangentfairy** [comment]
Came in another couple of times today, it happened with a champion who is the owner of more than one Dojo.

**Comment by tangentfairy** [comment]
This error came in again after deployment (about half an hour after).

**Comment by tangentfairy** [comment]
This happened this morning when I tried to accept a badge

**Comment by tangentfairy** [comment]
Update: I reproduced this locally by doing the following:
- Created a new mentor account
- Joined two Dojos
- Awarded a badge as one of the Dojo champions
- Logged back in as original mentor and accepted the badge. At this stage the badge is showing up correctly on my profile.
- Go back to the page of one of my Dojos 
- Click on my name to go back to my profile. Nothing appears to happen. Eventually I get a slew of timeout errors

**Comment by tangentfairy** [comment]
CC @BenChapman who is taking a look

**Comment by mihaidma** [comment]
Can't reproduce it. I am working to implement tests that execute this scenario to see if it reproduces.

**Comment by tangentfairy** [comment]
I can reproduce this on my machine, it might be best for me to give you a dump of the data I have that causes it. I also have a dump of some debug that is output when this happens.

**Comment by tangentfairy** [comment]
Another user has replicated this error on live, they report that in the console they see `https://zen.coderdojo.com/api/2.0/profiles/user-profile-data Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT)` 

In the logs I see the same error of `cmd:load_dojo_admins_for_user` so I think this is the same problem.

This occurs for them before an event happens, when they are loading the list of users in an event (the Dojo has a fair amount of applications for an event). Automatic approval was turned on. 

![unable_to_access_waitlist](https://cloud.githubusercontent.com/assets/1136491/11030690/96ec46c4-86c7-11e5-9d5c-1d29b6be2018.png)

**Comment by BenChapman** [comment]
Figured out the number of calls this query makes. Here's a tree of the calls for reference.

```
cd-users:load_dojo_admins_for_user
    cd-dojos:dojos_for_user { id: userId }
        cd-dojos:load_usersdojos { userId:args.id, deleted: 0 }
    cd-dojos:load_dojo_admins { dojoId: dojo.id, user: args.user }
        cd-dojos:load_usersdojos { dojoId:dojoId }
        cd-users:load { id: userDojo.userId, user: args.user }
            validateUserRequest { user, id }
                cd-dojos:load_usersdojos { userId: id }
                cd-dojos:load_dojo_champion { id: userDojo.dojoId }
                    cd-dojos:load_dojo_users { dojoId: dojoId }
                        cd-dojos:load_usersdojos { dojoId: dojoId }
                    cd-dojos:load_usersdojos { userId:user.id, dojoId:dojoId }
                cd-dojos:load_usersdojos { dojoId: userDojo.dojoId }
                cd-profiles:list { userId: id }
```

**Comment by tangentfairy** [comment]
Thanks for looking into that - it seems like there are a lot of calls happening there. I'd imagine this happens when a user is a champion of more than one Dojo, and perhaps when there is more than one champion. Hopefully this will help @mihaidma to automate.

**Comment by mihaidma** [comment]
I start looking at it and let the automation for later.

**Comment by rjrodger** [comment]
@tangentfairy Please post full error dump as all the information is relevant, thanks.

These errors are occurring in the cp-zen process - correct?

So, cp-users times out for whatever reason. Seneca-transport then raises a timeout error, and the seneca instance in cp-zen on which .act is called then dies, as it has a fatal$ fixed arg. 

This is the working assumption, so please correct if wrong @dberesford 

The seneca instance comes from https://github.com/hapijs/chairo - can we confirm that chairo is *not* using a seneca instance with a `fatal$:true` fixed arg @geek ?

(chairo has a separate instance issue which may affect this, @geek please review: https://github.com/hapijs/chairo/issues/24)

Also, we need to rule out this as a cause: https://github.com/senecajs/seneca/blob/master/seneca.js#L290
@mihaidma @tangentfairy do you have reproduction path? if so you can test when this event handler is commented out.
@geek this should really be optional as not related to initialisation - probably should be a strict option

**Comment by geek** [comment]
@rjrodger chairo is not setting `fatal$`.  I will resolve #24 as well.

What version of node is this all running on?

**Comment by tangentfairy** [comment]
v0.10.38

**Comment by tangentfairy** [comment]
@rjrodger I sent the dump to Mihai and Damian, can forward to you also if you want, a little big for Github and just for security reasons it is not in this issue.

**Comment by dberesford** [comment]
@geek we can move to a newer node, we were locked on 0.10 as I think the seneca elasticsearch store wouldn't work with 12, but we're not using that now so we can move if needs be

**Comment by geek** [comment]
@dberesford no problem... I will need to fix that chairo bug in an older version then. Last night I cut a new release (v 1.0.0) that requires ES6 support

**Comment by mihaidma** [comment]
I can reproduce a crash in an almost consistent way but didn't find the issue yet.

How to reproduce: login, go to mydojos, on the first dojo from the dojo list make view events, back, view listings back. After **2-5 repeats** it crashes. This happened with the db dump from Ursula with real data, did not reproduce on the test data.

**Comment by ckiss** [comment]
I'm doing the same thing with the same DB(the ones from Ursula) and I couldn't make it to crash. After a while is working slower but it's still working. 

I found that we might not need to call profiles/user-profile-data when going to my events page or dojo listing. I'll test this theory more.

**Comment by tangentfairy** [comment]
@ckiss are you using the same user (it's a parent) that Mihai is? I seem to manage to do it by going to the profile a lot. I think perhaps double clicking the profile will cause multiple calls. Clicking around a bit gets it to crash really easily on that account.

It's happening with a fair few people in production also.

**Comment by ckiss** [comment]
@tangentfairy yes, using your account ursula+parent@coderdojo.org

**Comment by geek** [comment]
@dberesford I recommend upgrading to node v5.  Cluster has changed a lot, especially because of the work of @cjihrig

see
https://github.com/nodejs/node/commits/master/lib/cluster.js

**Comment by tangentfairy** [comment]
This error came in this morning on the cp-dojos-service:

```
Seneca Fatal Error
==================

Message: seneca: Action cmd:load_dojo_users,role:cd-dojos failed: [TIMEOUT].

Details: { id: 'qixaasue7fd3/vxfpfgltp7sx',
  gate: false,
  ungate: true,
  desc: 'cmd:load_dojo_users,role:cd-dojos',
  cb: [Function],
  plugin: { name: 'cd-dojos', tag: '-' },
  fn: [Function: cmd_load_dojo_users],
  time: { start: 1447665768104, end: 1447665888106 },
  'orig$': { [Error: [TIMEOUT]] timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:load_dojo_users,role:cd-dojos',
  instance: 'Seneca/0.6.4/kvweoaq2fgwp/1447607504066/7056/-' }
Code: act_execute

SENECA TERMINATED at 2015-11-16T09:24:48.127Z. See above for error report.
```

At the same time we got this error in the users service:

```
Seneca Fatal Error
==================

Message: seneca: Action cmd:load_dojo_admins_for_user,role:cd-users failed: [TIMEOUT].

Code: act_execute

Details: { id: '7xl0s3kduyht/r6t2uhuw1dtz',
  gate: false,
  ungate: true,
  desc: 'cmd:load_dojo_admins_for_user,role:cd-users',
  cb: [Function],
  plugin: { name: 'cd-users', tag: '-' },
  fn: [Function: cmd_load_dojo_admins_for_user],
  time: { start: 1447665768076, end: 1447665888081 },
  'orig$': { [Error: [TIMEOUT]] timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:load_dojo_admins_for_user,role:cd-users',
  instance: 'Seneca/0.6.4/5rqjykwqp61k/1447607503972/7051/-' }

SENECA TERMINATED at 2015-11-16T09:24:48.152Z. See above for error report.
```

Hoping this will help to narrow down the issue.

**Comment by tangentfairy** [comment]
Came in just before 9am, same endpoint but different error. Leaving this here so we can monitor that it doesn't happen again after the deployment of the latest fix:

```
Seneca Fatal Error
==================

Message: seneca: Action cmd:load_dojo_admins_for_user,role:cd-users failed: Cannot read property 'id' of undefined.

Code: act_execute

Details: { id: 'qg4a4j6o4lms/kjmy30wyy1ks',
  gate: false,
  ungate: true,
  desc: 'cmd:load_dojo_admins_for_user,role:cd-users',
  cb: [Function],
  plugin: { name: 'cd-users', tag: '-' },
  fn: [Function: cmd_load_dojo_admins_for_user],
  time: { start: 1447750325357 },
  'orig$': [TypeError: Cannot read property 'id' of undefined],
  'message$': 'Cannot read property \'id\' of undefined',
  message: 'Cannot read property \'id\' of undefined',
  pattern: 'cmd:load_dojo_admins_for_user,role:cd-users',
  instance: 'Seneca/0.6.4/fqwzcxmf4cx1/1447687492012/8831/-' }

Stack: 
    at Seneca.cmd_load_dojo_admins_for_user (/opt/zen/cp-users-service/users.js:498:54)
    at Object.execspec.fn (/opt/zen/cp-users-service/node_modules/seneca/seneca.js:1720:24)
    at Object._onImmediate (/opt/zen/cp-users-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:108:14)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
```

**Comment by ckiss** [comment]
@tangentfairy Mihai logged an issue for that https://github.com/CoderDojo/community-platform/issues/797 which was fixed by my PR.

**Comment by tangentfairy** [comment]
Great! I have gotten back to a couple of users who were having problems with this before, once they confirm they can access the site I will close this.

**Comment by ckiss** [comment]
@tangentfairy this seems to be fixed now. I'm waiting to get access to that DB dump so I can test the account who still reports issues.

**Comment by tangentfairy** [comment]
Cool, we can close it when the account who still has issues is fixed.

**Comment by tangentfairy** [comment]
Although not solved with Kennan, this was resolved with a lady in Turkey causing the same errors. So we are one step closer to fully closing this issue.

**Comment by ckiss** [comment]
@tangentfairy this seems fixed by the changes made here:
https://github.com/CoderDojo/cp-zen-platform/pull/749 & https://github.com/CoderDojo/cp-users-service/pull/171

**Comment by tangentfairy** [comment]
This is solved by those changes

**Comment by tangentfairy** [comment]
This issue is finally resolved. Thank you everyone for your input and assistance. 

@kennanseno your profile is accessible again.

**Comment by tangentfairy** [comment]
This error is being caused again by the profile in this ticket: https://github.com/CoderDojo/community-platform/issues/689

```
2015-11-30T11:46:14.786Z iv9wsb28kj4y/1448871294658/3508/- ERROR	act	cd-users	OUT		cmd:load_champions_for_user,role:cd-users	330	{role:cd-users,cmd:load_champions_for_user,userId:31c1e5d2-6c9b-4adc-86ac-66b57d0449db}	ENTRY	(ioow9)	-	seneca: Action cmd:load_champions_for_user,role:cd-users callback threw: Cannot read property 'id' of undefined.	act_callback	{message:Cannot read property 'id' of undefined,pattern:cmd:load_champions_for_user,role:cd-users,instance:Sene	TypeError: Cannot read property 'id' of undefined
    at Seneca.<anonymous> (/Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/profiles.js:514:49)
    at act_done (/Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/seneca/seneca.js:1554:16)
    at /Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:127:20
    at /Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/users.js:415:16
    at /Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/async/lib/async.js:254:17
    at done (/Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/async/lib/async.js:135:19)
    at /Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/async/lib/async.js:32:16
    at Seneca.<anonymous> (/Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/async/lib/async.js:251:21)
    at act_done (/Users/ursulaclarke/cp-local-development/workspace-zen/cp-users-service/node_modules/seneca/seneca.js:1554:16)

```

**Comment by tangentfairy** [comment]
No issues since, closing!
