### ISSUE TITLE
Events section on Dojo listing

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#746]
If there are no events scheduled on a Dojo listing state "There are no events currently listed for this Dojo"

**Comment by tangentfairy** [comment]
__Technical spec__
Add a check in here https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/events/list.dust

**Comment by michaelfbradley** [comment]
I'll take this

**Comment by Arrayindex** [comment]
Almost done!!

**Comment by michaelfbradley** [comment]
:relieved:

**Comment by tangentfairy** [comment]
Sorted in https://github.com/CoderDojo/cp-zen-platform/pull/716, congrats on your first deployed change @Arrayindex !
