### ISSUE TITLE
Create separate name fields for first and last name

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#748]
Currently one full name field - splitting this would be useful for automatic emails and also for privacy on any public O13 accounts.

**Comment by josmas** [comment]
What are your thoughts on dealing with already existing data?

Users that have already signed up with full name could be prompted to split into first_name and last_name when editing their profiles, by showing the full name in the first_name field, and making last_name mandatory.

**Comment by tangentfairy** [comment]
We'd need to have a backfill script for existing data that would split this into two fields. 

The validation you suggest sounds good. This is not a priority features anyway as it is on our long term roadmap.

**Comment by josmas** [comment]
the issue with a script is how to deal with name variations if it's more than two words: 1 name + 2 surnames, or 2 names + 1 surname, or 2 names + 2 surnames, and so forth.

**Comment by tangentfairy** [comment]
Right - I think if we did this we might have to just take the last word as
the last name and all other words are for the first name. Any edge case
users would then have to update their profile of we got them incorrect!

On Sunday, December 13, 2015, Jos <notifications@github.com> wrote:

> the issue with a script is how to deal with name variations if it's more
> than two words: 1 name + 2 surnames, or 2 names + 1 surname, or 2 names + 2
> surnames, and so forth.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/748#issuecomment-164295410>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by rosalanghammer** [comment]
@DanielBrierton @Wardormeur this is done for all users now right? We still get reports of kids with only one name but I assume they are old accounts.

**Comment by DanielBrierton** [comment]
@rosalanghammer This is actually what's holding me up with the new add child page. Currently, there's only a single field for name when adding a child, so parents/guardians can put just the first name in. Handling first and last name separately has caused issues with the e2e tests, so I need to get to the bottom of that and fix them. I'm 95% sure everything still works, but I want the tests to work to confirm at least those features work.

**Comment by rosalanghammer** [comment]
Excellent - hopefully gives us less instances of community feedback. So we are good to close this when merged :)

**Comment by Wardormeur** [comment]
@DanielBrierton closing ?
