### ISSUE TITLE
tooltip texts seems to be cut off at the top in setup your dojo form

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#749]
<img width="303" alt="screen shot 2015-10-14 at 7 32 27 p m" src="https://cloud.githubusercontent.com/assets/7852866/10493834/2734b698-72ab-11e5-8966-5cadaf7e8478.png">

**Comment by tangentfairy** [comment]
__Technical spec:__
- You'll be looking for anything using `tooltip-html-unsafe` [in this file](https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/start-dojo-wizard/step-three-setup-your-dojo.dust#L34).
- The [CSS file is here](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/css/dashboard.less)

**Comment by odowdj** [comment]
<img width="671" alt="setupyourdojotooltip" src="https://cloud.githubusercontent.com/assets/13198015/13251940/2d44fcea-da2b-11e5-8061-8076c7b59bbf.png">

@tangentfairy appears to be already fixed!?!

**Comment by tangentfairy** [comment]
@odowdj I think someone fixed this at the last hackathon when they spotted it but didn't close the issue. Thanks :)
