### ISSUE TITLE
add over 13 button not has shorter height than the rest.

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#752]
<img width="1020" alt="screen shot 2015-10-15 at 1 47 02 p m" src="https://cloud.githubusercontent.com/assets/7852866/10514045/730eeff0-7343-11e5-90cf-7cc0b7c61e87.png">

**Comment by kennanseno** [comment]
fix will be up in a bit.

**Comment by tangentfairy** [comment]
Fixed thanks @kennanseno
