### ISSUE TITLE
Add ticker to all pages to show load time

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#760]
Just on the train here waiting for tabs to load and it is fairly slow... Considering that Dojos in countries with slower internet connectivity may have an issue where they think the page is not loading at all!

Can we add a ticker/loading icon in these areas:
- My Dojos, after you click manage users/manage events/anywhere data is loaded
- Events tab
- Badges tab

**Comment by tangentfairy** [comment]
Related to https://github.com/CoderDojo/community-platform/issues/398 - there is an example of a loading animation here https://github.com/CoderDojo/cp-zen-platform/search?utf8=%E2%9C%93&q=spinner

**Comment by flakyfilibuster** [comment]
Hey @tangentfairy, I'll have a look at this.

**Comment by tangentfairy** [comment]
Great stuff! :)

**Comment by Wardormeur** [comment]
:+1:
