### ISSUE TITLE
Export events attendees

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#763]
We have a feature to allow you to export the guest list for an event. Italian Dojo want to be able to export the waitlist also.

If we can have a dropdown called "Export" which when dropped down shows three options:
- Export guest list
- Export waiting list
- Export full list

![screen shot 2015-10-20 at 09 41 58](https://cloud.githubusercontent.com/assets/1136491/10602206/d54b25ac-770e-11e5-943e-2dafc5f7aecf.png)

Each of them generate a different CSV. 

__Tech spec:__
- See pull requests relating to exporting guest list [here](https://github.com/CoderDojo/cp-zen-platform/search?q=guest+list&type=Issues&utf8=%E2%9C%93) and [here](https://github.com/CoderDojo/cp-events-service/pull/62) as a good example.
- The existing endpoint could just be edited here to accept parameters, of "guest" or "waiting" so that a different filtering would be applied depending on what type of list you asked for.

**Comment by nigelhanlon** [comment]
I have submitted two pull requests which should provide this functionality if accepted. 
Not sure exactly why I can't reference them directly but here are the links:

https://github.com/CoderDojo/cp-zen-platform/pull/831
https://github.com/CoderDojo/cp-events-service/pull/100

**Comment by tangentfairy** [comment]
That's great thanks @nigelhanlon we hope to take a look as soon as possible!
