### ISSUE TITLE
Allow parents and mentors to have consolidated profile options

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#768]
I have a mentor who is also a parent and wants to add ninjas to their profile. However it looks like you can only be one profile type. Wheras you can join a Dojo as a mentor _and_ parent (based on `cd_usersdojos` table) there is only one `user_type` in the `cd_profiles` table, so you can only have a mentor or parent profile.

Can we change this so that you can have the parent features, and have the parent profile fields as well as mentor (mentors can show what programming languages they know for example).

**Comment by Wardormeur** [comment]
@DanielBrierton Should be closed?

**Comment by DanielBrierton** [comment]
Yeah, any adult can add children now, and user type in cd_profiles is actually now completely hidden.
