### ISSUE TITLE
Store capacity in database for events

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#770]
I'm not sure what the thinking was behind this, but we don't appear to store the total capacity of an event, even though we used to. It is only calculated on the front end.

This makes it very difficult for us to do statistics so can we add it back in please?

**Tech spec:**
- [See references to capacity](https://github.com/CoderDojo/cp-events-service/search?utf8=%E2%9C%93&q=capacity)

**Comment by Wardormeur** [comment]
Closing, the only usage we would have of it is for maxCapacity (https://github.com/CoderDojo/community-platform/issues/954)
