### ISSUE TITLE
Security of User profile details

### ISSUE THREAD

**Issue by noodleworm** [CoderDojo/community-platform#771]
On zen, when signing up there is little information on security. 
or even what is going to be publicly available on my profile. 

Is my phone number,email, date of birth and address all publicly viewable?

I'm not really comfortable having all those associated with my full name is a way that is potentially searchable online. 

I think that needs to be considered in order to protect users from possibly doxxings form third parties.

If it is hidden fro other users and google, this isn't being clearly indicated anywhere on the platform.

**Comment by tangentfairy** [comment]
Hi @noodleworm,

Your details are not publicly viewable. We're adding a couple of things to the system to make this clearer for users. We'll be adding a banner as in https://github.com/CoderDojo/community-platform/issues/738 and in the long term we want to have a "public profile view" similar to LinkedIn (see this issue https://github.com/CoderDojo/community-platform/issues/739).

The list of issues here is for reporting bugs and suggesting new features. If you want to open up a discussion about a potential feature or idea I would suggest using the community forums - https://forums.coderdojo.com/
