### ISSUE TITLE
Ninja (O13) Email should not be required

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#774]
Ninja O13 accounts cannot currently be created with the same email as their parent account. 

Advise to remove requirement for email and make it clear with a note that this is the Ninjas email not the parents.

**Comment by tangentfairy** [comment]
O13 ninjas are allowed to have an account separate to their parents so the one issue with this is that the foundation will have no way to contact the owner of the account if we don't require an email address (because they are not required to have a parent account attached to them at present).

**Comment by rosalanghammer** [comment]
So then is there any way for those under a parent account either to;
a) have the same email as their parent
b) not be required to have an email

**Comment by tangentfairy** [comment]
Yep we can do either or both :)

**Comment by hippyjim** [comment]
+1 for if a parent is creating the O13 account it could be automatically linked - and not need an email.

We've had a few instances of parents attempting to add an account for their O13, and getting the nick_exists error because they're using their own email address. Not requiring one would avoid this.

**Comment by tangentfairy** [comment]
Yep, we're definitely going to do this. On the nick exists error, that will be made clearer in https://github.com/CoderDojo/community-platform/issues/877f

Thanks for the input Jim, feel free to join [the Gitter chat](https://gitter.im/CoderDojo?utm_source=share-link&utm_medium=link&utm_campaign=share-link)! :)

**Comment by Wardormeur** [comment]
Dup of https://github.com/CoderDojo/community-platform/issues/822
