### ISSUE TITLE
Homepage map not showing dojos

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#776]
This is due to the new api endpoint being updated to 2.0. Have to update the homepage to match.

**Comment by tangentfairy** [comment]
Need to update this https://github.com/CoderDojo/coderdojo-dot-com/blob/master/dojo-proxy.php#L2 to 2.0 on the server. The repo is not set up to pull from Github (that is just for reference). So it will need to be updated there. CC @BenChapman

**Comment by BenChapman** [comment]
Change completed

**Comment by tangentfairy** [comment]
Thank you!

On Thursday, October 29, 2015, Ben Chapman <notifications@github.com> wrote:

> Change completed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/776#issuecomment-152294870>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.
