### ISSUE TITLE
Only update Dojo URL when dojo name or location is changed

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#779]
We have someone who wanted their URL changed to something specific which we granted.

The problem is that whenever he edits the listing it changes back to something with a "1" on the end.

If we can change this so that the Dojo URL is only updated when the Dojo name or location is changed that would be perfect.

**Comment by BenChapman** [comment]
Perhaps the name shouldn't change that easily? Unless we're redirecting old ones, then it's going to negatively affect people bookmarking and Google indexing Dojos.

**Comment by tangentfairy** [comment]
True, originally we were going to require that Dojos request the url to be
changed but it seemed this would require support beyond capacity. Ideally
we could also have some sort of redirect enabled when the url is changed.

On Sunday, November 8, 2015, Ben Chapman <notifications@github.com> wrote:

> Perhaps the name shouldn't change that easily? Unless we're redirecting
> old ones, then it's going to negatively affect people bookmarking and
> Google indexing Dojos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/779#issuecomment-154814306>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by niccokunzmann** [comment]
Short URLs
---------------

Ideally I would like something like

    http://coderdojo.com/ballsbridge → https://zen.coderdojo.com/dashboard/dojo/ie/cpl-8-percy-place-ballsbridge-co-dublin/ballsbridge-dublin-4-cpl

But I can understand that routing might be a problem. Thus one could add a special character at the beginning that would be in no other route, such as `-`.

    http://coderdojo.com/-ballsbridge

Or a new URL auch as 

    http://coderdojos.com/ballsbridge

One could also route like this

    http://coderdojo.com/-ballsbridge → http://zen.coderdojo.com/-ballsbridge → https://zen.coderdojo.com/dashboard/dojo/ie/cpl-8-percy-place-ballsbridge-co-dublin/ballsbridge-dublin-4-cpl

Conflicts
------------
A concern was that dojos could fight about short urls. 

I do not think that this will be the case. One should clarify that a short URL should not change and be most unique to the dojo and close to the name. Thus URLs like 'London' or 'Dublin' would be avoided if there exist many dojos already.

The Problem would arise when there is one dojo in a town and another comes after this. Since the dojos know each other they can handle it.

**Comment by tangentfairy** [comment]
Cool, if no one has any objections then I think we can implement short URLs.

However routing from coderdojo.com to zen.coderdojo.com will not be easy, as zen.coderdojo.com is currently on a different hosting service. I would suggest that we would just use zen.coderdojo.com

If we use one character, I think it might be a good idea to have it within it's own section of the url, e.g. zen.coderdojo.com/d/ballsbridge because it will be easier to technically implement.

Happy to see a volunteer take on this task, although it is not the highest priority of the Foundation at the moment. Am happy to help with testing of the feature and advice on implementation.

**Comment by rosalanghammer** [comment]
This is not just an issue for custom URLs but seems to be occurring for every Dojo - even if you do not actually edit anything in the listing. 

e.g. Start URL = https://zen.coderdojo.com/dashboard/dojo/ie/dublin/dublin/dublin-docklands-chq 
If you click edit (listing) then save - New URL = https://zen.coderdojo.com/dashboard/dojo/ie/dublin/dublin/dublin-docklands-chq-1
Then click edit then save a further time and you go back to the original URL without the -1.

Problematic if Dojos are sharing out their Dojo URL but making changes from week to week.

**Comment by rekado** [comment]
This also affects our new Dojo in Berlin.  We have registered a shorter domain to forward to the zen page, but the URL keeps changing.  It would be great if we could have simple numeric ids for verfied Dojos or if a Dojo's zen page could be accessed via its long alphanumeric Dojo id.

**Comment by BenChapman** [comment]
Once this is deployed the URL should no longer change on save, unless there is a change to the information used for the slug (country code, administrative area, place name, dojo name).

**Comment by BenChapman** [comment]
This is now deployed. Any Dojos left with the "-1" on the end of their URL can remove it by updating their Dojo, and the "-1" shouldn't reappear on save after that.

**Comment by niccokunzmann** [comment]
Thanks! @BenChapman
