### ISSUE TITLE
Error when trying to go to profile from event popup

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#784]
I think this could be related to https://github.com/CoderDojo/community-platform/issues/745 but making a separate issue anyway

Log in as a parent, go to a Dojo with a live event and click on book. Then click on the link that says "You must add them to your profile first" to add ninjas to your profile.

The link is broken and you get a timeout error. See screenshot.

![screen shot 2015-11-09 at 16 48 14](https://cloud.githubusercontent.com/assets/1136491/11040059/6e5e74da-8702-11e5-824d-ede484720e20.png)

**Comment by ckiss** [comment]
This seems to be fixed now.

**Comment by tangentfairy** [comment]
Appears to be fixed, although we have lost some functionality, which is now covered in https://github.com/CoderDojo/community-platform/issues/805
