### ISSUE TITLE
Error when registering from Dojo listing

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#785]
Steps to reproduce:
- Search for a Dojo that has existing events
- Go to Dojo listing page
- Click on book (I'm not logged in)
- You are brought to registration page.
- Fill in details for a parent with an existing email

You get an error about not being able to load the Dojo listing (after the error to tell you this username already exists).

It works fine for a non existing user.

![screen shot 2015-11-10 at 12 32 37](https://cloud.githubusercontent.com/assets/1136491/11062575/dd1fb9b0-87a7-11e5-8b78-7cbc24bec736.png)

**Comment by rosalanghammer** [comment]
Now redirected to login or register so closing.
