### ISSUE TITLE
Update text request in badging

### ISSUE THREAD

**Issue by LauraCDF** [CoderDojo/community-platform#787]
Please change the text that says "Are you sure you want to award this badge to" to "Are you sure you want to award this badge to the below Ninja?"

Suits better for translation purposes

![capture](https://cloud.githubusercontent.com/assets/11885481/11069914/9da710c0-87d0-11e5-825c-97181d750e4d.PNG)
.

**Comment by tangentfairy** [comment]
__Technical spec:__

[You'll need to update the template here](https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/manage-dojo-users.dust#L75). You'll need to display the name of the person on a separate line.

Then you can remove the string from [the translations file](https://github.com/CoderDojo/cp-zen-platform/blob/6d923582ecc2ebf46126f09f598bb29c84e69aa7/web/locale/en_US/messages.po#L1225) and add the new string that Laura suggested.

**Comment by tangentfairy** [comment]
This is live @LauraCDF!
