### ISSUE TITLE
Add field to edit Dojo page to display frequency of how often Dojo typically runs

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#789]
Request from Foundation team to add a field called "Frequency Dojo runs" with three options: weekly, biweekly and monthly. This will let users know how often a Dojo runs and in the long term we'll be able to search and filter by this option.

Will be a required field.

**Comment by rosalanghammer** [comment]
@adhorrig you have added this if I am correct?

**Comment by adhorrig** [comment]
@rosalanghammer yes, however it was a duplicate! there is an open pull request for it by @josmas.

**Comment by Wardormeur** [comment]
Yep, didn't merged it yet, will do after a review

**Comment by Wardormeur** [comment]
This has been covered through SAD
