### ISSUE TITLE
Account inactivity

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#79]
See FR-2.130:

```After x months of inactivity users are notified that their account will become inactive after X days.  Account is added to list to be reviewed by champion and champion is emailed. If no action the account is marked as inactive.```

Let's set this to 3 months.

**Comment by tangentfairy** [comment]
We don't do either of these as far as I know:

- Account is added to list to be reviewed by champion and champion is emailed. 
- If no action the account is marked as inactive. (i.e. marked inactive in database).

So I'll reopen this as a backlog item.

**Comment by Wardormeur** [comment]
@rosalanghammer do we really want to do this?

**Comment by Wardormeur** [comment]
Spoke with Rosa, we cancel this :)
