### ISSUE TITLE
400 bad request when loading Dojos

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#792]
I think this is due to the security changes:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "\"value\" must be an object",
    "validation": {
        "source": "payload",
        "keys": [
            "value"
        ]
    }
}
```

We need to be able to call `http://zen.coderdojo.com/api/2.0/dojos` from two places, changex.org and the coderdojo.com homepage.

**Comment by mihaidma** [comment]
Made PR for it:
https://github.com/CoderDojo/cp-zen-platform/pull/739

**Comment by tangentfairy** [comment]
Deployed
