### ISSUE TITLE
400 bad request error when starting a second dojo

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#800]
User has an existing dojo and cannot create a second dojo. 

```
{"statusCode":400,"error":"Bad Request","message":"child \"dojoLead\" fails because [child \"application\" fails because [child \"championDetails\" fails because [child \"countryName\" fails because [\"countryName\" is required]]]]","validation":{"source":"payload","keys":["dojoLead.application.championDetails.countryName"]}}
```

**Comment by mihaidma** [comment]
made PRs:
https://github.com/CoderDojo/cp-users-service/pull/172
https://github.com/CoderDojo/cp-zen-platform/pull/752

**Comment by mihaidma** [comment]
both uncomplete champion details and missing champion details should be fixed by:
https://github.com/CoderDojo/cp-zen-platform/pull/755

**Comment by tangentfairy** [comment]
All deployed now, thanks @mihaidma
