### ISSUE TITLE
Cannot create O13 ninja

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#801]
@Giustina  previously did not have the parent user type. She had it added to her account and added two U13 ninjas successfully this morning.

She tried to add a third this afternoon and when she does it tells her the profile saved successfully, except the page refreshes and says "This profile is private"

The second time I tried this on live, it just tells me that it saves successfully but doesn't actually add the ninja.

I've replicated this locally if anyone wants the dump.

**Comment by ckiss** [comment]
@tangentfairy how can someone add the parent user type to his account?

**Comment by tangentfairy** [comment]
Go to my dojo > docklands dojo > manage users and add it there

**Comment by ckiss** [comment]
thanks @tangentfairy I'll try that

**Comment by tangentfairy** [comment]
This could be related: https://github.com/CoderDojo/community-platform/issues/806

**Comment by ckiss** [comment]
@tangentfairy with the changes i've made on user load and stuff I couldn't reproduce this. (might be fixed now). Can you please check this too? Thanks

**Comment by tangentfairy** [comment]
It seems to be working now - we'll check with the user that made it happen when the user load changes are live to be sure before closing.

**Comment by tangentfairy** [comment]
This works now - @Giustina can you try creating the ninja profile again please and let us know if it is resolved for you? :)

**Comment by tangentfairy** [comment]
Confirmed we have it working now

**Comment by tangentfairy** [comment]
We figured out that there's an issue with O13 profiles where you can enter an existing email address in the system but no error is shown

**Comment by tangentfairy** [comment]
This is live and working now, thanks @ckiss
