### ISSUE TITLE
Redirect user to original page after registration

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#805]
We recently fixed https://github.com/CoderDojo/community-platform/issues/786 but before this, when you were not registered, the following flow would happen:

- Click join dojo (not logged in)
- You are brought to register
- Register account, and edit your profile
- You are redirected to the original dojo listing page so you can join the dojo and book a ticket

Now when you edit your profile you are just brought to your profile page, and it is difficult to find the original listing page where I was trying to book an event.

We need to redirect to the Dojo listing if someone was trying to join a dojo or book an event.

**Comment by tangentfairy** [comment]
This works if you are just editing your own profile, but if you are also adding ninjas you aren't redirected to the dojo listing page. It would be nice to carry the referrer through then also.

**Comment by rosalanghammer** [comment]
Closing as opting to restructure booking process as in #865 instead.
