### ISSUE TITLE
Export users to CSV

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#810]
Related to  https://github.com/CoderDojo/community-platform/issues/698 , it would be good to have a feature to export users to CSV

**Comment by tangentfairy** [comment]
__Technical spec:__
There are [two pull requests referenced here](https://github.com/CoderDojo/community-platform/issues/408) that would be a good example of how to go about this. In this case we'd need to have the backend code in the users service instead of the events service.

Make sure the endpoint is secured so that only a person with dojo admin permissions on the given dojo can access the details/endpoint.

**Comment by iamconor** [comment]
I'm working on this one

**Comment by tangentfairy** [comment]
Hi @iamconor just going to reassign this for someone else to look at
