### ISSUE TITLE
Cannot add O13 ninjas

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#814]
I think this may be related to the fixes for https://github.com/CoderDojo/community-platform/issues/800

I was logged in as a parent and attempted to add an O13 ninja to my profile, but it just brings me to a page which says "This profile is private" and does not add the ninja

**Comment by mihaidma** [comment]
The #800 changes are related to the create dojo wizard, probably not realted to this bug

**Comment by tangentfairy** [comment]
Closing in favour of https://github.com/CoderDojo/community-platform/issues/801 - same bug
