### ISSUE TITLE
Event tickets: add functionality for startdate of "ticket sales"

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#818]
Hello, because we have too many kids who want to participate, we open ticket sales via eventbrite always on a Sunday at 10 o'clock for the dojo of the next month. This way anyone has the same chance to get a ticket and they can not "block" reservations by reserving tickets for all the events of the year at once.

So in my opinion a real needed improvement of the ticketing system...

**Comment by tangentfairy** [comment]
Hi @FDelporte! We already have this featured [logged here](https://github.com/CoderDojo/community-platform/issues/409).

If you can leave your call of support on that issue it will help us to move it from the Long Term Roadmap to the Short Term Roadmap!

I'll close this issue as it is a duplicate.
