### ISSUE TITLE
Change wording for CrowdIn issues

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#820]
See https://crowdin.com/translate/zen-community-platform/1/en-ga#336
https://crowdin.com/translate/zen-community-platform/1/en-ga#502
https://crowdin.com/translate/zen-community-platform/1/en-ga#2671
and
https://crowdin.com/translate/zen-community-platform/1/en-ga#338

**Comment by niccokunzmann** [comment]
Also: 
- https://crowdin.com/translate/zen-community-platform/1/en-de#q=Citytown
- https://crowdin.com/translate/zen-community-platform/1/en-de#197

**Comment by tangentfairy** [comment]
Also look at https://github.com/CoderDojo/community-platform/issues/844
https://github.com/CoderDojo/community-platform/issues/843
https://github.com/CoderDojo/community-platform/issues/842

**Comment by tangentfairy** [comment]
And this! https://crowdin.com/translate/zen-community-platform/1/en-de#3361

**Comment by niccokunzmann** [comment]
These three entries are not translated:
1. ![event-translation-error3](https://cloud.githubusercontent.com/assets/564768/11919875/313149d0-a75e-11e5-8e4f-dd8271d32193.PNG)
2. ![event-translation-error2](https://cloud.githubusercontent.com/assets/564768/11919876/3136bf82-a75e-11e5-9533-ac0557a29781.PNG)
3. ![event-translation-error](https://cloud.githubusercontent.com/assets/564768/11919877/3136c19e-a75e-11e5-8a88-e54e658c4d4a.PNG)

**Comment by niccokunzmann** [comment]
- "Open, come along" is not translated. It should be "Open, just show up" or vise versa.

**Comment by tangentfairy** [comment]
https://crowdin.com/translate/zen-community-platform/1/en-nl#430 Could be worded better

**Comment by tangentfairy** [comment]
Badges tab doesn't look to be fully added to this file.

**Comment by DoubleYouEl** [comment]
This is not translated + should be integrated into the sentence at the "..."
![image](https://cloud.githubusercontent.com/assets/11661560/12645877/34985b76-c5cd-11e5-9333-d0c3e0794333.png)

**Comment by niccokunzmann** [comment]
This was fully merged into 934. Please close if you had a look aver it and comment anything further in 934 where it can be assigned a checkbox.
