### ISSUE TITLE
Add note beside O13 email requirement

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#823]
Due to the confusion of https://github.com/CoderDojo/community-platform/issues/822 

Add a note beside the O13 email address field suggesting that if you have a gmail address you can use the + feature (e.g. info+child1@coderdojo.org)

**Comment by kennanseno** [comment]
@tangentfairy Can I get an exact text to be added on this? Not sure how to explain the + feature myself. haha

**Comment by tangentfairy** [comment]
Sure: "If you do not wish to create a separate Over 13 email, you may use the [plus feature](http://gmailblog.blogspot.ie/2008/03/2-hidden-ways-to-get-more-from-your.html) if you have a gmail account. e.g. if your email is test@gmail.com you can use test+over13@gmail.com".

Stylewise, it can look like the info icon beside the user type dropdown on the registration page.

**Comment by flakyfilibuster** [comment]
hey there @tangentfairy,
I could have a look at this - maybe you can point me towards the proper file?

Cheers

**Comment by Aryess** [comment]
You could like to an external article such as this one: http://gmailblog.blogspot.ie/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by rosalanghammer** [comment]
Closing as once #822 is deployed this will not be necessary. cc @Wardormeur
