### ISSUE TITLE
Inactive Dojos still appear on List of Dojos

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#824]
Inactive Dojos are appearing on the list of Dojos but they do not appear on the map when searching.

Inactive Dojos should not appear on either list or map.

**Comment by tangentfairy** [comment]
Example: https://zen.coderdojo.com/dashboard/dojo/gb/london-hackspace-laboratory-24-units-23-andamp-24-cremer-business-centre-37-cremer-street-london-e2-8hd/london-hackspace-london-e2-8hd-1

**Comment by tangentfairy** [comment]
This is fixed and live now @rosalanghammer - thanks to @josmas! :)
