### ISSUE TITLE
Field in Form Needs to Change

### ISSUE THREAD

**Issue by rossoneill** [CoderDojo/community-platform#825]
This field exists somewhere in a form possibly when registering as a champion.

The language of this field needs to change as Champions just submit a provisional date of when there first Dojo session might happen. The field is I believe mean't to be populated with the Dojos schedule (Day & Time of Dojo) either weekly, monthly etc.

Proposed change of field: "Day & Time of your Dojo (e.g. Once a Week, 1pm - 3pm on Saturdays)

![screen shot 2015-12-01 at 2 31 11 p m](https://cloud.githubusercontent.com/assets/15870361/11503435/81f05864-9838-11e5-93b0-dbd038fd0987.png)

**Comment by tangentfairy** [comment]
Was a bit of confusion about this, turns out no wording change required.
