### ISSUE TITLE
Fix Intercom created date

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#827]
Intercom contact noticed that the signed up date and last seen date are the same for our users on Intercom.

"This is because the created_at timestamp should be the signed up date for the user, not the current timestamp. I think you are sending is the current timestamp here."

![intercomscreen](https://cloud.githubusercontent.com/assets/1136491/11556969/f3c6ad84-99a1-11e5-92dd-bc59d5d54372.png)

**Comment by petecoderdojo** [comment]
See Carmelo comes in as a new addition on intercom here:
![screen shot 2015-12-07 at 11 22 17](https://cloud.githubusercontent.com/assets/10957621/11625722/f3ec6fde-9cd4-11e5-8f50-b9bff6e7595e.png)

See below that Carmelos has been registered for 3 months and is not new. It is taking the data from the last time they logged in:
![screen shot 2015-12-07 at 11 22 26](https://cloud.githubusercontent.com/assets/10957621/11625750/35c618ec-9cd5-11e5-98bf-8230fd3920bc.png)

**Comment by tangentfairy** [comment]
@petecoderdojo this is fixed now, tested and deployed. Congratulations on your first PR, @josmas! :)
