### ISSUE TITLE
Locate automatically - http://zen.coderdojo.com/

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#828]
**Context**
When you are an http://zen.coderdojo.com/, you are asked to enter your location.
**Problem**
1. This may not be necessary. 
2. I do not know what to enter: Town, Village, Country, Street. Is it to find close dojos or will it exclude some that are further but better reachable?
**Solution**
Zoom in automatically to the probable location of the viewer, showing at least one dojo.
**Implementation Hint**
One can locate people by IP-address or by GPS or the location JavaScript API in the browser.
- http://ngxingyu.github.io/GCI/geo.html ([from fossasia & google code-in](https://codein.withgoogle.com/dashboard/task-instances/5058098905481216/?sp-page=1))
- http://www.w3schools.com/html/html5_geolocation.asp ([from fossasia & google code-in](https://codein.withgoogle.com/dashboard/task-instances/5058098905481216/?sp-page=1))

**Comment by tangentfairy** [comment]
Good idea, happy for a volunteer to implement this :+1:

**Comment by DanielBrierton** [comment]
This has since been implemented using the JavaScript Geolocation API, so I'm closing this issue.
