### ISSUE TITLE
Allow opening several dojos in dojo list - http://zen.coderdojo.com/

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#830]
**Context**
I am on http://zen.coderdojo.com/, clicked the list tab and want to view several dojos (e.g. to read about all of them and decide where to go/which one is next/...).
**Problem**
I want to open several dojos at once. To do this I need to open so many new tabs with http://zen.coderdojo.com/, for each tab, click on the list, scroll down and click on the dojo.
**Solution**
Allow opening several dojos from one list. 
**Implementation Hint**
Make the dojo entries links with an href attribute. Example:

    <a href="http://zen.coderdojo.com/dojo/be/turnhout/turnhout-1">Turnhout</a>

Instead of 

    <a class="pointer ng-binding" ng-click="viewDojo(dojo)">Turnhout</a>

**Comment by tangentfairy** [comment]
Thank you for the feature suggestion - this will be covered in https://github.com/CoderDojo/community-platform/issues/194 so I'll close this issue.
