### ISSUE TITLE
Refactor filter query on map page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#831]
It should be possible to filter this in the query rather than looping through the dojos and checking stage !== 4

https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/dojos-map-controller.js#L29

**Comment by mirceaalexandru** [comment]
postgres version 0.8.3 now supports:

ne$: .list$({ f1: {ne$: v1} }) for not-equal.
eq$: .list$({ f1: {eq$: v1} }) for equal.
lte$: .list$({ f1: {lte$: 5} }) for less than or equal.
lt$: .list$({ f1: {lt$: 5} }) for less than.
gte$: .list$({ f1: {gte$: 5} }) for greater than or equal.
gt$: .list$({ f1: {gt$: 5} }) for greater than.
in$: .list$({ f1: {in$: [10, 20]} }) for in. in$ operator accepts only values of type array.
nin$: .list$({ f1: {nin$: ['v1', 'v2']} }) for not-in. nin$ operator accepts only values of type array.

Note: you can use any operators described above together.

Another change was that sort$ was fixed. To be consistent with the other seneca store the sort order was reversed.

**Comment by mirceaalexandru** [comment]
Version bump to 1.0.0

**Comment by Wardormeur** [comment]
Closing, the map has been reworked
