### ISSUE TITLE
Awarded Badges not displaying on my profile

### ISSUE THREAD

**Issue by petecoderdojo** [CoderDojo/community-platform#835]
Mentor Badge has been awarded to you mail :) On a side note may need to make that badge image smaller.

![screen shot 2015-12-08 at 16 00 39](https://cloud.githubusercontent.com/assets/10957621/11660488/3d397b14-9dc5-11e5-941b-fb0b1ad704ab.png)

But it is not displayed on my profile :(
<img width="605" alt="screen shot 2015-12-08 at 16 06 06" src="https://cloud.githubusercontent.com/assets/10957621/11660564/9e130d38-9dc5-11e5-9a4b-2d0f207dfb17.png">

**Comment by tangentfairy** [comment]
False alarm
