### ISSUE TITLE
[Bug] Events disappeared

### ISSUE THREAD

**Issue by neonimo** [CoderDojo/community-platform#838]
Greystones Dojo. 

Added a multi-day event a couple of weeks back.
Added another today, saved it

Both events disappeared - got an "object not found" error box.

**Comment by tangentfairy** [comment]
Hi @neonimo - I cannot reproduce this issue - can you contact our support team on info@coderdojo.org with details and screenshots please?

**Comment by tangentfairy** [comment]
Waiting for more information, will reopen when we can confirm the issue.
