### ISSUE TITLE
Update Postgres plugin to 1.0.0

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#839]
According to https://github.com/CoderDojo/community-platform/issues/831#issuecomment-164456907
There is a list of additional features that the postgres plugin we are using now supports.

However, the ordering for sort has changed. If we want to upgrade we will need to change this. The old version was: `sort ascending = -1` and `sort descending = 1`

The new version is the reverse.

For example, [this](https://github.com/CoderDojo/cp-zen-platform/blob/a11b4ed127de658f83da69140438b71221817d58/web/public/js/controllers/user-events-controller.js#L16) will now be 1 and [this](https://github.com/CoderDojo/cp-zen-platform/blob/ad81b12eb9c77b5a1686ba4c4d05fc33d78e741a/web/public/js/controllers/dojo-events-list-controller.js#L48) will now be -1. 

[Not too many places this needs to be changed.](https://github.com/CoderDojo/cp-zen-platform/search?p=1&q=sort&utf8=%E2%9C%93)

**Comment by ckiss** [comment]
Check the other services too for places where sort is used and reverse the order

**Comment by tangentfairy** [comment]
Couldn't see anything in the other services, but worth rechecking.

**Comment by josmas** [comment]
I'm happy to work on this if no one's already started. @tangentfairy can you assign it to me?

**Comment by tangentfairy** [comment]
Sure thing!

**Comment by tangentfairy** [comment]
Tested, deployed and working beautifully! Thanks @josmas!
