### ISSUE TITLE
Cannot log in from 404 page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#840]
See screenshot, clicking on login link does nothing, and there is an error in the console.

I was coming from a non-existent dojo listing page

![screen shot 2015-12-15 at 11 11 03](https://cloud.githubusercontent.com/assets/1136491/11809142/b562942a-a31c-11e5-95a4-5997f4dead7f.png)

**Comment by DanielBrierton** [comment]
This is no longer an issue with our new menu bar.
