### ISSUE TITLE
Translation forgotten - PASSWORD

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#842]
PASSWORD and EMAIL is not translated to the German PASSWORT and E-MAIL, see the picture below or [crowdin](https://crowdin.com/translate/zen-community-platform/1/en-de#q=password).

![password not translated](https://cloud.githubusercontent.com/assets/564768/11827618/e51383ac-a38d-11e5-909a-3235116499a7.PNG)

It works under https://zen.coderdojo.com/register - it can be copied.

**Comment by tangentfairy** [comment]
Merging into https://github.com/CoderDojo/community-platform/issues/820
