### ISSUE TITLE
Translation forgotten - user types

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#843]
On a dojo page, the user types for joining are not translated. See the image below and [crowdin](https://crowdin.com/translate/zen-community-platform/1/en-de#q=Parent%2FGuardian).

![user types not translated](https://cloud.githubusercontent.com/assets/564768/11827657/325d4918-a38e-11e5-970a-7a92d15db52c.PNG)

Appearances
- https://zen.coderdojo.com/dojo/861
- https://zen.coderdojo.com/register

**Comment by tangentfairy** [comment]
Merging into https://github.com/CoderDojo/community-platform/issues/820
