### ISSUE TITLE
Redirection of Dojo Listing to Profile page. 

### ISSUE THREAD

**Issue by speciousstream9** [CoderDojo/community-platform#846]
When a Champion/Parent/Volunteer/Ninja Profile is incomplete, when looking for a dojo in the "Find Dojo" Section. It automatically redirects to the profile. Sometimes issuing a prompt to complete the profile before continuing. 

Does not happen when you are not logged in and viewing the "Find a Dojo" as normal. 

<img width="960" alt="build" src="https://cloud.githubusercontent.com/assets/10137754/11845368/7ad9d7f6-a40b-11e5-8826-566e427ec444.PNG">

**Comment by yannart** [comment]
Sent a pull request on cp-zen-platform repo.

**Comment by tangentfairy** [comment]
This is live now, thanks @yannart ! :)
