### ISSUE TITLE
Formatting on badge and events data

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#847]
For some reason, we seem to have some strange json formatting in the database in a couple of places.

Here's an example from the dates field on the `cd_events` table: `{"{\"startTime\":\"2015-09-23T18:00:00.083Z\",\"endTime\":\"2015-09-23T19:30:00.083Z\"}"}`
As opposed to this value in the city field: `{"toponymName":"Dublin"}`

The other field that needs to be cleaned up is the `badges` field on the `cd_profiles` table

```
{"{\"id\":43,\"slug\":\"mentor-badge\",\"name\":\"Mentor Badge\",\"strapline\":\"This Badge is awarded to CoderDojo community members who share their coding knowledge with others by Mentoring at CoderDojo.\",\"earnerDescription\":\"This badge signifies that you want to make the world a better place by sharing your knowledge with others by Mentoring at a CoderDojo in your local community.\\r\\n\\r\\nTo apply: You are eligible for this badge once you've Mentored at two CoderDojo sessions or approximately 4 hours of Mentoring time at your Dojo. You can request this badge from your CoderDojo champion.\",\"consumerDescription\":\"The owner of this badge has chosen to share their coding knowledge with others by Mentoring at their CoderDojo. This is no easy task and they have excelled! By sharing their coding knowledge they are showing others that coding is a force to change the world!\",\"issuerUrl\":\"https://coderdojo.com/\",\"rubricUrl\":\"\",\"timeValue\":4,\"timeUnits\":\"hours\",\"limit\":0,\"unique\":0,\"created\":\"2015-12-01T14:44:01.000Z\",\"imageUrl\":\"http://badgekit.coderdojo.com:80/images/badge/50\",\"type\":\"Skill\",\"archived\":false,\"system\":{\"id\":1,\"slug\":\"coderdojo\",\"url\":\"http://52.17.20.218\",\"name\":\"CoderDojo\",\"email\":null,\"imageUrl\":null,\"issuers\":[]},\"criteriaUrl\":\"http://badgekit.coderdojo.com:80/system/coderdojo/badge/mentor-badge/criteria\",\"criteria\":[{\"id\":37,\"description\":\"The awardee of this badge has to have Mentored at two CoderDojo sessions or approximately 4 hours of Mentoring time.\",\"required\":1,\"note\":\"\"}],\"alignments\":[],\"evidenceType\":null,\"categories\":[\"Community Action\",\"Coding and Gaming\"],\"tags\":[{\"id\":145,\"value\":\"soft-skills\"},{\"id\":146,\"value\":\"Mentor\"}],\"milestones\":[],\"$$hashKey\":\"object:80\",\"status\":\"accepted\",\"dateAccepted\":\"2015-12-08T16:11:37.035Z\",\"assertion\":{\"uid\":\"coderdojo-9c9ed75a-660f-4a2e-a92e-f267c161c34d43\",\"recipient\":{\"identity\":\"pete@coderdojo.org\",\"type\":\"email\",\"hashed\":false},\"badge\":\"http://badgekit.coderdojo.com:8080/public/systems/coderdojo/badges/mentor-badge\",\"verify\":{\"url\":\"https://zen.coderdojo.com/api/1.0/verify_badge/9c9ed75a-660f-4a2e-a92e-f267c161c34d/43/assertion\",\"type\":\"hosted\"},\"issuedOn\":\"2015-12-08T16:11:37.035Z\"}}"}
```

The way these fields are formatted is restricting us in the way we do statistics so we need to sort this out ASAP!

__Tech spec:__
- [Badge is accepted here](https://github.com/CoderDojo/cp-badges-service/blob/98612bdf6f71ecc18389c4cf009f05fc7de84632/lib/accept-badge.js) and [in the frontend here](https://github.com/CoderDojo/cp-zen-platform/blob/6975d3e45378cf1d569ee8eb95ca18591c97bd0b/web/public/js/controllers/accept-badge-controller.js)
- How to add a badge: as the administrator, go to My Dojos > Manage Users and award the badge. mailtrap.io settings to accept the badge link can be gotten from me. 
- [Saving of event is here on frontend](https://github.com/CoderDojo/cp-zen-platform/search?utf8=%E2%9C%93&q=saveevent) and [here on the backend](https://github.com/CoderDojo/cp-events-service/blob/2b60103c322421ad6d68ee5d1738f1e98dcac7c2/lib/save-event.js)
- Compare this to the way the city is saved

**Comment by josmas** [comment]
I've also seen this in the sys_user table (from seneca-user) for the field join_requests: `{"{\"id\":\"E1gZK1EBg\",\"dojoId\":\"df8ec5d1-f3f9-11e4-910d-080027c336f0\",\"userType\":\"champion\",\"time
stamp\":\"2015-12-11T16:29:19.711Z\"}"}`

It's in my local dev DB, so it might be just a glitch, but no idea how it got there.

**Comment by tangentfairy** [comment]
That's right, it seems to be another field that needs tidying up!

**Comment by mcdonnelldean** [comment]
@geek We need to have a look at this, are we creating bad data?

**Comment by mirceaalexandru** [comment]
Can you please add a test to let me see the way you are using the store?

Take a look here for some basic tests.

https://github.com/mirceaalexandru/seneca-postgres-store/blob/dev/test/postgres.test.js#L358

**Comment by ckiss** [comment]
I'm looking at this

**Comment by tangentfairy** [comment]
Thanks @ckiss - as far as I know @adhorrig has a backfill script almost completed. He's in the Foundation Slack if you need to chat to him about it.

**Comment by ckiss** [comment]
I don't think one is needed. I'll run some tests myself, but the thing is the difference between those two fields is that one is `json` and the other one is `json []` and I believe that's the way psql stores the json[] internally(I'll check this pretty soon). 

How are you reading this data when you're doing statistics?

**Comment by tangentfairy** [comment]
@ckiss string replace all the things or ilike - very nasty :)

**Comment by ckiss** [comment]
@tangentfairy from my testing it looks like I was right, the difference between those two fields is that city is of type `json` and dates is of type `json[]` and the way the data is stored in postgres is that. To demonstrate that I created a test db with a table which has two fields(json and jsona) of those two types, and inserted some that into the table straight from pgAdmin, no seneca or anything else used. In the attached ss below you can see how the data is stored internally. 
<img width="1215" alt="screen shot 2016-02-17 at 3 22 22 pm" src="https://cloud.githubusercontent.com/assets/1004239/13110724/5d5bf1fe-d58a-11e5-8d01-5e904841e008.png">

Considering this, I would say a script to backfill the data it won't work or even if it does it will just mess with the whole DB.

Can you please let me know what tool are you using to do statistics? I think it should have some option to read from json[] postgres field type. If you are trying to do a select on that json[] it will just return a string I believe. Here are some tools psql provides to read data from json and json[] field types http://www.postgresql.org/docs/9.4/static/functions-json.html

**Comment by tangentfairy** [comment]
Little bit of a misinterpretation here while @adhorrig was investigating, we're all sorted now, and @ckiss will write a script if he has time, but I'll be working on the SQL for it within the next week.
