### ISSUE TITLE
Clone end to end repository when setting up cp-local-dev

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#849]
It would be great if the cp-local-development script could also clone the [end to end tests repository](https://github.com/CoderDojo/cp-e2e-tests) and install it. 

We also need to add some docs about unit testing - a unit testing doc in this repository would be great, which can cover the unit tests for each individual microservices plus an intro to the end to end tests.

**Comment by tangentfairy** [comment]
We also need to get cp-e2e-tests running on the pre-commit hook for cp-zen-platform.

**Comment by niccokunzmann** [comment]
Working on it.

**Comment by niccokunzmann** [comment]
I put the adding of the docs about testin into another issue: #851.

**Comment by Wardormeur** [comment]
E2E repo is deprecated in favor for front-end integration tests
https://github.com/CoderDojo/cp-zen-frontend/tree/master/test/e2e
