### ISSUE TITLE
Dojo attendance requires booking but this is not true

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#852]
When I open https://zen.coderdojo.com/dojo/861
I find the text 
> Booking is required to attend this Dojo. Please contact the Dojo administrator if no events are listed.
So I expect a checkbutton in the [Dojo-Edit view](https://zen.coderdojo.com/dashboard/edit-dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a) to be present, so I can remove this.

![booking-required](https://cloud.githubusercontent.com/assets/564768/11918119/631d194a-a724-11e5-96cb-fa4731751cee.PNG)

**Comment by josmas** [comment]
Hey @niccokunzmann not sure I understand this. Does the dojo need registration Or is it open? Can you change the *current stage* field in **Status Messages** when you edit it? If you set it to *open*, the message should go away. Or am I missing something?

**Comment by niccokunzmann** [comment]
Thanks. Somehow this field was checked wrongly, I did not do it.
