### ISSUE TITLE
Mentors needed moved to bottom

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#853]
The mentors needed field moved down on the dojo view. I think this is very important so it should be top 
in the page. Also, the "open, come along" text moved to the bottom.

[![mentors moved down](https://cloud.githubusercontent.com/assets/564768/11918131/052474ae-a725-11e5-9e6c-449af7a88105.PNG)](https://zen.coderdojo.com/dojo/861)

**Comment by kennanseno** [comment]
yep. this is pretty hard to see especially when viewing in a phone/tablet. I think it would be more suitable to place it above or below the contact section?

**Comment by tangentfairy** [comment]
It was put here by the request of @rosalanghammer so it'd be up to her to move it back up the page :)

**Comment by rosalanghammer** [comment]
Agree it looks strange here where the notes are long. I would move it up but keep it below the contact section.

However I would keep the 'Open...' one as is. There is another option for this box when a Dojo is not Open which is 'Booking is required to attend this Dojo. Please contact the Dojo administrator if no events are listed.' so it wouldn't make sense to have it down below Events.

Having both the 'Need Mentors' and 'Open Come Along' section below the contact section would be my preferred solution. Open to any other thoughts though?

**Comment by tangentfairy** [comment]
Okay, action here is to move the "Mentors needed" and "open, come along" boxes up to just below the contact section.

**Comment by tangentfairy** [comment]
Completed last week
