### ISSUE TITLE
HTML escape not working for dojo status

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#854]
Looking at https://zen.coderdojo.com/dashboard/edit-dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a in German,
the status is not correctly shown:
![current state - escaping bug](https://cloud.githubusercontent.com/assets/564768/11918216/f59b13e6-a727-11e5-938e-95ac9f29590f.PNG)

**Comment by josmas** [comment]
I can reproduce. The same fix that applies to the Portuguese translation issues also clears this one up. Still on review though: https://github.com/CoderDojo/cp-zen-platform/pull/782

**Comment by tangentfairy** [comment]
This works now, thanks @josmas! :)
