### ISSUE TITLE
Event Ticket Type missing

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#855]
There is a ticket type missing when translated to German.
![event-ticket-type](https://cloud.githubusercontent.com/assets/564768/11919854/d00571c2-a75d-11e5-8fd3-b9f2b194bf33.PNG)

Website: https://zen.coderdojo.com/dashboard/dojo/0be123e7-c9be-4002-a3cf-f0c8550f749a/event-form/cdebe884-caa8-46f7-9e1f-d7581049a855

**Comment by Wardormeur** [comment]
Hey @niccokunzmann, is this still happening?
I've tried with a couple of languages and when the languages had no translations, it was using the english word.
Was the issue that a translation was pulled (and existing) and the value was being empty ?

**Comment by Wardormeur** [comment]
Doesn't seem to happen anymore, closing off
