### ISSUE TITLE
Discussion about recurring events

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#857]
**Context**
My workflow for the CoderDojo Potsdam is to copy events because the recurring thing is nothing I understand. Events usally take place every two weeks but sometimes they do not take place, sometimes it is one week more or less in between.
**Suggestion**
1. My first suggestion is to create a copy functionality of an event to duplicate it so one can change the date.

---
**Context**
What I do not understand is the recurring functionality but I like to use it because my dojo is not only once. What if it takes place at the second Saturday in months? What if every 3rd day of a month? What if at full moon? What if we as a platform can not know how often and when it occurs? What if every three weeks but not on holidays? Did you do a study to find out that 1 or 2 weeks is 80% of what is needed?
**Suggestion**
1. Do not use the "recurring -> scheme" way of characterizing this. If somebody creates this event he or she has the time to add the dates explicitly. 

---
**Context**
Eventbrite also has a recurring event form that is similar to this.

**Comment by tangentfairy** [comment]
Hi @niccokunzmann - would the implementation of this feature help your issue?
https://github.com/CoderDojo/community-platform/issues/665

On the second suggestion, I think we need to have an in-depth discussion about what you'd expect, as I'm not sure what the feature request is here. It sounds like something that would need a detailed wireframe.

**Comment by niccokunzmann** [comment]
@tangentfairy This would help.

**Comment by tangentfairy** [comment]
I think we can close this if issue #665 will help you - on the second part, maybe opening a discussion on the forum would be useful?

**Comment by niccokunzmann** [comment]
That helps me. We can move the discussion to a forum.
