### ISSUE TITLE
Charter Error

### ISSUE THREAD

**Issue by speciousstream9** [CoderDojo/community-platform#858]
Dojo has already signed the charter but Zen. Has not hit Salesforce either. 

![chartererror1](https://cloud.githubusercontent.com/assets/10137754/11932360/d6b54508-a7ec-11e5-84fa-03176455eec9.png)
![charter error 2](https://cloud.githubusercontent.com/assets/10137754/11932361/d7dd17d0-a7ec-11e5-8178-450dc0472bb1.png)

**Comment by tangentfairy** [comment]
@speciousstream9 I'm unsure of the error you are reporting - is it that the user has signed the charter but it did not show as being signed in the management backend?

**Comment by tangentfairy** [comment]
Any update on this @speciousstream9 ?

**Comment by rosalanghammer** [comment]
No reoccurrence. Closing!
