### ISSUE TITLE
Invite all feature for events

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#864]
We want to add a feature where in the events section you can invite all in the events section, and it will send an email to all members of a Dojo notifying them that there is a new event live on the Dojo.

Wireframe to follow.

**Comment by rumasingh8** [comment]
This will be very helpful as we are currently sending out a separate email from our gmail account to all our members once we publish the event. Thanks!

**Comment by Giustina** [comment]
Its definitely the feature I want most for our Dojo :)

**Comment by hippyjim** [comment]
If implementing this (which I desperately need as it takes ages picking the right users for the right ticket types otherwise) - could we look at matching invite ticket types to member/user types - e.g parents to a parent ticket, ninjas to a ninja ticket etc.

**Comment by rosalanghammer** [comment]
@hippyjim we plan on this being a notifier so you do not have to pick which category to match and the user will self identify!

**Comment by rosalanghammer** [comment]
Also suggested by Liam Friel, Bray Dojo, was a 'Leave Dojo' option at the bottom of this notification email. I think this would be super useful so members can easily navigate and self exclude themselves when they leave a Dojo!

**Comment by Wardormeur** [comment]
:+1:
