### ISSUE TITLE
Book event ticket process

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#865]
New wireframes have been completed for the book a ticket process in the events section.

This is a priority to complete in Q1/Q2

https://docs.google.com/document/d/1OzQDYeckRw_j_MghLCSBmlsLdbbnKz_rLGHQZAugONc/edit

**Comment by Wardormeur** [comment]
Fixd in https://github.com/CoderDojo/cp-zen-platform/commit/90cf5e8d4ec8a9eaa86919bd9985796001e015dc
