### ISSUE TITLE
Links to Charter & privacy statement broken when logged in

### ISSUE THREAD

**Issue by kennanseno** [CoderDojo/community-platform#866]
Charter link in nav and privacy statement link in footer seems to break when a user is logged in but works  fine when no one is logged in. 

1. Log in your account in zen
2. Click privacy statement - will give 404
3. Click charter - will go to https://zen.coderdojo.com/undefined

if you skip step 2, charter works fine even when logged in.

**Comment by Wardormeur** [comment]
@tangentfairy This should be closed isn't it? :)

**Comment by tangentfairy** [comment]
@Wardormeur - nope, privacy statement is still broken when logged in. Charter link was fixed.

**Comment by machineperson** [comment]
I'm really sorry about this, I wanted to fix this after the community hackathon, but work has been super busy and it just dropped off my radar. If someone else wants to have a look at this, please go ahead.

**Comment by tangentfairy** [comment]
No worries, thanks @machineperson ! Will clear the assignee for now :)
