### ISSUE TITLE
Log In Errors. 

### ISSUE THREAD

**Issue by speciousstream9** [CoderDojo/community-platform#873]
![log in issue](https://cloud.githubusercontent.com/assets/10137754/12231190/7d648560-b84d-11e5-9c8b-bf19f4969a27.PNG)

This error occurs upon trying to log in. When clicking the top Log in bar, no error is displayed & doesn't move to the login screen but in the console log you get an error about resolving logins. 

This is fixed by doing a hard refresh.

**Comment by kennanseno** [comment]
I remember we had this issue before.

https://github.com/CoderDojo/community-platform/issues/500

**Comment by speciousstream9** [comment]
I'm on Chrome, the latest version, though a hard refresh does fix the error, just I'm not too sure what's causing it.

**Comment by speciousstream9** [comment]
Please note this should be specified for Zen Log in only

**Comment by kennanseno** [comment]
@speciousstream9  i'd say a service was down at that time like what is said in the old issue. next time you get this error, please check if there's a deploy on-going so we can be sure if that really is that cause or not. You can check it in the zen-alert channel in slack.

**Comment by rosalanghammer** [comment]
Closing - will reopen if happens again.
