### ISSUE TITLE
Add parent type automatically if Mentor/Champion adds Ninja

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#874]
Following a discussion with @tangentfairy it would be super useful if mentors/champions get auto-assigned the parent user type as well once they 'Add Ninja' to their profile. 

Otherwise this has to be done manually by Champion/Dojo Admin.

**Comment by Aryess** [comment]
@tangentfairy Can you assign this one to me please? :)

**Comment by rosalanghammer** [comment]
@Wardormeur Can this be amalgamated in as part of #865 - though this is a more LT change to registration & profile?

**Comment by Wardormeur** [comment]
Yes
