### ISSUE TITLE
community-platform development chat

### ISSUE THREAD

**Issue by raboof** [CoderDojo/community-platform#875]
Is there a chat available somewhere to discuss community-platform development? For example gitter, irc or slack?

**Comment by tangentfairy** [comment]
@raboof send me a mail on ursula@coderdojo.org and I'll get you added to the Slack channel. There's a Gitter too which I'll get added to the docs https://gitter.im/CoderDojo?utm_source=share-link&utm_medium=link&utm_campaign=share-link
