### ISSUE TITLE
Users cancelling tickets

### ISSUE THREAD

**Issue by speciousstream9** [CoderDojo/community-platform#876]
Feature request for when a Parent is unable to attend an event, that it is possible for the parent to delete the Ticket for the Event. 

Ideally, this would be done through links in the confirmation email which you receive when you book a ticket. A line at the bottom which would state the Following :

"If you are unable to attend this event, please click this link to Cancel your booking"

Clicking the link would bring you to a page which would say: 

"Thank you for confirming you will not be in attendance; your ticket has now been canceled."

**Comment by tangentfairy** [comment]
@johnbrett For more information on creating test data, [see this doc](https://github.com/CoderDojo/community-platform/blob/master/creating-test-data.md). The main (readme file is here)[https://github.com/CoderDojo/community-platform/blob/master/README.md]. 

- [Cancel backend logic is here](https://github.com/CoderDojo/cp-events-- service/blob/cc15412e8e8bd3be4e8b91c69ea03a3f6198bb34/lib/cancel-session.js)
- You'll probably need a frontend controller [like this invite one](https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/accept-dojo-user-request-controller.js) for the new cancel link page
- [Here is where an application is cancelled](https://github.com/CoderDojo/cp-events-service/blob/cc15412e8e8bd3be4e8b91c69ea03a3f6198bb34/lib/cancel-session.js#L104) if the champion is doing it through the manage event page.

Let me know if you have any questions, usually around on the [Gitter](https://gitter.im/CoderDojo/community-platform?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)!

**Comment by johnbrett** [comment]
@tangentfairy Thanks for the extra info. I'm up and running with the platform and able to manage dojos and events locally but emails don't seem to be sending. Should they work out of the box or do I require any extra config/setup?

**Comment by tangentfairy** [comment]
I've sent you a direct email with access to our mailtrap.io account!

On 30 January 2016 at 10:48, John Brett <notifications@github.com> wrote:

> @tangentfairy <https://github.com/tangentfairy> Thanks for the extra
> info. I'm up and running with the platform and able to manage dojos and
> events locally but emails don't seem to be sending. Should they work out of
> the box or do I require any extra config/setup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/876#issuecomment-177145469>
> .
>



-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by johnbrett** [comment]
Perfect - thanks for the quick reply :)

**Comment by tangentfairy** [comment]
This is live now, thanks very much @johnbrett

**Comment by johnbrett** [comment]
Awesome! Glad to help!
