### ISSUE TITLE
Friendlier error when attempting to enter a used alias

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#877]
The error that appears when you enter an alias that already exists is "nick-exists" which is not very user friendly.

We need it to say "The alias you have chosen is already taken. Please enter a new, unique alias."

**Comment by flakyfilibuster** [comment]
hey @tangentfairy,
when you say alias, do you mean the selected username on registration? 

Sorry, if this seems like a redundant question, but the platform is quite extensive and I haven't seen all pages so far.

I get this message - maybe you can point me to the correct url.


![screen shot 2016-01-18 at 8 29 53 am](https://cloud.githubusercontent.com/assets/2176610/12385574/ed604fbe-bdbd-11e5-96ee-8b1ace02895d.png)


Cheers

**Comment by tangentfairy** [comment]
@flakyfilibuster This is when you are registering, but also when you are editing your profile and adding a child account. When you are logged in and click on your name, you can go to "add ninja over 13" from here. In there you need to add an alias for your child. 

It is [here on the register page](https://github.com/CoderDojo/cp-zen-platform/blob/b555f3c9207fab7d2bd33a0b793429e6b968f648/web/public/js/controllers/login-controller.js#L143) so this needs to be copied to where the youth is added to an account.

I think the error might [come back here](https://github.com/CoderDojo/cp-zen-platform/blob/3bc01054c6380ff5cd96135c80f13b84a254fd49/web/public/js/controllers/user-profile-controller.js#L280) but isn't specifically dealt with at the moment.

**Comment by flakyfilibuster** [comment]
@tangentfairy I replaced the error message on the registration form with the string you provided above.

However, I'm not able to reproduce the error on the parent profile page (maybe I need another type of account?).

I'm able to add an arbitrary amount of youth (over and under 13) accounts and even have them occupy the same name/ aliases. Please see attached screenshots.

![screen shot 2016-01-19 at 7 35 35 am](https://cloud.githubusercontent.com/assets/2176610/12411464/4c49f43c-be7f-11e5-9401-818ac995721c.png)

![screen shot 2016-01-19 at 7 35 49 am](https://cloud.githubusercontent.com/assets/2176610/12411467/51eaf1c0-be7f-11e5-88b1-30b946989d2c.png)


As you can see, the account has 3 linked child accounts all with the name and alias 'jane' :S

Maybe this warrants an additional bug? 


Cheers

**Comment by Aryess** [comment]
![screenshot from 2016-01-23 13-12-00](https://cloud.githubusercontent.com/assets/3518172/12530299/f1d8050a-c1d2-11e5-97cf-7b6771aabd55.png)
Confirm the error.

**Comment by Aryess** [comment]
![screenshot from 2016-01-23 13-34-13](https://cloud.githubusercontent.com/assets/3518172/12530392/08826fa4-c1d6-11e5-88e3-e10bc2c10363.png)
Tadaaa. PR on the way

**Comment by tangentfairy** [comment]
Fixed, thanks @Aryess !
