### ISSUE TITLE
Access for parents to Forum

### ISSUE THREAD

**Issue by speciousstream9** [CoderDojo/community-platform#878]
As of build of Zen 75 is the frontend build number at the moment, dojos service is at 15
Chome version :  47.0.2526.106 m

If a parent type account tries to access the form they get the following error. 
![parent access](https://cloud.githubusercontent.com/assets/10137754/12327402/41811472-bace-11e5-9a75-c5c3d3e304a8.PNG)

Add access to forums for parents

**Comment by tangentfairy** [comment]
Chatted to Rosa about this - because parents don't have to be validated to join a dojo or use the system, we are going to leave this as is.

If a parent wants to access the forum they can have the "mentor" user type added to their profile in manage users by the dojo champion.
