### ISSUE TITLE
Delete ticket application error

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#881]
When cancelling a ticket application, I see the blue bar strapline appear, but no error appears

![screen shot 2016-01-19 at 11 03 08](https://cloud.githubusercontent.com/assets/1136491/12416929/66c6195e-be9c-11e5-8fd0-1ef004fb92ba.png)

**Comment by andresiglesias** [comment]
This is only happening when the attendee has been approved for the event.

**Comment by tangentfairy** [comment]
Thanks for the update @andresiglesias !

**Comment by andresiglesias** [comment]
What we want to show in the blue bar is "'Attendee name' has been successfully deleted" isn't it?

**Comment by tangentfairy** [comment]
"Ticket for 'Attendee name' has been successfully cancelled" :)

**Comment by andresiglesias** [comment]
> "Ticket for 'Attendee name' has been successfully cancelled" :)

:+1:

**Comment by tangentfairy** [comment]
This is live now, thanks @andresiglesias !
