### ISSUE TITLE
Ticket application email

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#882]
When automatic approval for tickets has been turned on:
- we need an email to be sent to the dojo email and champion email notifying them when a new application for a ticket has been logged

Otherwise the champion has no idea when this has happened or that they need to approve a ticket.

**Comment by tangentfairy** [comment]
For more information on creating test data, [see this doc](https://github.com/CoderDojo/community-platform/blob/master/creating-test-data.md). The main [readme file is here](https://github.com/CoderDojo/community-platform/blob/master/README.md). 

- Test that this email does _not_ send when the ticket approval is turned off in an event
- [Take a look here](https://github.com/CoderDojo/cp-events-service/blob/cc15412e8e8bd3be4e8b91c69ea03a3f6198bb34/lib/bulk-apply-applications.js#L170) for where to send the email - we want to send it to the owner of the dojo, _as well as_ the dojo email to notify them that someone has booked a ticket. This is where the email is sent to the user so it can be done at the same time. The champions email will be in the `sys_user` table under `email` and the dojo email is in `cd_dojos` under `email`. It looks like the dojo data is already loaded in this code.

Let me know if you have any questions, usually around on the [Gitter](https://gitter.im/CoderDojo/community-platform?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)!

**Comment by DanielBrierton** [comment]
This should be an optional feature. Not all admins will want to receive emails for each booking. A checkbox should be added to enable/disable the sending of emails.

**Comment by Wardormeur** [comment]
Thanks a lot to all of you @danburke @grabartley @campbs :+1:
