### ISSUE TITLE
Search existing tickets booked by name

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#883]
It would be great to add a search feature in each event to search the applicants by name. There is already a filter for ticket type but we need something more specific.

If we could also have the applicants sortable by name (a little arrow beside attendee name) that would be useful too.

**Comment by tangentfairy** [comment]
Beside "select ticket type..." which does the filtering by ticket type, add a "Search by name" textbox which will automatically filter the list (will start filtering after you type three characters).

![screen shot 2016-01-21 at 16 17 13](https://cloud.githubusercontent.com/assets/1136491/12486419/96622990-c05a-11e5-8c55-1f22f5cb6317.png)

Instructions for creating an event:
- As the manager@example.com default user, you can go to "start a dojo" and go through the steps. Then you can approve yourself by going to "manage dojos", ticking "verify" and applying the changes.
- Then you can go to "my dojos" > "manage events" under your dojo to create a new event.
- Once the event is created you can click on "manage" beside the event in the manage events screen.

Let me know if you have any questions @wardormeur!

**Comment by Wardormeur** [comment]
Thanks :+1:

**Comment by Wardormeur** [comment]
Maybe could we merge the attending label with this search one.
Certainly, "attending" by itself is an indicator of how many places are available, but it could be displayed as "[input label=attending] (1/4)"; (1) being the validated user while 4 being the max. Being a bootstrap base, a badge could be appropriate. 
However i don't include the waitlist in this display and can probably be thought a bit more.
Stick to plan A or think about B ? :)

**Comment by tangentfairy** [comment]
@Wardormeur It needs to be like the invite dojo members functionality, where the list is refined as you type. 

I'm not sure what you mean by merging the attending label - the labels listed can stay as they are, accept you can have a little arrow beside attendee to sort the list (like we do on manage dojos). Does that make sense? Happy to have a Skype to walk through further, would be easier than on Github :)

**Comment by Wardormeur** [comment]
The remarks regarding the labels where more likely to understand what's more important to display, either the amount of free places or how successful your communication is (how many users registered for it).
To display it in a x out of y (5/10) sounded like a fastest way for the user to understand the information than to have to process the information by himself
Just saying :)

**Comment by tangentfairy** [comment]
This is live now, many thanks @Wardormeur !
