### ISSUE TITLE
Add timezones to Events 

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#889]
All event times are being inputted in GMT by default and there are no options to change this. 

This is problematic as the event gets removed at the date & GMT time on the event rather than local time, particularly in American timezones which are behind GMT meaning the event gets removed too early.

The quick fix for this would be for events to only remove +10 hours after the event but in the long term we will want a drop down or ability to add custom timezones by the user when creating the event.

**Comment by niccokunzmann** [comment]
I think, usually the time zone should default to the event's location. The closing of the event should adapt to this. I think adding a field to change the time zone of the event would be useful in 0.1% of the cases and much more harmful. The event has a location and the location determines the time zone.

**Comment by rosalanghammer** [comment]
Yes this is also a good option and probably preferable. Was suggested by
@tangentfairy earlier too :)

On 22 January 2016 at 17:10, Nicco Kunzmann <notifications@github.com>
wrote:

> I think, usually the time zone should default to the event's location. The
> closing of the event should adapt to this. I think adding a field to change
> the time zone of the event would be useful in 0.1% of the cases and much
> more harmful. The event has a location and the location determines the time
> zone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/889#issuecomment-173980560>
> .
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by rumasingh8** [comment]
Thank you for opening up this issue. It would make most sense for the time zone to default to event's location as suggested above. Can this be done quickly enough?

**Comment by tangentfairy** [comment]
@rumasingh8 I don't think it would be an issue, the only thing is that we'd probably just do this for new events. If a volunteer takes this on it is a middle sized task, dependant on experience.

**Comment by rumasingh8** [comment]
By new events you mean events that will be created after the bug is fixed?

**Comment by tangentfairy** [comment]
Yes - we could have a backfill script to fix the old ones but the priority
is to fix the new ones.

On Sunday, January 24, 2016, rumasingh8 <notifications@github.com> wrote:

> By new events you mean events that will be created after the bug is fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/889#issuecomment-174249172>
> .
>


-- 
Ursula Clarke Everett
Technical Lead @ CoderDojo Foundation
S: tangentfairy | T: @CoderDojo | @tangentfairy

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by rumasingh8** [comment]
sounds good to me!

**Comment by tangentfairy** [comment]
Deployed a temporary fix for this but we need the timezones sorted out other than this. 

I have other fires to fight so will unassign this for a volunteer to take a look at.

**Comment by DanielBrierton** [comment]
As events are super local, and don't span timezones, we've deemed it unnecessary to actually store timezones. Instead, we ensure the time input is the time that displays when viewing, regardless of which timezone you're in. Closing.
