### ISSUE TITLE
Optional Tao Text Boxes to be required once tickbox checked

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#891]
Once ticked the checkboxes under CoderDojo Tao e.g. 'Set up Background Checking for all Mentors' all have a drop down text box so Champions can justify how their Dojo is meeting the condition.

Once a checkbox for Tao is checked it must be required that they fill out this textbox to prove they are completing the step. This requirement needs to be added so you cannot move past the page without adding this justification.

**Comment by rosalanghammer** [comment]
@adhorrig is there any update on this? I know you were looking at requirements on this page recently.

**Comment by adhorrig** [comment]
@rosalanghammer still open, i made the page more user-friendly but never submitted a pr for it

**Comment by rosalanghammer** [comment]
@DanielBrierton if we are rebuilding Tao this can be closed. If we are just going to build upon the neverending checkbox page then it needs to remain as this is still a requirement for Tao.

**Comment by Wardormeur** [comment]
Closing, Tao is being reworked apart from the Start a Dojo process
