### ISSUE TITLE
Checking in for recurring events is slow

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#894]
Report from Tramore dojo that when they have many dates it takes a long time to check someone in.

They have dates set up of 16th January til 12th March, 3 pages of attendees on one session, and 5 sessions.

Loading the dates for check in seems to be slow and could be improved.

**Comment by Wardormeur** [comment]
I think I'll need a bit more info to narrow it down.
Is this then 20+ events, each having 5 sessions of regularly 1 page attending ppl?
Do we agree this is related to the action to check-in or to the action of displaying the list of users/sessions (and then not related to the event whatsoever)?

**Comment by Wardormeur** [comment]
It seems to be a lib related issue(https://github.com/dotansimha/angularjs-dropdown-multiselect/issues/45) (no extra call done on the API side), trying to find a workaround as the lib sound not really maintained

**Comment by tangentfairy** [comment]
Perfectly fixed now, thanks @Wardormeur ! :)
