### ISSUE TITLE
Redesign of Zen landing page

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#897]
It has been suggested to redesign the landing page to include some information on the right of the page that details the feature of the community platform.

This can be done in tandem with the redesign of the navigation bar. The map would be smaller and we'd remove the tabs and move the "list" to a smaller link.

**Comment by Wardormeur** [comment]
There has been a discussion regarding landing page, to make it more specific of a dashboard according to your user type, and more appealing regarding when not logged-in, likely having nearest upcoming events or newest awarded badges.

**Comment by Wardormeur** [comment]
"No dojo found" seems to be hard to find, we should probably come up with something more visible.

**Comment by Wardormeur** [comment]
As per https://forums.coderdojo.com/topic/311/search-function-for-dojo-listings-on-zen we should probably add the possibility to filter on "Looking for mentors" in a way you can easily look for a dojo.
However I feel like @rosalanghammer was considering this was a non-status as you're generally always looking for more mentors. Am I right ?

**Comment by rosalanghammer** [comment]
Yeah everyone is looking for mentors but they can choose not to tick if they want but it's good to get this forum feedback. I think the point on days and time is definitely a searchable item that both parents and mentors would appreciate.

Here is a previous mockup - can be viewed in both list and map form. https://projects.invisionapp.com/share/RA7971JJQ#/screens/157278849 

My concern would be that both day and time are free text fields that may be hard to search and not kept up to date. We could maybe implement something in advance which would make these non-free text before we take on the larger issue of redesigning the map.

**Comment by rosalanghammer** [comment]
An addition to this mockup would be private vs public - with default on private listings not showing up unless selected specifically on the sidebar. 

Some confusion now with private dojos on the map and current list.

**Comment by Wardormeur** [comment]
Performance concern : https://github.com/CoderDojo/community-platform/issues/1025

**Comment by Wardormeur** [comment]
May I close @rosalanghammer @DanielBrierton ?

**Comment by Wardormeur** [comment]
The homepage has been reworked to show more relevant information (find a dojo/ dojo events/ content/ news) when you're registred. If you're not, the classic "Find a Dojo" page is there to guide you through a normal registration flow with value (booking).
Closing for the time being
