### ISSUE TITLE
Menu bar does not work in Microsoft Edge browser

### ISSUE THREAD

**Issue by kurtdevocht** [CoderDojo/community-platform#900]
The menu bar does not work in Microsoft's Edge browser (Windows 10) - Buttons are not recognized as links.

![28-01-2016 8-16-59](https://cloud.githubusercontent.com/assets/3392982/12637697/910c39b2-c597-11e5-9df8-86c4164f27a7.png)

**Comment by tangentfairy** [comment]
Had @speciousstream9 test it and she says it is slightly off but not non-functional. So it sounds like we need to tweak the CSS slightly for IE - make sure that it is using floats correctly etc :)

**Comment by DanielBrierton** [comment]
We've since reworked the entire menu bar across our site, so this should no longer be an issue.
