### ISSUE TITLE
Awarded Badges not appearing on profiles

### ISSUE THREAD

**Issue by petecoderdojo** [CoderDojo/community-platform#901]
Awarded Badges are not appearing on user profiles. See below for details.

![badges issue](https://cloud.githubusercontent.com/assets/10957621/12646525/8b39b18c-c5c8-11e5-871b-693215d3773d.gif)

**Comment by tangentfairy** [comment]
This is happening on my profile: I have more than one badge in the `cd_profiles` table under my user id, but only one is showing up on my profile.

**Comment by tangentfairy** [comment]
Fixed this last week
