### ISSUE TITLE
Preselect user type and dojo when join dojo is selected

### ISSUE THREAD

**Issue by bazkennedy** [CoderDojo/community-platform#903]
I noticed an issue on the dojo's page that when you select a role (eg Mentor/Volunteer) and click join dojo
![image](https://cloud.githubusercontent.com/assets/2617738/12721020/7fa21c26-c8f5-11e5-8a44-e7a761e32242.png)

When you go to the next page you have to select your role again, making this first step redundant
![image](https://cloud.githubusercontent.com/assets/2617738/12721042/9ddf86ce-c8f5-11e5-81ac-22177f91607d.png)

Ideally this selection should be carried across and pre-filled on the form

**Comment by bazkennedy** [comment]
Just an update on this. The dojo is also not carried through, That means that anyone who tries to join a dojo has to go back in and join the dojo after they've created an account. This isn't very intuitive and as a result there could be new ninjas/parents who have registered for zen but aren't assigned to their dojo.

**Comment by Wardormeur** [comment]
Hey, sorry for coming back to you so late 
So basically the registration is missing a pre-selection of the dojo you want to join, am i right ?

**Comment by bazkennedy** [comment]
Pre-selection of the role and the dojo. The dojo is the important one as its not so clear that you have to go back and join a dojo after you create an account. I wonder how many users have been left unassigned due to this.

**Comment by rosalanghammer** [comment]
For the pre-selection of Dojo, wireframe could be similar to not logged in user flow for Events as in #865. i.e. no redirection to register.

Also +1 on preselecting user type - would definitely help bypass confusion for parents. Would work with #874 as mentors could automatically join as both parents & mentors.

**Comment by Wardormeur** [comment]
user-type is merged, post-registration dojo subscription left to be done :+1:

**Comment by Wardormeur** [comment]
@DanielBrierton to be closed?

**Comment by DanielBrierton** [comment]
@Wardormeur Yeah, no longer makes sense since you don't select a user type when registering.
