### ISSUE TITLE
Alphabetic order of country dojo's not correct

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#904]
Hello, just noticed my own dojo is the last on the Belgian list ;-)

http://zen.coderdojo.com/dashboard/dojo-list > List > Belgium

Ieper is last and not in correct alphabetic order.
Mistake by me while editing or in the code?

**Comment by tangentfairy** [comment]
@FDelporte I'm willing to bet this is something to do with "leper" being in lowercase. We can update the sorting to be case insensitive, but in the meantime you could update it to be uppercase and it would likely be in order. Thanks for the report!

**Comment by FDelporte** [comment]
nope, is uppercase in the editor...
the other one I can edit "Roeselare" is correct in the list

**Comment by tangentfairy** [comment]
In the database it is lowercase, and on the listing. I updated it to be "Leper" uppercase and it appeared correctly alphabetically in the list. We still need to fix the case sensitive issue so this can stay open :)
