### ISSUE TITLE
Improvement of dojo list: show number per country + collapse

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#905]
http://zen.coderdojo.com/dashboard/dojo-list > list

is now a very long page.
idea to improve:
- next to the country name show number of dojos
- make the country name clickable to expand/collapse the dojos in this country
- by default all countries collapsed

**Comment by tangentfairy** [comment]
Happy for a volunteer to take this on!

**Comment by tangentfairy** [comment]
I would suggest that the dojos in each countries not be loaded until the country is expanded also. It loads the entire list at once at the moment.

**Comment by Wardormeur** [comment]
This page doesn't exist anymore :)
