### ISSUE TITLE
MIME type issue while running the app locally

### ISSUE THREAD

**Issue by vikashvverma** [CoderDojo/community-platform#908]
I am getting following error after running the app locally:

<img width="1440" alt="screen shot 2016-02-05 at 11 49 20 pm" src="https://cloud.githubusercontent.com/assets/915277/12855078/6d07001a-cc63-11e5-9dc4-668d58b30126.png">

Is there any extra configuration required?

**Comment by niccokunzmann** [comment]
think that has to do with 404 pages. They are 200 pages with the 404 content. 
#870 #836

**Comment by vikashvverma** [comment]
@niccokunzmann I'm getting this when I'm trying to access localhost:8000.

**Comment by tangentfairy** [comment]
@vikashvverma Are you seeing the map and the page itself with these errors? I seem to remember seeing this when all the node modules didn't install properly. Try rm -rf the node_modules directory in cp-zen-platform and npm install again. You can also try reinstalling the bower components by rm -rf bower components in the web directory and then install again. [This is in our troubleshooting doc.](https://github.com/CoderDojo/cp-local-development/blob/master/troubleshooting.md)

**Comment by vikashvverma** [comment]
@tangentfairy I'm still getting some errors. Markers in map are not visible.

<img width="1439" alt="screen shot 2016-02-06 at 5 57 34 pm" src="https://cloud.githubusercontent.com/assets/915277/12866645/5334d110-ccfb-11e5-92f9-4170a2fa9151.png">

**Comment by tangentfairy** [comment]
@vikashvverma Can you see the map at all?

**Comment by vikashvverma** [comment]
@tangentfairy I can see the map but I'm not able to login/register.

**Comment by tangentfairy** [comment]
@vikashvverma Okay, have you tried running the test data script as outlined in our docs? Join the Gitter chat if you can, then I can help you more instantly!

**Comment by tangentfairy** [comment]
@vikashvverma Let me know how you got on, please join the Gitter if you can so we can help. Will close this for now!
