### ISSUE TITLE
Ticino showing on map even though it is inactive

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#909]
Search for "Ticino" dojo in Switzerland, it doesn't show up in the list beneath the map but it does appear on the map, even though it is inactive! http://zen.coderdojo.com/dojo/ch/ticino/ticino/ticino

![screen shot 2016-02-08 at 12 37 29](https://cloud.githubusercontent.com/assets/1136491/12885805/c12a1ad4-ce60-11e5-8636-5f1d63a9a7db.png)

**Comment by orrwil** [comment]
@tangentfairy Hi, I've submitted a [pull request](https://github.com/CoderDojo/cp-zen-platform/pull/821) to fix this issue, just dawned on me that I maybe should have lifted the issue 1st, Apologies.

**Comment by tangentfairy** [comment]
Thanks @orrwil - I tested it and it works. I'm just wondering if you managed to test this locally?
I see that you have forked cp-zen-platform but not cp-local-development.

**Comment by orrwil** [comment]
@tangentfairy I'm a bit new to a lot of this so might have made a few errors along the way. I originally just cloned cp-local-development to my laptop. I did get the local setup running, although there were some errors populating the db and I had to run the script (dojos.sql) again manually.  I was able to successfully test my change locally but my commits were producing errors, that I assumed were configuration issues, so I ended up submitting the change from another computer. Hope this makes sense?

**Comment by tangentfairy** [comment]
@orrwil I see - if you still have problems then make sure to join the [Gitter](https://gitter.im/CoderDojo/community-platform?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)! Thank you for the pull request :)

**Comment by tangentfairy** [comment]
This is live now, thank you!
