### ISSUE TITLE
Platform KPI's

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#91]
Need 10 or so key KPI's for the CP Platform.

**Comment by tangentfairy** [comment]
List of existing KPI endpoints are:
Badges service:
- Number of badges awarded: /api/1.0/badges/kpi/number_of_badges_awarded
- Number of badges published: /api/1.0/badges/kpi/number_of_badges_published

Users service:
- Number of youths registered: /api/1.0/kpi/number_of_youths_registered
- Number of champions and mentors registered: /api/1.0/kpi/number_of_champions_and_mentors_registered
- Number of youth females registered: /api/1.0/kpi/number_of_youth_females_registered

So we still have to write a few. In the meantime we could make a dashboard with the existing ones.

**Comment by rosalanghammer** [comment]
Would also be good to get the country breakdown of the following;
- Badges awarded
- Youths registered
- Champions registered
- Mentors registered

Also for Dojos using ticketing features;
- Total number of Dojos using ticketing (ever)
- Total number of Dojos who have used ticketing recently (3 months)
- Total number of live events

**Comment by Wardormeur** [comment]
According to the API description, we allready have some of those, like badges awarded
GET              /api/2.0badges/kpi/number-of-badges-awarded 
  GET              /api/2.0badges/kpi/number-of-badges-published 
However probably broken regarding how the path is built :p

**Comment by Wardormeur** [comment]
Should probably be extended to data gathered from  https://github.com/CoderDojo/community-platform/issues/964

**Comment by Wardormeur** [comment]
This has been moved into our warehouse / Google Data studio for more flexibility
