### ISSUE TITLE
Sytem failure when registrater for a new account

### ISSUE THREAD

**Issue by DragonBe** [CoderDojo/community-platform#911]
Hi, I recently got invited to register an account at zen.coderdojo.com where I filled out my details. After pressing submit I received a server error.

```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

![screenshot 2016-02-15 11 04 50](https://cloud.githubusercontent.com/assets/282825/13049464/67480b24-d3ed-11e5-9764-6d98df0caaa8.png)

As the error is a server-side error, there's not much more that I can include in this bug report. No further information was provided.

**Comment by tangentfairy** [comment]
@DragonBe Could you send on the exact details you entered to info@coderdojo.org please? Also, did a second attempt fix the issue?

**Comment by tangentfairy** [comment]
Wait for more information, closing until we receive it.
