### ISSUE TITLE
Add crowdin to the footer

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#912]
**Context**

Currently in the footer, there is the text 

> Zen is an open source platform, you can contribute code and suggest features to help make it better.

This has no reference to [crowdin](https://crowdin.com/project/zen-community-platform). You can only reach crowdin of you click on "contribute code".

**Suggestion**
Add a link to crowdin so people can correct the text on the site.

**Hints**
The added text should not contain "translate" but rather "correct the text on the website" because this includes both mistakes made and missing translations as they are seen as incorrect.

**Comment by tangentfairy** [comment]
Happy for someone to do this :+1:

**Comment by sudheesh001** [comment]
I've given this a try, I would like your review @niccokunzmann and @tangentfairy

**Comment by niccokunzmann** [comment]
I like it. I do not know if the messages.po file needs an update, too.

**Comment by sudheesh001** [comment]
Ah that's right, let me fix that immediately :smile:

**Comment by sudheesh001** [comment]
@niccokunzmann I've made the required changes, could you review now and merge if its good to go

**Comment by niccokunzmann** [comment]
@sudheesh001 I cannot merge. @tangentfairy is the lead and can do that.

By the way, looking at https://github.com/sudheesh001/cp-zen-platform/blob/2f667906930664a404a14a194dcdca4184ec8955/web/locale/en_US/messages.po#L228
If it is one string in the mesages.po, it is nicer to translators. Crowdin handles links specially and the sentences do not get torn apart. 

In the past I translated but did not contribute code to zen.

**Comment by sudheesh001** [comment]
@niccokunzmann Thanks for pointing to that, i'll make a fix and rebase it again. After that i'll wait for @tangentfairy to merge :smile:
