### ISSUE TITLE
Bulk load mentors and ninja addresses

### ISSUE THREAD

**Issue by coderdojopv** [CoderDojo/community-platform#913]
We are moving from eventbrite to zen.
It has been three years since we are using eventbrite.
We have a group of 70 mentors and 300 ninja

How can we bulk load mentor or ninja addresses, associating them to our dojo?
We have to do this one by one?

We think that bulk loading (like in a group) could be useful

**Comment by tangentfairy** [comment]
Hi @coderdojopv - I think [this issue](https://github.com/CoderDojo/community-platform/issues/811) is the feature you are looking for. Please upvote it - it is on our Long Term Roadmap at the moment as we have many other priorities on our Q1/Q2 and Short Term Roadmap milestones. Thank you!
