### ISSUE TITLE
Events dates in UTC+01:00 reverting to GMT

### ISSUE THREAD

**Issue by coderdojopv** [CoderDojo/community-platform#915]
we are planning a dojo session for february 27th, that is a saturday.
I pick the 27 as day, the system register it in the field, but after I press Publish the event day keeps turning 26.
I also tried to restraint the event in the anti meridian (from 9:30 to 11:30) but nothing changes.

We are dojo 414: CoderDOjo Pavia.

Thanks for your help!

**Comment by tangentfairy** [comment]
@coderdojopv our intern @adhorrig has been working on the events dates this week and is looking into this for you.

**Comment by coderdojopv** [comment]
Thank you,
we wait to hear from you!

Laura

Mail: coderdojopv@compvter.it
WEB: coderdojo.compvter.it
http://compvter.it/index.php/coderdojo
Twitter: https://twitter.com/CoderDojoPavia
FB: facebook.it/coderdojopv

Associazione culturale comPVter <http://www.compvter.it/>
via del commercio 13, loc. Prado
<http://www.openstreetmap.org/way/318110395>,
www.compvter.it
Cura Carpignano (PV)

2016-02-18 15:40 GMT+01:00 Ursula Clarke Everett <notifications@github.com>:

**Comment by tangentfairy** [comment]
This was due to an issue caused by the fix for https://github.com/CoderDojo/community-platform/issues/889, which has been rolled back now until we come up with a solid implementation.
