### ISSUE TITLE
Most Invited mentors receive the message "Invito non valido" (invalid invite)

### ISSUE THREAD

**Issue by coderdojopv** [CoderDojo/community-platform#916]
Dear team, sorry to bother you with all this issues!

We just started usng zen ticketing system.
I sent invites to all our mentor, inserting their mail and rpressing "Invite as mentor" button

The system answered me " Invite sent"
But when a mentor press the link contained in the email the system answers with "Invalid Invite" message (see attached print screen)

A lots of mentor reported me that.

Thank you for what you will be able to do, our event is near in time and we are worried!!

Laura

![image](https://cloud.githubusercontent.com/assets/16879351/13146681/302449c0-d657-11e5-8ae1-0f952140a009.png)

**Comment by tangentfairy** [comment]
Hi Laura, could you please go through info@coderdojo.org for support issues, Github is mainly for logging confirmed bugs and new features. 

Adam can look after this request once you sort out the events issue.
