### ISSUE TITLE
Badge awarding messaging for Mentors

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#917]
When awarding a badge to a Mentor the pop up says ' Are you sure you want to award this badge to the below Ninja?'

Wording is confusing and off-putting for those trying to award to their mentors so would be good if it could recognise the user type and use Mentor where appropriate or use a generic phrase like 'Are you sure you want to award this badge to the person below?'

![screen shot 2016-02-24 at 09 36 23](https://cloud.githubusercontent.com/assets/12827424/13281215/5f0de9da-dada-11e5-87bb-4f9e9c0a3fc7.png)

**Comment by niccokunzmann** [comment]
I referenced it in 934 as it is a request to change the wording in crowdin.
