### ISSUE TITLE
where are the 7-13 users

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#922]
when people visit the dojo page they can only book a room as guardian, champion or youth over 13...
where are the "youth below 13"?

https://zen.coderdojo.com/dojo/be/vlaams-gewest/izegem/izegem-1

**Comment by rosalanghammer** [comment]
Hi,

As Youth U13 must be attached to a parent account, their parent has to join! When a parent joins their Ninjas are automatically brought across with them also.

We mainly use Github for new feature requests & issues. In future please drop us an email on info@coderdojo.org for these sort of problems :). 

Thanks,
Rosa

**Comment by skynetbbs** [comment]
Okay there is a bug in the URL to the dojo on zen
An ending -1 is added for every unecen update of the dojo fiche... Giving
error404 to people using the -1 or not -1 link
Op 2-mrt.-2016 10:42 schreef "rosalanghammer" <notifications@github.com>:

**Comment by rosalanghammer** [comment]
Hi @skynetbbs how did you generate this URL? If you could email screenshots of this URL in your browser and how you changed it that would be great.

On Zen your URL seems to still be - https://zen.coderdojo.com/dashboard/dojo/be/vlaams-gewest/izegem/izegem
