### ISSUE TITLE
Invite parent feature for Under 13's

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#923]
both parents are registered in zen...how can they both register thesame child in zen?

**Comment by rosalanghammer** [comment]
Hi there! Unfortunately at the minute there is no way for both parents to attach the same child to their profiles. The short term fix for your Dojo is for the parents to only add the child to one of their profiles and then share the log in with one another.

Going to open a 'request for comments' on this one to see if any other Dojos want this feature.

**Comment by tangentfairy** [comment]
@rosalanghammer we have an invite parent feature that allows children to invite secondary parents to their account.

**Comment by rosalanghammer** [comment]
@tangentfairy to the Rescue.

@skynetbbs My apologies - see screenshot below on how Youths can add a second parent.
![screen shot 2016-03-10 at 16 29 43](https://cloud.githubusercontent.com/assets/12827424/13676488/f761830e-e6dd-11e5-8c89-9f652e9336ab.png)

Closing as not an issue or feature req.

**Comment by skynetbbs** [comment]
can't be done with a youth under 13 so i notice?
hence this person has no own login
and invite parent is not visible


2016-03-10 17:35 GMT+01:00 rosalanghammer <notifications@github.com>:

**Comment by rosalanghammer** [comment]
@skynetbbs Under 13's cannot have logins to be compliant with COPPA legislation. (This is why you cannot sign up for email accounts/social media accounts if you are under 13). We are multi-jurisdictional so wanted to keep in line with this as it is best practice adopted by all global technology companies with  youth users.

Have re-opened this as adding parent would be useful for under 13's as well as Over 13's.

**Comment by tangentfairy** [comment]
Suggest we add the invite box on an u13 profile when viewing it from the
parents account.
