### ISSUE TITLE
children of a mentor that is member of 2 dojo's automatically is registered for 2 dojo's?

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#924]
I'm a champion of one dojo and help out in a 2nd dojo
i've added my child ninja
and if i look at his profile he's member of both dojo's...i've never taken him to the 2nd location though?

**Comment by adhorrig** [comment]
Hey @skynetbbs , thank you for bringing this up. I've just tested it and can confirm that this is the case. 
@rosalanghammer could you please tag this as "backlog" and "long term road-map".

Note - to recreate:
Be a champion of a Dojo, with Ninjas attached to your account. Apply to be a mentor at a different Dojo. Approve the request and all you will see all Ninjas are also carried over.

**Comment by tangentfairy** [comment]
This was intended behaviour - all ninjas automatically are joined to any dojos which their parents are joined to.

**Comment by Wardormeur** [comment]
As stated, this wa sthe intentional behavior, we want to simplify as much as possible for adults to carry their children along. My children page from @DanielBrierton will help managing this, should be there soon !

**Comment by DanielBrierton** [comment]
@Wardormeur My Children page is there now for managing your child's Dojos! I'm just finishing off the simplified add child form now.
