### ISSUE TITLE
can't approve an attendee

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#925]
Hi,

i've got an attendee (kylian)
i click on the "[ ]" approve... nothing happens
mother is asking if there is an issue...can her son join the next session?

my browser is Chrome Version 39.0.2171.95 
no plugins...

**Comment by rosalanghammer** [comment]
Hi there,

Can you email a screenshot please to info@coderdojo.org so we can solve?

Thanks,

Rosa

On 2 March 2016 at 11:54, skynetbbs <notifications@github.com> wrote:

> Hi,
>
> i've got an attendee (kylian)
> i click on the "[ ]" approve... nothing happens
> mother is asking if there is an issue...can her son join the next session?
>
> my browser is Chrome Version 39.0.2171.95
> no plugins...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/925>.
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by tangentfairy** [comment]
Closing until more details are received

**Comment by skynetbbs** [comment]
It seems i have To click above the checkbox. Must be an issue with the
citrix thinclient environment i work with
Op 21-mrt.-2016 21:09 schreef "Ursula Clarke Everett" <
notifications@github.com>:
