### ISSUE TITLE
[Test Data] - Unable to update Dojo Founder for existing dojo's

### ISSUE THREAD

**Issue by SlashmanX** [CoderDojo/community-platform#926]
When trying to follow [these steps](https://github.com/CoderDojo/community-platform/blob/master/creating-test-data.md#becoming-championorganiser-of-an-existing-dojo) to assign a user as founder of an existing dojo, the following error appears. This occurs for all dojo's I try to update.

```
An error has occurred while saving:: 
{"data":{"statusCode":400,"error":"Bad Request","message":"child \"dojo\" fails because [child \"dojoLeadId\" fails because [\"dojoLeadId\" must be a string, \"dojoLeadId\" must be a string]]","validation":{"source":"payload","keys":["dojo.dojoLeadId","dojo.dojoLeadId"]}},"status":400,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"url":"api/2.0/dojos/df8ec619-f3f9-11e4-910d-080027c336f0","data":"{\"dojo\":{\"entity$\":\"-/cd/dojos\",\"id\":\"df8ec619-f3f9-11e4-910d-080027c336f0\",\"mysqlDojoId\":29,\"dojoLeadId\":null,\"name\":\"Carlow\",\"creator\":\"df7401f0-f3f9-11e4-910d-080027c336f0\",\"created\":null,\"verifiedAt\":\"2013-12-01T14:25:30.000Z\",\"verifiedBy\":\"3006\",\"verified\":1,\"needMentors\":1,\"stage\":2,\"mailingList\":0,\"time\":\"Every Saturday 10:30am to 1pm\",\"country\":{\"countryName\":\"Ireland\",\"geonameId\":\"2963597\",\"alpha2\":\"IE\"},\"county\":{},\"state\":{\"toponymName\":\"Leinster\"},\"city\":{},\"place\":{\"name\":\"Carlow\",\"geonameId\":\"2965768\"},\"coordinates\":\"52.82669428900052,-6.936200398950177\",\"geoPoint\":{\"lat\":52.82669428900052,\"lon\":-6.936200398950177},\"notes\":\"......
```

The dojo edit form looks like this before editing: 
<img width="863" alt="screen shot 2016-03-07 at 08 33 09" src="https://cloud.githubusercontent.com/assets/871743/13564128/3e2905d8-e43f-11e5-8e99-6219709d6645.png">

After adding the founder:

<img width="853" alt="screen shot 2016-03-07 at 08 32 06" src="https://cloud.githubusercontent.com/assets/871743/13564126/32d2b184-e43f-11e5-83b3-b01a647d3114.png">

After clicking 'Save':
<img width="631" alt="screen shot 2016-03-07 at 08 33 37" src="https://cloud.githubusercontent.com/assets/871743/13564145/56257aa4-e43f-11e5-8dd1-4b02c0029044.png">

I have filled out the profile for the `manager@example.com` user and already created a test dojo which works ok. Is there another step I am missing?

**Comment by josmas** [comment]
It looks like a Joi error. Have a look at https://github.com/hapijs/joi

**Comment by SlashmanX** [comment]
Attaching screen recording of steps taken:

![dojo_lead_error mov](https://cloud.githubusercontent.com/assets/871743/13567194/c38bd4aa-e451-11e5-84b5-5bd36ea2e07f.gif)

**Comment by SlashmanX** [comment]
[Screen recording of error](http://streamable.com/mrr6)

**Comment by Wardormeur** [comment]
I believe it's breaking here (https://github.com/CoderDojo/cp-dojos-service/blob/master/dojos.js#L749) because we save the dojo then update the founder ( https://github.com/CoderDojo/cp-zen-platform/blob/master/web/public/js/controllers/edit-dojo-controller.js#L311)
Can't get further into debugging before this evening alas, so that editing a Founder is possibly broken

**Comment by Wardormeur** [comment]
Issue validated, there seems to have a bug in test data, however the process to create a dojo from scratch is working fine and the founder can be updated. 
In the present case, it's crashing because there is no reference to a previous Founder which is required to update to the new one.

**Comment by tangentfairy** [comment]
@Wardormeur this might happen if there's an issue with the Salesforce Lead.

**Comment by Wardormeur** [comment]
Closing as the testdata structure has been reworked some months ago in order to be handled through the microservices rather than SQL based.
