### ISSUE TITLE
dojo.setup.confirmation

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#927]
When I register myself as a Dojo Champion, I get a confirmation that says "dojo.setup.confirmation"
That should be some useful text.
![capture](https://cloud.githubusercontent.com/assets/564768/13570075/5acebd7c-e46c-11e5-9765-e9be0a655827.PNG)

**Comment by adhorrig** [comment]
Hey!

I believe that the issue is here:

https://github.com/CoderDojo/cp-zen-platform/blob/d9dc98254d3f1593fb69306c9800bc2a2daf1b2a/web/locale/en_US/messages.po#L1954

and

https://github.com/CoderDojo/cp-zen-platform/blob/cf2e0c2eaecd208b91fc1bba1e2871e8f155059b/web/public/templates/dojos/dojo-setup-confirm.dust#L6

**Comment by niccokunzmann** [comment]
@adhorrig I suggest that the id "dojo.setup.confirmation" is changed to "Are you sure you have filled out all the information correctly and wish to proceed?". This is they way it is in crowdin and would be consistent.

**Comment by adhorrig** [comment]
@niccokunzmann Thanks, I've done that here -> https://github.com/CoderDojo/cp-zen-platform/compare/master...adhorrig:i927-translate-alert-confirmation?expand=1

My local copy of Zen won't seem to change language though so I can't test it atm

**Comment by niccokunzmann** [comment]
It looks good and I think it should work.
After merge, I do not know how one would upload that to crowdin so it can be translated.

**Comment by josmas** [comment]
@adhorrig you can follow steps in https://github.com/CoderDojo/community-platform/issues/815 to test languages locally

**Comment by adhorrig** [comment]
@josmas Thanks a lot! Was looking for that information in the docs :)

**Comment by josmas** [comment]
Not sure it is 'officially' documented, but it most certainly should be! :)

**Comment by niccokunzmann** [comment]
please do not forget to click it in 934.

**Comment by tangentfairy** [comment]
Thanks @niccokunzmann
