### ISSUE TITLE
translate titles

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/community-platform#928]
When I start a new dojo, the title is not translated. Other titles could also be affected.
![capture](https://cloud.githubusercontent.com/assets/564768/13570174/eac8ed9e-e46c-11e5-95ea-8af70321475a.PNG)
URL: https://zen.coderdojo.com/dashboard/start-dojo

**Comment by tangentfairy** [comment]
@niccokunzmann there's an issue for all the oustanding translations here https://github.com/CoderDojo/community-platform/issues/820 it'd be great to consolidate these issues into that one and then @adhorrig could get them done in one swift go.

**Comment by niccokunzmann** [comment]
@tangentfairy Ok, right I understand. I will do something about it. 
@niccokunzmann

**Comment by niccokunzmann** [comment]
closing, as 934 contains it
