### ISSUE TITLE
Coolest Projects title on the forums navbar says '2015' instead of '2016'

### ISSUE THREAD

**Issue by adhorrig** [CoderDojo/community-platform#935]
See here: https://forums.coderdojo.com/

'COOLESTPROJECTS2015' in the navbar should be 'COOLESTPROJECTS2016'

cc @rosalanghammer

**Comment by EugeneMcD** [comment]
The JavaScript that is on www.coderdojo.com needs to be implemented on all other sites. It pulls the menu items from the wordpress install on www.coderdojo.com and makes it easy to manage them in one place.

**Comment by BenChapman** [comment]
Look like the "Global Menu" has been removed from all sites.

**Comment by BenChapman** [comment]
Close was accidental. Reopened

**Comment by tangentfairy** [comment]
I think it would be ideal if a configuration by a non-technical person of the nav bar was to be implemented that it pull centrally from the Zen API instead of Wordpress.

**Comment by Wardormeur** [comment]
Navbar is going to be redesigned to be global upon the whole websites ( Commercial/WP, Zen, Kata) I'm just going to quick fix this as the event is oncoming.
