### ISSUE TITLE
zen maintenance mode not shown on main page

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#936]
the login link is gone
people can't register any more activities as they are all away

by "hacking" the website (i just enter zen.coderdojo.com/admin) i notice there might be a "maintenance" mode active ?
could you make this more clear on the page that today all dojo's are not showing any bookeable events  nor allow changing / logging in?

**Comment by Wardormeur** [comment]
We've activated the maintenance mode to avoid manipulaton while we're trying to fix a critical issue
Sorry for the inconvenience :|

**Comment by BenChapman** [comment]
Currently adding the notice to all pages. Sorry for the confusion caused.

**Comment by tangentfairy** [comment]
This is live now, so closing, thanks all!

**Comment by skynetbbs** [comment]
Hi,

how long will this be down?
nobody can register anymore for Coderdojo?
Some lead coaches only just send a mail to register...others have a dojo
next weekend and nobody knows about it or can do anything :(
downtime of more than 3 days? never had this with eventbrite :(
Can't this downtime not be limited?


2016-03-14 20:05 GMT+01:00 Ursula Clarke Everett <notifications@github.com>:

**Comment by tangentfairy** [comment]
@skynetbbs I'm afraid I do not know about the downtime circumstances. @BenChapman might be able to tell you.

**Comment by BenChapman** [comment]
[This post](https://forums.coderdojo.com/topic/104/zen-under-maintenance/2) will contain any updates about the situation with the platform. Please discuss it there, so everything is in one place.
