### ISSUE TITLE
Link to Zen/Kata from coderdojo.com

### ISSUE THREAD

**Issue by dmwelch** [CoderDojo/community-platform#937]
Getting to these pages needs to be simple and straightforward to new participants, either directly from the main page or from a dojo's page (using 'Find a dojo').

**Comment by tangentfairy** [comment]
@dmwelch there is a wireframe and design for a whole new navigation bar which will be in progress as soon as we have more development resources. There will be a lot more direct links to Zen and a more obvious link to Kata in the new navbar :)
