### ISSUE TITLE
"Manage users" is empty

### ISSUE THREAD

**Issue by skynetbbs** [CoderDojo/community-platform#938]
Hi,

i'm champion of dojo "Izegem"
today I noticed that when i wanted to manage the "user" section it was empty
yesterday this was fine

the "event" managment is okay...13 resources

**Comment by rosalanghammer** [comment]
Hi @skynetbbs - Noticed that there is a delay in loading the users. Does this work after you wait for a bit?

Closing as this as is a support issue - email info[at]coderdojo.com if this continues with screenshots so we can help support.
