### ISSUE TITLE
Setting the project up locally

### ISSUE THREAD

**Issue by nerdess** [CoderDojo/community-platform#943]
I'd like to setup the project locally but I do get a 

> Postgres connection error: Error: connect ECONNREFUSED 127.0.0.1:5432

when I run ./localdev.js init zen

afaik this has sth to do with postgres/node both pointing to 127.0.0.1 but i don't know how to fix it...

**Comment by josmas** [comment]
Hi there, is _postgres_ actually running in your box? They will use the same address, that's not an issue, because they use different *ports* but it looks like postgres is either not running, or potentially being blocked by a firewall?

**Comment by nerdess** [comment]
#facepalm no postgres was not running....works all fine now :)

**Comment by josmas** [comment]
@nerdess great stuff; could you please close the issue if you are happy with the setup?
