### ISSUE TITLE
Extend data in attendee CSV list of event

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#946]
Is it possible to add parent email to the list? Would be very handy for mailing all participants a reminder some days before the Dojo...

**Comment by Wardormeur** [comment]
Wouldn't be notify users a more fitting functionnality ?

**Comment by rosalanghammer** [comment]
A customisable reminder for event attendees (as opposed to a notification
of a live event to all Dojo members), would probably be more fitting. This
way Champions could edit it to include specifics for their Dojo.

Or should be a more basic reminder email, as templated by us, for event
attendees only.

On 5 April 2016 at 15:56, Wardormeur <notifications@github.com> wrote:

> Wouldn't be notify users a more fitting functionnality ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/946#issuecomment-205844721>
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by Wardormeur** [comment]
A default template that could be customisable/editable/saved ?

**Comment by rosalanghammer** [comment]
@FDelporte You can export all users from an event (including parents) already.

Closing this as the next step to customise this would be to build #947 :)
