### ISSUE TITLE
Mailing function to all attendees of a Dojo

### ISSUE THREAD

**Issue by FDelporte** [CoderDojo/community-platform#947]
Handy feature: mailing box to send a mail to all kids and parents who subscribed for a Dojo.
Usage:
- send a reminder a few days for the Dojo
- after the Dojo easily send a mail with the links of the Scratch studio, pictures,... of that Dojo
- ...

**Comment by Wardormeur** [comment]
I think we already provide email for dojos, cc @rosalanghammer

**Comment by rosalanghammer** [comment]
No would have to be done manually through the Dojos inbox at the minute by exporting the Dojo Event list.

**Comment by Wardormeur** [comment]
This has been done around a month ago through the "Email" function on manage-users :)
