### ISSUE TITLE
Map Issue when you search fir "EGYPT"

### ISSUE THREAD

**Issue by petecoderdojo** [CoderDojo/community-platform#948]
I search for Egypt and it gives me a Dojo in Cyprus. This seems to only happen with this country at the moment.

<img width="1162" alt="screen shot 2016-04-08 at 11 49 25" src="https://cloud.githubusercontent.com/assets/10957621/14382450/c653042c-fd85-11e5-82f8-9c27cda462b2.png">

![egypt search issue](https://cloud.githubusercontent.com/assets/10957621/14382567/a624462e-fd86-11e5-8ddb-e3838a65f43a.gif)

**Comment by Wardormeur** [comment]
It may be not a bug, as if i remember well, it's supposed to return the nearest one
To be checked :)

**Comment by petecoderdojo** [comment]
I see that would make sense. You can solve then

Pete

On 8 April 2016 at 12:47, Wardormeur <notifications@github.com> wrote:

> It may be not a bug, as if i remember well, it's supposed to return the
> nearest one
> To be checked :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/948#issuecomment-207396687>
>



-- 
Pete O'Shea

Community (EMEA) and Events Lead @ the CoderDojo Foundation
<http://coderdojo.com/>
PH: +353876965019 | Skype: peter__oshea
Twitter: @*p*eter0shea <https://twitter.com/peter0shea> @CoderDojo
<http://coderdojo.com/>

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by adhorrig** [comment]
Seems to be the case, if you search for 'Angola' the map focuses to 'Loandjili, Pointe-Noire' Dojo which is in Republic of the Congo - and also the closest Dojo to Angola

**Comment by petecoderdojo** [comment]
Ok 👍

On Friday, 8 April 2016, Adam Horrigan <notifications@github.com> wrote:

> Seems to be the case, if you search for 'Angola' the map focuses to
> 'Loandjili, Pointe-Noire' Dojo which is in Republic of the Congo - and also
> the closest Dojo to Angola
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/948#issuecomment-207427222>
>


-- 
Pete O'Shea

Community (EMEA) and Events Lead @ the CoderDojo Foundation
<http://coderdojo.com/>
PH: +353876965019 | Skype: peter__oshea
Twitter: @*p*eter0shea <https://twitter.com/peter0shea> @CoderDojo
<http://coderdojo.com/>

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by niccokunzmann** [comment]
Maybe the map should also include the place where one is?

**Comment by Wardormeur** [comment]
You mean autofocus to the region where you live ?
