### ISSUE TITLE
Event edition - Address textbox modification not included on saving

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/community-platform#949]
User role: Champion
URL: https://zen.coderdojo.com/dashboard/dojo/8308d14d-dda8-49a4-b217-6d07e9f88e2d/event-form/6e9900ca-b2f4-49eb-a4e3-5bc81c5c6740

Details:
In Event edition page, modifications on Address textbox couldn't be saved.
Initially, I reported a bug because this textbox was disabled on edition time. 
Bug: https://github.com/CoderDojo/cp-zen-platform/issues/858
The disabled status was solved but this field still can not be modified. 

How reproduce it:
1) Open Chrome browser
2) "New Incognito window"
3) Login zen platform (user must be champion as role)
4) go to "My Dojos" link
5) go to "Manage" under "Events" column
6) click "Edit" in any Event
6) Event Edition form loads. Edit address textbox content.
7) Save
8) Visit Event page from a different browser/computer. Modifications weren't saved.

**Comment by Wardormeur** [comment]
Darn.. 
I'll have a look tomorrow morning, sorry

**Comment by Wardormeur** [comment]
Hopefully fixed :)
