### ISSUE TITLE
Booking Event Flow Change

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#953]
Change flow of booking so that user type can automatically be assigned if there is only one ticket you can possibly book.  e.g. Mentor or Parent (only match with the Mentor or Parent ticket type)

If there are multiple ticket types that a user can book in for either one or multiple tickets. e.g. Scratch, Hardware, Laptop. 

Allows user to clearly see what they are booking in for.

Setup would be;
Rosa (Mentor) - [Dropdown to ticket options] or [Book - if only one option]

**Comment by Wardormeur** [comment]
The idea is to reverse the display logic : instead of making it session oriented as it is atm, it should be user oriented.
This way, you easily see what you're booking for, both for yourself or your children

**Comment by ChristianVermeulen** [comment]
Most important, if you have 2 tracks and a capacity of 30 you can potentially end up with 60 ninja's.
Another possibility, and probably easy quick fix, is to be able to set a max capacity for your dojo.

This way you can have 30 tickets for each track, but close the ticketing as soon as a total of 30 have been booked.

You would also need to be able to make ticket types as `not counting` so ninja's are able to book extra things like laptops etc.

**Comment by Wardormeur** [comment]
Should this maxCapacity defaulted to a caculation based upon the number of mentor? 1 for 5 ?

**Comment by rosalanghammer** [comment]
Probably better for Champions to set capacity as they will have to take
into account Mentors and venue capacity!

On 15 April 2016 at 14:54, Wardormeur <notifications@github.com> wrote:

> Should this maxCapacity defaulted to a caculation based upon the number of
> mentor? 1 for 5 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderDojo/community-platform/issues/953#issuecomment-210471966>
>



-- 
Rosa Langhammer
Reporting Lead

@RosaLanghammer | @CoderDojo

-- 
*Volunteer at your local Dojo and inspire the next generation of digital 
creators!*

   - Pledge to start a Dojo <https://coderdojo.com/pledge-a-dojo/>
   - How to volunteer at your local CoderDojo 
   <https://coderdojo.com/get-involved/volunteer/>
   - Read the CoderDojo Foundation Strategy 
   <https://coderdojo.com/news/2015/08/07/the-coderdojo-foundation-strategy-20152016/>


-- 
Hello World Foundation operating as the CoderDojo Foundation is a company 
limited by guarantee not having a share capital with charitable status, CHY 
20812. Registered in Dublin, Ireland, No 524255. Registered Office: 
Dogpatch Labs, Unit 1, CHQ Building, Custom House Quay, Dublin 1, Ireland.

**Comment by ChristianVermeulen** [comment]
Exactly what I meant @rosalanghammer :)

**Comment by rosalanghammer** [comment]
@ChristianVermeulen have opened a new issue for this - may make the booking flow a bit more complex so would be great to get some comments on it. See #954

**Comment by Wardormeur** [comment]
Parent are now automatically booked and tickets are filtered on the kind of users you are : 
 - children -> ninja; 
 - adult mentoring -> mentor; 
 - adult accompagning -> "parent" (hidden)
