### ISSUE TITLE
Add Max Capacity to events

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#954]
Would have to find a way to set this only for Ninjas tickets. 

This may be too complex for users with each session also having capacity fields so I wouldn't just add it on without thought; would like to request comments from Champions/Mentors as to if they would use this.

**Comment by DGuiloff** [comment]
If you could set the max capacity of each ticket type (EX: for ninjas or loaner equipment) and be able to leave them at infinite (EX: for parents) while others have a max, that would be ideal. Would need to be able to easily modify this even after the event is created. Max ninja levels may increase with additional mentors/volunteers registered.

Champions/Ticket Admins would need a way to be proactively notified when max capacities are almost and fully reached (maybe they can get more equipment or volunteers and increase the capacity of ticket types).

**Comment by Wardormeur** [comment]
@rosalanghammer related to waiting list, am i right ?

**Comment by rosalanghammer** [comment]
Correct. Plan is now for waiting list to activate and then Dojo admins can easily add additional spaces from the waiting list (over capacity) with a trigger message 'Are you sure you want to add more tickets to this event - Current bookings X' 'Yes/No'

Too difficult to implement a ratio system based on mentors attending as different Dojos have varying policies and venues for this. 

Also +1 on notification for Champions and Admins.

**Comment by conoramurphy-zz** [comment]
You can currently set amount for tickets so I consider this fulfilled.
