### ISSUE TITLE
Find a Dojo on Coderdojo.com master navbar directs to 404

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#956]
It adds an analytics tracker to the end of the URL which seems to be the problem!

**Comment by DanielBrierton** [comment]
What browser are you seeing this in? Just tested this on Chrome (49, stable) and Firefox (38.7.1 ESR) on Ubuntu and the map loads without any issue.

**Comment by Wardormeur** [comment]
It's basically related to GA, when you navigate from Wordpress header "Find a dojo", ga append some parameters in the url that create an invalid state for ui-router

**Comment by Wardormeur** [comment]
Fixed by cleaning up the navigation system https://github.com/CoderDojo/cp-zen-platform/commit/d1f6402dc589b653dce3bb589cac698aba3b1eed
