### ISSUE TITLE
Error when checking in multiple people as a Champion/Dojo Admin

### ISSUE THREAD

**Issue by rosalanghammer** [CoderDojo/community-platform#958]
![screen shot 2016-05-04 at 17 59 13](https://cloud.githubusercontent.com/assets/12827424/15039554/e1ce54ba-12a5-11e6-8983-7c054f595ad7.png)

**Comment by Wardormeur** [comment]
There was an issue with the badges assignement (which are done through checking-in), so I believe that's what happened here : the service awaited for the badges to be awarded, which didn't respond, creating a timeout here
Closing it, feel free to bump it if it's happening again
