### ISSUE TITLE
Add images for Dojos

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#959]
The idea is to be able to personalize a bit more your dojo page by adding a logo
This must be done as a new migration on cd-dojos to add the field take for reference the avtar field on cd_profiles https://github.com/CoderDojo/cp-users-service/blob/master/scripts/database/pg/migrations/010.do.add-avatar.sql)
I'd recommend using https://github.com/danialfarid/ng-file-upload to upload the file and have a more intuitive UI

**Comment by FleetAdmiral** [comment]
Hey , i'm new to Open Source , so i'd like to take this up , and would appreciate some help along the way too 👍

**Comment by Wardormeur** [comment]
Furrpect, welcome in !
Start with https://github.com/CoderDojo/cp-local-development to prepare your locale environnement of Zen, then please feel free to ask any question, we don't bite :)

**Comment by niccokunzmann** [comment]
I wrote [this](https://github.com/niccokunzmann/cp-automated-development) to automate the development installation and there exists a ready-to-start solution by @josmas, if I remember correctly.

**Comment by Wardormeur** [comment]
We should add this to the list on cp-local-dev for the possible docker images :)

**Comment by josmas** [comment]
@FleetAdmiral this hasn't been updated in a while, but should still work fine (if you use docker and fancy a shortcut): https://hub.docker.com/r/josmas/coderdojo-local-zen/

**Comment by Wardormeur** [comment]
@FleetAdmiral How is it going on? Please keep us updated if you need some help :)

**Comment by FleetAdmiral** [comment]
@Wardormeur Sorry for the delay , kind of caught up with my own internship right now , give me a few days , will do it ASAP 👍

**Comment by Wardormeur** [comment]
No pressure, just don't want you to give up on it by being blocked on a technical issue we could help with :)

**Comment by Wardormeur** [comment]
We took care of it during our ui-refresh ;)
