### ISSUE TITLE
Eventbrite integration

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#966]
We can't compete with a company which business is ticketing, and don't want to if ours users find it adequate to use it more than ours. @rosalanghammer we will probably be needed some specs here to know what we're supposed to link together

**Comment by marcusnygren** [comment]
Something we'd love would be if the Eventbrite integration meant that each user automatically would become a participant of the dojo! 

This would allow us to keep using Eventbrite (which has some functionality we value), but still be able to award CoderDojo badges to participants in a smooth way!

**Comment by Wardormeur** [comment]
I'm afraid it's a bit complex : there is not enough information to 'create' an user on Zen based from eventbrite information. Tickets are booked for multiple users by the parent (generally). For us to map the users on a recurrent basis is purely random.

**Comment by Wardormeur** [comment]
This has been covered last year.
There is some difficulty with multiple dojos per account but works for simples scenarios.
Closing off but feel free to open another for more specific request
