### ISSUE TITLE
Front-end Build system

### ISSUE THREAD

**Issue by Wardormeur** [CoderDojo/community-platform#973]
Everytime we deploy, a good part of our users (even in the team, actually ;)) complains it's broken.
We need to have a build system that allows us to 

- [ ] minify
- [ ] concatenate
- [ ] **Version the ressources so that cache is refreshed**

I'd go with grunt since we already have it used, but open for suggestions as by experience it can get messy (no pipelines). It must work with our actual AWS/CircleCI workflow (probably executed by CircleCI then)

**Comment by DanielBrierton** [comment]
We can also generate our CSS from LESS at build time, instead of through hapi.

I'll throw my vote in for gulp as a build system.

**Comment by Wardormeur** [comment]
min & concat can be both js & css :))

**Comment by butlerx** [comment]
a grunt or gulp task would be easily added to the build procedure on circle before deployment. 
Id also say use grunt since we already use it and dont really want to have people install both

**Comment by Wardormeur** [comment]
@DanielBrierton Can we close this one? :)

**Comment by DanielBrierton** [comment]
@Wardormeur Whoops, meant to respond last week. Yes, yes we can.
