### ISSUE TITLE
All emails are sent in english language

### ISSUE THREAD

**Issue by elnomade** [CoderDojo/community-platform#988]
Even when there are templates for spanish in the crowdin project, all messages are sent in english instead of spanish.

Our Coderdojo is located in Córdoba, Argentina.

This issue was previously reported and even when was closed as solved that never happened. We still receive all emails in english instead of spanish.

[Gmail - Your ticket request for Encuentro #35 - 2016 - Coderdojo Córdoba en PEZS (Evento Especial) has been approved.pdf](https://github.com/CoderDojo/community-platform/files/339410/Gmail.-.Your.ticket.request.for.Encuentro.35.-.2016.-.Coderdojo.Cordoba.en.PEZS.Evento.Especial.has.been.approved.pdf)

https://github.com/CoderDojo/cp-zen-platform/issues/852

**Comment by DanielBrierton** [comment]
Hi Leonardo,

Thanks for the bug report. The specific template for that email has actually not yet been translated to Spanish. https://crowdin.com/translate/zen-community-platform/1147/en-esar

We need to do a cleanup of unused templates from CrowdIn, as I can understand the confusion as an older template for the same purpose is translated.

If you are seeing this issue with emails that have been translated in CrowdIn, then it's possible that the user triggering the email (either you, or a Dojo admin) has their browser locale set to English. I have successfully tested other emails using an Argentinian Spanish locale in my browser, and it has translated correctly.

Daniel

**Comment by elnomade** [comment]
Coderdojo LatAm volunteers completed the Argentinian spanish translation. Currently is 100% complete.
https://crowdin.com/project/zen-community-platform/es-AR

**Comment by elnomade** [comment]
I used a Mozilla Firefox browser, Argentinian spanish version. I used it when I sent the previous email group and a few minutes again. The issue persists.

**Comment by Wardormeur** [comment]
We'll need to add the Argentinian translation not sure it's in our deployment job right now @butlerx

**Comment by butlerx** [comment]
its not currently in our deployment ill add it now

**Comment by Wardormeur** [comment]
Is it fixed?  @elnomade

**Comment by Wardormeur** [comment]
Closed for inactivity, please come back if it still doesn't work :)
