### ISSUE TITLE
"Find nearby Dojos" in Zen does not find

### ISSUE THREAD

**Issue by Geekluca** [CoderDojo/community-platform#993]
I've noticed that it's very hard to find a nearby dojo using "Find nearby Dojo" in Zen.
The following small towns (in north Italy) all have a nearby dojo, but Zen always return "No Dojos match your search query".
Lesmo is 9 km away from CoderDojo [Lissone](https://zen.coderdojo.com/dojo/it/lissone-province-of-monza-and-brianza/lissone) same as Vedano (only 3 km distant from Lissone) or Biassono (only 4 km distant from Lissone) or Seregno (only 7 km distant from Lissone), the answer is always "No Dojos match your search query".

But if you try with Desio (4 km away from Lissone) then Zen correctly returns "Your closest dojo is Lissone".
## 

Gianluca

**Comment by Wardormeur** [comment]
Thanks for the report
We'll try to figure out what's wrong in our implementation, (which is based uon Google's libs and seems to find it for gmaps)

**Comment by Wardormeur** [comment]
Tested and seemd to be fixed with current research
