### ISSUE TITLE
CDF - Add Column to Zen Manage Dojos with Verified Date

### ISSUE THREAD

**Issue by rossoneill** [CoderDojo/community-platform#995]
Create and Addition Column to Display the Verified Date of the Dojos in the Manage Dojos Admin Section.

**Comment by rosalanghammer** [comment]
Solution to replace manual documentation - not top priority as resulting statistics needed will be developed in Stats Platform.

**Comment by DanielBrierton** [comment]
Implemented in CoderDojo/cp-zen-platform#996, closing.
